(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>{const x=Number(String(v??'').replace(/\s/g,'').replace(',','.'));return Number.isFinite(x)?x:0};
const fmt=(v,d=2)=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n(v));
const pct=v=>fmt(v,2)+'%';
const today=()=>new Date().toISOString().slice(0,10);
const shift=d=>{const x=new Date();x.setDate(x.getDate()-d);return x.toISOString().slice(0,10)};
const TIMEOUT=15000;
let baseRows=[],periodRows=[],resultRows=[],currentTab='abc',xyzLoaded=false,busy=false;
function status(t,c=''){const e=$('status');if(e){e.textContent=t;e.className='status-pill '+c}}
function conn(){try{const x=JSON.parse(localStorage.getItem('iikoConnection')||'null');return x?.ip&&x?.port&&x?.login&&x?.password?x:null}catch(_){return null}}
function pick(r,keys){for(const k of keys){if(r?.[k]!==undefined&&r[k]!==null)return r[k];const hit=Object.keys(r||{}).find(x=>x.toLowerCase()===k.toLowerCase());if(hit)return r[hit]}return ''}
function mapRows(a,cols){if(!Array.isArray(a))return [];if(!a.length||!Array.isArray(a[0]))return a;return a.map(r=>Object.fromEntries(r.map((v,i)=>[(cols?.[i]?.name||cols?.[i]?.field||cols?.[i]||('col'+i)),v])))}
function extract(payload){const out=[],seen=new Set();const add=(a,c)=>{for(const r of mapRows(a,c)){if(!r||typeof r!=='object'||Array.isArray(r))continue;const k=JSON.stringify(r);if(!seen.has(k)){seen.add(k);out.push(r)}}};const walk=(v,d=0)=>{if(!v||d>5)return;if(Array.isArray(v)){add(v);return}if(typeof v!=='object')return;const c=v.columns||v.columnNames||v.headers||[];for(const k of ['data','rows','items','result']){const x=v[k];if(Array.isArray(x))add(x,c);else if(x&&typeof x==='object')walk(x,d+1)}};walk(payload);return out}
async function request(body,label){const c=new AbortController();const timer=setTimeout(()=>c.abort(),TIMEOUT);const timeout=new Promise((_,rej)=>setTimeout(()=>rej(new Error('Таймаут: iiko не ответил за 15 секунд.')),TIMEOUT+250));status(label,'loading');try{return await Promise.race([fetch('/api/iiko/olap',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(body),signal:c.signal}),timeout])}catch(e){if(e?.name==='AbortError')throw new Error('Таймаут: iiko не ответил за 15 секунд.');throw e}finally{clearTimeout(timer)}}
async function query(fields,measures,label){const c=conn();if(!c)throw new Error('Не найдено подключение к iiko Server.');const from=$('from').value,to=$('to').value;if(!from||!to)throw new Error('Укажите период анализа.');if(from>to)throw new Error('Дата начала не может быть позже даты окончания.');const body={action:'query',reportType:'SALES',ip:c.ip,port:c.port,login:c.login,password:c.password,from,to,buildSummary:false,groupByRowFields:fields,groupByColumnFields:[],aggregateFields:measures,filters:[{field:'DishType',operator:'IncludeValues',values:['DISH']},{field:'DeletedWithWriteoff',operator:'ExcludeValues',values:['DELETED_WITHOUT_WRITEOFF']}]};const r=await request(body,label);const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch(_){throw new Error(text||('HTTP '+r.status))}if(!r.ok||data.success===false)throw new Error(data.message||('OLAP HTTP '+r.status));const rows=extract(data.report||data);if(!rows.length)throw new Error('iiko не вернул строки продаж за выбранный период.');return rows}
function info(r){return {name:String(pick(r,['DishName','Product.Name','name'])||'Без названия').trim(),code:String(pick(r,['DishCode','DishId','Product.Num','Product.Id'])||'').trim(),group:String(pick(r,['DishGroup','DishGroup.Name'])||'').trim()||'—',category:String(pick(r,['DishCategory','DishCategory.Name','DishCategory.Accounting'])||'').trim()||'—',unit:String(pick(r,['DishMeasureUnit','MeasureUnit'])||'').trim()}}
function dateOf(r){const v=String(pick(r,['OpenDate.Typed','OpenDate','Date','date'])||'');const m=v.match(/\d{4}-\d{2}-\d{2}/);return m?m[0]:''}
function bucket(d){const mode=$('interval').value;if(!d)return '';if(mode==='month')return d.slice(0,7);if(mode==='week'){const x=new Date(d+'T00:00:00'),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x.toISOString().slice(0,10)}return d}
function aggregate(rows,period=false){const m=new Map();for(const r of rows){const i=info(r),k=(i.code||i.name)+'¦'+i.name;if(!m.has(k))m.set(k,{...i,revenue:0,quantity:0,profit:0,periods:new Map()});const x=m.get(k),rev=n(pick(r,['DishSumInt','Sales'])),qty=n(pick(r,['DishAmountInt','DishAmountInt.PerOrder'])),pro=n(pick(r,['ProductCostBase.Profit','Profit']));x.revenue+=rev;x.quantity+=qty;x.profit+=pro;if(period){const b=bucket(dateOf(r));if(b){if(!x.periods.has(b))x.periods.set(b,{revenue:0,quantity:0,profit:0});const p=x.periods.get(b);p.revenue+=rev;p.quantity+=qty;p.profit+=pro}}}return [...m.values()]}
function abc(a,m){const A=n($('abcA').value),B=n($('abcB').value),total=a.reduce((s,x)=>s+Math.max(0,x[m]),0);let cum=0;for(const x of [...a].sort((u,v)=>v[m]-u[m])){cum+=Math.max(0,x[m]);const p=total?cum/total*100:100;x['abc_'+m]=p<=A?'A':p<=B?'B':'C'}return total}
function xyz(a){const metric=$('xyzMetric').value,X=n($('xyzX').value),Y=n($('xyzY').value);const by=new Map(periodRows.map(r=>{const i=info(r),k=(i.code||i.name)+'¦'+i.name;return [k,r]}));for(const x of a){const source=by.get((x.code||x.name)+'¦'+x.name);const vals=source?[]:[ ];if(source){const all=periodRows.filter(r=>{const i=info(r);return (i.code||i.name)+'¦'+i.name===(x.code||x.name)+'¦'+x.name}).map(r=>[dateOf(r),n(pick(r,metric==='quantity'?['DishAmountInt']:metric==='revenue'?['DishSumInt']:['ProductCostBase.Profit']))]);const p=new Map();for(const [d,v] of all){const b=bucket(d);if(b)p.set(b,(p.get(b)||0)+v)}vals.push(...p.values())}let cv=0;if(vals.length>1){const mean=vals.reduce((s,v)=>s+v,0)/vals.length;if(mean){const variance=vals.reduce((s,v)=>s+(v-mean)**2,0)/(vals.length-1);cv=Math.sqrt(variance)/Math.abs(mean)*100}}x.cv=cv;x.xyz=cv<=X?'X':cv<=Y?'Y':'Z';x.matrix=(x.abc_revenue||'C')+x.xyz}}
function calculate(){const a=aggregate(baseRows,false);for(const m of ['revenue','quantity','profit'])abc(a,m);if(xyzLoaded)xyz(a);return a.sort((u,v)=>v.revenue-u.revenue)}
function selected(){return [...document.querySelectorAll('.indicator-box input:checked')].map(x=>x.value)}
function render(){const rows=resultRows;const d=$('distribution');if(currentTab==='abc'){const m=selected()[0]||'revenue',c={A:0,B:0,C:0};rows.forEach(x=>c[x['abc_'+m]]++);const t=rows.length||1;d.innerHTML=['A','B','C'].map(k=>`<div class="dist-row"><span class="dist-label">${k}</span><div class="dist-track"><div class="dist-fill ${k.toLowerCase()}" style="width:${c[k]/t*100}%"></div></div><span class="dist-value">${pct(c[k]/t*100)}</span></div>`).join('')}else{const c={X:0,Y:0,Z:0};rows.forEach(x=>c[x.xyz]++);const t=rows.length||1;d.innerHTML=['X','Y','Z'].map(k=>`<div class="dist-row"><span class="dist-label">${k}</span><div class="dist-track"><div class="dist-fill ${k.toLowerCase()}" style="width:${c[k]/t*100}%"></div></div><span class="dist-value">${pct(c[k]/t*100)}</span></div>`).join('')}const q=($('search').value||'').trim().toLowerCase(),view=q?rows.filter(x=>[x.name,x.code,x.group,x.category].join(' ').toLowerCase().includes(q)):rows;const ms=selected(),h=$('#resultTable thead'),b=$('#resultTable tbody'),f=$('#resultTable tfoot');let cols='<th>Группа</th><th>Категория</th><th>Артикул</th><th class="text-left">Наименование</th><th>Ед. изм.</th>';if(currentTab==='abc')for(const m of ms)cols+=`<th>${m==='revenue'?'Выручка':m==='quantity'?'Количество продаж':'Прибыль'}</th><th>ABC</th>`;else cols+='<th>Коэффициент вариации</th><th>XYZ</th><th>Матрица</th>';h.innerHTML='<tr>'+cols+'</tr>';b.innerHTML=view.length?view.map(x=>{let s=`<td>${esc(x.group)}</td><td>${esc(x.category)}</td><td>${esc(x.code)}</td><td class="text-left"><b>${esc(x.name)}</b></td><td>${esc(x.unit)}</td>`;if(currentTab==='abc')for(const m of ms)s+=`<td class="num">${fmt(x[m],m==='quantity'?3:2)}</td><td><span class="abc-badge ${(x['abc_'+m]||'C').toLowerCase()}">${x['abc_'+m]||'C'}</span></td>`;else s+=`<td class="num">${pct(x.cv||0)}</td><td><span class="xyz-badge ${(x.xyz||'Z').toLowerCase()}">${x.xyz||'Z'}</span></td><td><span class="matrix-badge">${x.matrix||'CZ'}</span></td>`;return '<tr>'+s+'</tr>'}).join(''):'<tr><td colspan="20" style="text-align:center;padding:35px;color:#7d8b9c">Нет данных</td></tr>';const tot={revenue:view.reduce((s,x)=>s+x.revenue,0),quantity:view.reduce((s,x)=>s+x.quantity,0),profit:view.reduce((s,x)=>s+x.profit,0)};let foot='<tr><th colspan="5" class="text-left">ИТОГО</th>';if(currentTab==='abc')for(const m of ms)foot+=`<th class="num">${fmt(tot[m],m==='quantity'?3:2)}</th><th>—</th>`;else foot+='<th></th><th>—</th><th>—</th>';f.innerHTML=foot+'</tr>';$('rowCount').textContent=view.length+' '+(view.length===1?'позиция':'позиций')}
async function loadABC(){if(busy)return;busy=true;$('run').disabled=true;$('error').hidden=true;try{baseRows=await query(['DishCode','DishName'],['DishSumInt','DishAmountInt','ProductCostBase.Profit'],'Загрузка ABC…');resultRows=calculate();render();status('Готово · '+resultRows.length+' позиций','ok')}catch(e){resultRows=[];render();$('error').hidden=false;$('error').textContent=e.message||String(e);status('Ошибка','error')}finally{busy=false;$('run').disabled=false}}
async function loadXYZ(){if(xyzLoaded||busy)return;busy=true;$('run').disabled=true;$('error').hidden=true;try{periodRows=await query(['OpenDate.Typed','DishCode','DishName'],['DishSumInt','DishAmountInt','ProductCostBase.Profit'],'Загрузка XYZ…');xyzLoaded=true;resultRows=calculate();render();status('Готово · XYZ загружен','ok')}catch(e){$('error').hidden=false;$('error').textContent=e.message||String(e);status('Ошибка','error')}finally{busy=false;$('run').disabled=false}}
function init(){$('from').value=shift(31);$('to').value=today();$('run').onclick=()=>{xyzLoaded=false;periodRows=[];loadABC()};$('export').onclick=()=>{};$('search').oninput=render;$('clearSearch').onclick=()=>{$('search').value='';render()};document.querySelectorAll('.tab').forEach(t=>t.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');currentTab=t.dataset.tab;render();if(currentTab!=='abc')await loadXYZ()});document.querySelectorAll('.indicator-box input,#xyzMetric,#abcA,#abcB,#xyzX,#xyzY,#interval').forEach(e=>e.addEventListener('change',()=>{if(baseRows.length){if(e.id==='interval'&&currentTab!=='abc'){xyzLoaded=false;loadXYZ()}else{resultRows=calculate();render()}}}));if(conn())loadABC();else status('Нет подключения','error')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
