(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;const n=Number(String(v??'').replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:0;};
  const fmt=(v,d=2)=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}).format(num(v));
  const pct=v=>fmt(v,2)+'%';
  const today=()=>{const d=new Date();return d.toISOString().slice(0,10)};
  const shift=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
  const TIMEOUT=20000;
  let connection=null, baseRows=[], periodRows=[], resultRows=[], currentTab='abc', xyzLoaded=false, loading=false;

  function status(t,c=''){const e=$('status');if(e){e.textContent=t;e.className='status-pill '+c}}
  function connectionData(){try{const x=JSON.parse(localStorage.getItem('iikoConnection')||'null');return x?.ip&&x?.port&&x?.login&&x?.password?x:null}catch(_){return null}}
  function pick(r,n){if(!r)return '';for(const k of n){if(r[k]!==undefined&&r[k]!==null)return r[k];const hit=Object.keys(r).find(x=>x.toLowerCase()===k.toLowerCase());if(hit)return r[hit]}return ''}
  function mapRows(a,cols){if(!Array.isArray(a))return [];if(!a.length||!Array.isArray(a[0]))return a;const c=(cols||[]).map(x=>typeof x==='string'?x:(x?.name||x?.field||x?.key||''));return a.map(r=>Object.fromEntries(r.map((v,i)=>[c[i]||('col'+i),v])))}
  function extract(payload){
    const out=[],seen=new Set();
    const add=(a,cols)=>{const rows=mapRows(a,cols);for(const r of rows){if(!r||typeof r!=='object'||Array.isArray(r))continue;const k=JSON.stringify(r);if(!seen.has(k)){seen.add(k);out.push(r)}}};
    const walk=(v,d=0)=>{if(!v||d>6)return;if(Array.isArray(v)){add(v);return}if(typeof v!=='object')return;const cols=v.columns||v.columnNames||v.headers||[];for(const k of ['data','rows','items','result']){const x=v[k];if(Array.isArray(x))add(x,cols);else if(x&&typeof x==='object')walk(x,d+1)}for(const x of Object.values(v))if(x&&typeof x==='object'&&!Array.isArray(x))walk(x,d+1)};
    walk(payload);return out;
  }
  function info(r){return {name:String(pick(r,['DishName','Product.Name','name'])||'Без названия').trim(),code:String(pick(r,['DishCode','DishId','Product.Num','Product.Id'])||'').trim(),group:String(pick(r,['DishGroup','DishGroup.Name','Product.TopParent'])||'').trim()||'Без группы',category:String(pick(r,['DishCategory','DishCategory.Name','DishCategory.Accounting','Product.Category'])||'').trim()||'(без категории)',unit:String(pick(r,['DishMeasureUnit','Product.MeasureUnit','MeasureUnit'])||'').trim(),store:String(pick(r,['Store.Name','Store','StoreName'])||'').trim()||'Без склада'} }
  function dateOf(r){const v=String(pick(r,['OpenDate.Typed','OpenDate','Date','date'])||'');const m=v.match(/\d{4}-\d{2}-\d{2}/);return m?m[0]:''}
  function filters(){const a=[{field:'DishType',operator:'IncludeValues',values:['DISH']},{field:'DeletedWithWriteoff',operator:'ExcludeValues',values:['DELETED_WITHOUT_WRITEOFF']}];for(const [f,id] of [['Store.Name','store'],['DishGroup','group'],['DishCategory','category']]){const v=$(id)?.value;if(v)a.push({field:f,operator:'IncludeValues',values:[v]})}return a}
  function metrics(){const a=['DishSumInt','DishAmountInt'];if(document.querySelector('.indicator-box input[value="profit"]:checked'))a.push('ProductCostBase.Profit');return a}
  async function post(body,label){
    const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),TIMEOUT);status(label||'Запрос данных iiko…','loading');
    try{return await fetch('/api/iiko/olap',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(body),signal:ctl.signal})}
    catch(e){if(e.name==='AbortError')throw new Error('iiko не ответил за 20 секунд. OLAP-запрос не завершился.');throw e}
    finally{clearTimeout(tm)}
  }
  async function runQuery(groupFields,extraMeasures,label){
    connection=connectionData();if(!connection)throw new Error('Не найдено подключение к iiko Server.');
    const from=$('from').value,to=$('to').value;if(!from||!to)throw new Error('Укажите период анализа.');if(from>to)throw new Error('Дата начала не может быть позже даты окончания.');
    const body={action:'query',reportType:'SALES',ip:connection.ip,port:connection.port,login:connection.login,password:connection.password,from,to,buildSummary:false,groupByRowFields:groupFields,groupByColumnFields:[],aggregateFields:extraMeasures||metrics(),filters:filters()};
    const r=await post(body,label);const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch(_){throw new Error(text||('HTTP '+r.status))}if(!r.ok||data.success===false)throw new Error(data.message||('OLAP HTTP '+r.status));const rows=extract(data.report||data);if(!rows.length)throw new Error('iiko не вернул строки продаж за выбранный период.');return rows;
  }
  function fill(id,vals){const e=$(id);if(!e)return;const old=e.value;const a=[...new Set(vals.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),'ru'));e.innerHTML='<option value="">Все</option>'+a.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(a.includes(old))e.value=old}
  function updateFilters(rows){const a=rows.map(info);fill('store',a.map(x=>x.store).filter(x=>x!=='Без склада'));fill('group',a.map(x=>x.group).filter(x=>x!=='Без группы'));fill('category',a.map(x=>x.category).filter(x=>x!=='(без категории)'))}
  function aggregate(rows,withPeriods=false){
    const m=new Map();const interval=$('interval').value;
    for(const r of rows){const i=info(r),k=(i.code||i.name)+'¦'+i.name;if(!m.has(k))m.set(k,{...i,revenue:0,quantity:0,profit:0,periods:new Map()});const x=m.get(k);const rev=num(pick(r,['DishSumInt','Sales'])),qty=num(pick(r,['DishAmountInt','DishAmountInt.PerOrder'])),pro=num(pick(r,['ProductCostBase.Profit','Profit']));x.revenue+=rev;x.quantity+=qty;x.profit+=pro;if(withPeriods){const d=dateOf(r);let b=d;if(interval==='month')b=d.slice(0,7);else if(interval==='week'){const z=new Date(d+'T00:00:00'),day=(z.getDay()+6)%7;z.setDate(z.getDate()-day);b=z.toISOString().slice(0,10)}if(b){if(!x.periods.has(b))x.periods.set(b,{revenue:0,quantity:0,profit:0});const p=x.periods.get(b);p.revenue+=rev;p.quantity+=qty;p.profit+=pro}}
    }return [...m.values()]
  }
  function clientFilter(a){const s=$('store').value,g=$('group').value,c=$('category').value;return a.filter(x=>(!s||x.store===s)&&(!g||x.group===g)&&(!c||x.category===c))}
  function abc(a,m){const A=num($('abcA').value),B=num($('abcB').value),total=a.reduce((s,x)=>s+Math.max(0,x[m]),0);let cum=0;for(const x of [...a].sort((u,v)=>v[m]-u[m])){cum+=Math.max(0,x[m]);const p=total?cum/total*100:100;x['abc_'+m]=p<=A?'A':p<=B?'B':'C'}return total}
  function xyz(a){const metric=$('xyzMetric').value,X=num($('xyzX').value),Y=num($('xyzY').value);for(const x of a){const vals=[...x.periods.values()].map(p=>num(p[metric]));let cv=0;if(vals.length>1){const mean=vals.reduce((s,v)=>s+v,0)/vals.length;if(mean){const v=vals.reduce((s,z)=>s+(z-mean)**2,0)/(vals.length-1);cv=Math.sqrt(v)/Math.abs(mean)*100}}x.cv=cv;x.xyz=cv<=X?'X':cv<=Y?'Y':'Z';x.matrix=(x.abc_revenue||'C')+x.xyz}}
  function calculate(){let a=clientFilter(aggregate(baseRows,false));for(const m of ['revenue','quantity','profit'])abc(a,m);if(xyzLoaded)xyz(clientFilter(aggregate(periodRows,true)));return a.sort((x,y)=>y.revenue-x.revenue)}
  function selected(){return [...document.querySelectorAll('.indicator-box input:checked')].map(x=>x.value)}
  function visible(){const q=($('search').value||'').trim().toLowerCase();return q?resultRows.filter(x=>[x.name,x.code,x.group,x.category,x.store,x.xyz,x.matrix].join(' ').toLowerCase().includes(q)):resultRows}
  function dist(){const e=$('distribution');if(!e)return;if(currentTab==='xyz'||currentTab==='matrix'){if(!xyzLoaded){e.innerHTML='<div class="small-note">XYZ загружается при первом открытии этого отчёта.</div>';return}const c={X:0,Y:0,Z:0};resultRows.forEach(x=>c[x.xyz]++);const t=resultRows.length||1;e.innerHTML=['X','Y','Z'].map(k=>`<div class="dist-row"><span class="dist-label">${k}</span><div class="dist-track"><div class="dist-fill ${k.toLowerCase()}" style="width:${c[k]/t*100}%"></div></div><span class="dist-value">${pct(c[k]/t*100)}</span></div>`).join('');return}const m=selected()[0]||'revenue',c={A:0,B:0,C:0};resultRows.forEach(x=>c[x['abc_'+m]]++);const t=resultRows.length||1;e.innerHTML=['A','B','C'].map(k=>`<div class="dist-row"><span class="dist-label">${k}</span><div class="dist-track"><div class="dist-fill ${k.toLowerCase()}" style="width:${c[k]/t*100}%"></div></div><span class="dist-value">${pct(c[k]/t*100)}</span></div>`).join('')}
  function table(){const rows=visible(),h=$('#resultTable thead'),b=$('#resultTable tbody'),f=$('#resultTable tfoot');let cols='<th>Группа</th><th>Категория</th><th>Артикул</th><th class="text-left">Наименование</th><th>Ед. изм.</th>',ms=selected();if(currentTab==='abc'||currentTab==='matrix')for(const m of ms)cols+=`<th>${m==='revenue'?'Выручка':m==='quantity'?'Количество продаж':'Прибыль'}</th><th>ABC</th>`;if(currentTab==='xyz'||currentTab==='matrix')cols+='<th>Коэффициент вариации</th><th>XYZ</th>';if(currentTab==='matrix')cols+='<th>Матрица</th>';h.innerHTML='<tr>'+cols+'</tr>';b.innerHTML=rows.length?rows.map(x=>{let s=`<td>${esc(x.group)}</td><td>${esc(x.category)}</td><td>${esc(x.code)}</td><td class="text-left"><b>${esc(x.name)}</b></td><td>${esc(x.unit)}</td>`;if(currentTab==='abc'||currentTab==='matrix')for(const m of ms)s+=`<td class="num">${fmt(x[m],m==='quantity'?3:2)}</td><td><span class="abc-badge ${(x['abc_'+m]||'C').toLowerCase()}" >${x['abc_'+m]||'C'}</span></td>`;if(currentTab==='xyz'||currentTab==='matrix')s+=`<td class="num">${pct(x.cv||0)}</td><td><span class="xyz-badge ${(x.xyz||'Z').toLowerCase()}" >${x.xyz||'Z'}</span></td>`;if(currentTab==='matrix')s+=`<td><span class="matrix-badge ${(x.matrix||'CZ').toLowerCase()}" >${x.matrix||'CZ'}</span></td>`;return '<tr>'+s+'</tr>'}).join(''):'<tr><td colspan="20" style="text-align:center;padding:35px;color:#7d8b9c">Нет данных</td></tr>';const totals={revenue:rows.reduce((s,x)=>s+x.revenue,0),quantity:rows.reduce((s,x)=>s+x.quantity,0),profit:rows.reduce((s,x)=>s+x.profit,0)};let q='<tr><th colspan="5" class="text-left">ИТОГО</th>';if(currentTab==='abc'||currentTab==='matrix')for(const m of ms)q+=`<th class="num">${fmt(totals[m],m==='quantity'?3:2)}</th><th>—</th>`;if(currentTab==='xyz'||currentTab==='matrix')q+='<th></th><th>—</th>';if(currentTab==='matrix')q+='<th>—</th>';f.innerHTML=q+'</tr>';if($('rowCount'))$('rowCount').textContent=rows.length+' '+(rows.length===1?'позиция':'позиций')}
  function render(){dist();table()}
  async function loadBase(){if(loading)return;loading=true;$('run').disabled=true;$('error').hidden=true;try{baseRows=await runQuery(['DishCode','DishName','DishGroup','DishCategory','Store.Name'],metrics(),'Загрузка ABC…');updateFilters(baseRows);resultRows=calculate();render();status('Готово · '+resultRows.length+' позиций','ok')}catch(e){resultRows=[];render();$('error').hidden=false;$('error').textContent=e.message||String(e);status('Ошибка','error')}finally{loading=false;$('run').disabled=false}}
  async function loadXYZ(){if(xyzLoaded)return;loading=true;$('run').disabled=true;$('error').hidden=true;try{periodRows=await runQuery(['OpenDate.Typed','DishCode','DishName'],['DishSumInt','DishAmountInt','ProductCostBase.Profit'],'Загрузка XYZ…');xyzLoaded=true;resultRows=calculate();render();status('Готово · XYZ загружен','ok')}catch(e){$('error').hidden=false;$('error').textContent=e.message||String(e);status('Ошибка','error')}finally{loading=false;$('run').disabled=false}}
  async function run(){xyzLoaded=false;periodRows=[];await loadBase()}
  function csv(){const rows=visible();if(!rows.length)return;const ms=selected(),head=['Группа','Категория','Артикул','Наименование','Ед. изм.'];if(currentTab==='abc'||currentTab==='matrix')for(const m of ms)head.push(m==='revenue'?'Выручка':m==='quantity'?'Количество продаж':'Прибыль','ABC');if(currentTab==='xyz'||currentTab==='matrix')head.push('Коэффициент вариации','XYZ');if(currentTab==='matrix')head.push('Матрица');const lines=[head,...rows.map(x=>{const a=[x.group,x.category,x.code,x.name,x.unit];if(currentTab==='abc'||currentTab==='matrix')for(const m of ms)a.push(x[m],x['abc_'+m]);if(currentTab==='xyz'||currentTab==='matrix')a.push(x.cv,x.xyz);if(currentTab==='matrix')a.push(x.matrix);return a})];const blob=new Blob(['\uFEFF'+lines.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='abc-xyz-'+$('from').value+'-'+$('to').value+'.csv';a.click()}
  function init(){
    $('from').value=shift(31);$('to').value=today();
    $('run').onclick=run;$('export').onclick=csv;$('search').oninput=render;$('clearSearch').onclick=()=>{$('search').value='';render()};
    document.querySelectorAll('.tab').forEach(t=>t.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');currentTab=t.dataset.tab;if((currentTab==='xyz'||currentTab==='matrix')&&!xyzLoaded)await loadXYZ();else render()});
    document.querySelectorAll('.indicator-box input,#xyzMetric,#abcA,#abcB,#xyzX,#xyzY').forEach(e=>e.addEventListener('change',()=>{if(baseRows.length){if(e.id==='xyzMetric'&&!xyzLoaded)return;resultRows=calculate();render()}}));
    ['store','group','category','interval'].forEach(id=>$(id).addEventListener('change',()=>run()));
    if(!connectionData()){status('Нет подключения','error');return}loadBase();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();