(function(){'use strict';const API='/api/iiko/accounts';const KEY='iikoConnection';const $=id=>document.getElementById(id);let all=[];
const TYPES={CASH:'Денежные средства',ACCOUNTS_RECEIVABLE:'Дебиторская задолженность',DEBTS_OF_EMPLOYEES:'Долги сотрудников',CURRENT_ASSET:'Текущие активы',OTHER_CURRENT_ASSET:'Основные средства',INVENTORY_ASSETS:'Складские запасы',EMPLOYEES_LIABILITY:'Расчёты с сотрудниками',ACCOUNTS_PAYABLE:'Расчёты с поставщиками',CLIENTS_LIABILITY:'Расчёты с гостями',OTHER_CURRENT_LIABILITY:'Прочие текущие обязательства',LONG_TERM_LIABILITY:'Долгосрочные обязательства',EQUITY:'Капитал',COST_OF_GOODS_SOLD:'Прямые издержки',INCOME:'Доходы',EXPENSES:'Расходы',OTHER_INCOME:'Прочие доходы',OTHER_EXPENSES:'Прочие расходы'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function conn(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function setStatus(t,kind){const e=$('acc-status');e.textContent=t;e.className='acc-status '+(kind||'')}
function typeName(t){return TYPES[String(t||'').toUpperCase()]||t||'—'}
function renderStats(items){const types=new Set(items.map(x=>x.type).filter(Boolean));$('acc-total').textContent=items.length;$('acc-types').textContent=types.size;$('acc-system').textContent=items.filter(x=>x.system).length;$('acc-custom').textContent=items.filter(x=>!x.system).length}
function render(){const q=$('acc-search').value.trim().toLowerCase(),type=$('acc-type').value,showDeleted=$('acc-deleted').checked;const filtered=all.filter(a=>(showDeleted||!a.deleted)&&(!type||a.type===type)&&(!q||[a.name,a.code,a.id,a.type].join(' ').toLowerCase().includes(q)));$('acc-count').textContent=`${filtered.length} из ${all.length}`;$('acc-body').innerHTML=filtered.length?filtered.map(a=>`<tr><td><b>${esc(a.name)}</b>${a.system?'<span class="acc-system">SYSTEM</span>':''}</td><td>${esc(a.code||'—')}</td><td><span class="acc-type">${esc(typeName(a.type))}</span><small>${esc(a.type||'')}</small></td><td class="acc-id">${esc(a.id)}</td><td>${a.deleted?'<span class="acc-deleted">Удалён</span>':'<span class="acc-active">Активен</span>'}</td><td>${a.customTransactionsAllowed?'Да':'Нет'}</td></tr>`).join(''):'<tr><td colspan="6" class="acc-empty">Счета не найдены</td></tr>'}
async function load(){const c=conn();if(!c?.ip||!c?.port||!c?.login||!c?.password){setStatus('Нет сохранённого подключения к SH Server. Сначала подключите сервер в Настройках.','error');return}const b=$('acc-load');b.disabled=true;setStatus('Получаем список счетов из SH Server…');try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:c.ip,port:c.port,login:c.login,password:c.password,includeDeleted:$('acc-deleted').checked})});const d=await r.json().catch(()=>({success:false,message:'Некорректный ответ'}));if(!r.ok||!d.success)throw new Error(d.message||`HTTP ${r.status}`);all=Array.isArray(d.accounts)?d.accounts:[];const types=[...new Set(all.map(x=>x.type).filter(Boolean))].sort();$('acc-type').innerHTML='<option value="">Все типы счетов</option>'+types.map(t=>`<option value="${esc(t)}">${esc(typeName(t))}</option>`).join('');renderStats(all);render();setStatus(`Загружено ${all.length} счетов из SH Server.`,'ok')}catch(e){all=[];renderStats([]);render();setStatus(e.message||'Ошибка загрузки счетов','error')}finally{b.disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{$('acc-load').addEventListener('click',load);$('acc-search').addEventListener('input',render);$('acc-type').addEventListener('change',render);$('acc-deleted').addEventListener('change',load);load()});})();