(function(){
 const root=document.documentElement;
 const saved=localStorage.getItem('shReportsTheme');
 root.dataset.theme=saved==='light'?'light':'dark';
 function update(){document.querySelectorAll('[data-theme-label]').forEach(e=>e.textContent=root.dataset.theme==='dark'?'☀️ Светлая тема':'🌙 Светлая тема');}
 window.toggleSHTheme=function(){const next=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('shReportsTheme',next);root.dataset.theme=next;update();};
 function loadUnifiedUI(){if(document.getElementById('anarsystem-site-modern'))return;const link=document.createElement('link');link.id='anarsystem-site-modern';link.rel='stylesheet';link.href='site-modern.css?v=3';document.head.appendChild(link);}
 function loadModernUI(){if(document.getElementById('anarsystem-modern-ui'))return;const link=document.createElement('link');link.id='anarsystem-modern-ui';link.rel='stylesheet';link.href='modern-ui.css?v=3';document.head.appendChild(link);if(!document.getElementById('anarsystem-modern-ui-v3')){const v3=document.createElement('link');v3.id='anarsystem-modern-ui-v3';v3.rel='stylesheet';v3.href='modern-ui-v3.css?v=2';document.head.appendChild(v3);}}
 function loadDashboardModern(){const p=location.pathname.toLowerCase();if(!p.endsWith('/index.html')&&!p.endsWith('/'))return;if(document.getElementById('anarsystem-dashboard-modern'))return;const link=document.createElement('link');link.id='anarsystem-dashboard-modern';link.rel='stylesheet';link.href='dashboard-modern.css?v=1';document.head.appendChild(link);}
 function currentPage(){const p=location.pathname.toLowerCase();if(p.endsWith('/reports')||p.endsWith('/reports.html'))return'reports.html';if(p.endsWith('/plugin-control')||p.endsWith('/plugin-control.html'))return'plugin-control.html';if(p.endsWith('/plugin-events')||p.endsWith('/plugin-events.html'))return'plugin-events.html';if(p.endsWith('/settings')||p.endsWith('/settings.html'))return'settings.html';if(p.endsWith('/debug')||p.endsWith('/debug.html'))return'debug.html';if(p.endsWith('/qr-menu')||p.endsWith('/qr-menu.html'))return'qr-menu.html';return'index.html';}
 function buildUnifiedSidebar(){const sidebar=document.querySelector('.sidebar');if(!sidebar||sidebar.dataset.unifiedSidebar==='1')return;const page=currentPage();const active=x=>x===page?' class="active"':'';sidebar.innerHTML=`<nav class="side-nav unified-main-nav"><a href="index.html"${active('index.html')}><span class="side-icon">⌂</span>Dashboard</a><a href="reports.html"${active('reports.html')}><span class="side-icon">▥</span>OLAP Отчёты</a><a href="plugin-control.html"${active('plugin-control.html')}><span class="side-icon">▣</span>Кассы</a><a href="qr-menu.html"${active('qr-menu.html')}><span class="side-icon">▦</span>QR Menu</a><a href="settings.html"${active('settings.html')}><span class="side-icon">⚙</span>Настройки</a></nav><div class="sidebar-spacer"></div>`;sidebar.dataset.unifiedSidebar='1';}
 function loadReportsModern(){if(!location.pathname.endsWith('/reports.html')&&!location.pathname.endsWith('/reports'))return;document.body.classList.add('reports-modern');if(!document.getElementById('reports-modern-css')){const link=document.createElement('link');link.id='reports-modern-css';link.rel='stylesheet';link.href='reports-modern.css?v=3';document.head.appendChild(link);}if(!document.getElementById('reports-modern-fix-css')){const fix=document.createElement('link');fix.id='reports-modern-fix-css';fix.rel='stylesheet';fix.href='reports-modern-fix.css?v=1';document.head.appendChild(fix);}}
 function loadQrMenuSync(){
   if(!location.pathname.endsWith('/qr-menu.html')&&!location.pathname.endsWith('/qr-menu'))return;
   const loadFix=()=>{if(!document.getElementById('qr-menu-fix-script')){const f=document.createElement('script');f.id='qr-menu-fix-script';f.src='qr-menu-fix.js?v=1';document.body.appendChild(f);}};
   const loadSyncFix=()=>{if(!document.getElementById('qr-menu-sync-fix-script')){const x=document.createElement('script');x.id='qr-menu-sync-fix-script';x.src='qr-menu-sync-fix.js?v=1';document.body.appendChild(x);}};
   const loadPublish=()=>{loadFix();loadSyncFix();if(!document.getElementById('qr-menu-publish-script')){const p=document.createElement('script');p.id='qr-menu-publish-script';p.src='qr-menu-publish.js?v=2';document.body.appendChild(p);}};
   if(!document.getElementById('qr-menu-sync-script')){const s=document.createElement('script');s.id='qr-menu-sync-script';s.src='qr-menu-sync.js?v=3';s.onload=loadPublish;document.body.appendChild(s);}else loadPublish();
 }
 loadUnifiedUI();loadModernUI();loadDashboardModern();document.addEventListener('DOMContentLoaded',()=>{update();loadUnifiedUI();loadModernUI();loadDashboardModern();buildUnifiedSidebar();loadReportsModern();loadQrMenuSync();update();const menu=document.querySelector('[data-mobile-menu]'),side=document.querySelector('.sidebar');if(menu&&side)menu.onclick=()=>side.classList.toggle('open');});
})();
