(()=>{
'use strict';
const $=id=>document.getElementById(id);let assets=[],events=[],binding=null,currentAsset=null;
const money=v=>Number(v||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₼';
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const statusText={ACTIVE:'В работе',REPAIR:'В ремонте',DISPOSED:'Списан',SOLD:'Продан'};
const eventText={BREAKDOWN:'Поломка',REPAIR:'Ремонт',MAINTENANCE:'Обслуживание',PART:'Замена детали',INSPECTION:'Осмотр',NOTE:'Заметка'};

async function token(){const client=await window.SHAuth?.createClient?.();if(!client)throw new Error('Supabase Auth не готов');const{data,error}=await client.auth.getSession();const t=data?.session?.access_token;if(error||!t)throw new Error('Сессия пользователя не найдена');return t}
async function api(body=null){const t=await token();const opt=body?{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${t}`},body:JSON.stringify(body)}:{headers:{'Authorization':`Bearer ${t}`}};const r=await fetch('/api/assets',opt);const j=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!j.success)throw new Error(j.message||`HTTP ${r.status}`);return j}
function restaurantName(id){return binding?.restaurants?.find(x=>String(x.id)===String(id))?.name||id||'—'}
function openModal(id){$(id)?.classList.add('show')}
function closeModal(id){$(id)?.classList.remove('show')}
function calcPreview(){const cost=Math.max(0,Number($('purchaseCost').value||0)),salvage=Math.max(0,Number($('salvageValue').value||0)),life=Math.max(1,Number($('usefulLifeMonths').value||1));const base=Math.max(0,cost-salvage),monthly=base/life;$('lifeHint').textContent=`${life} мес. ≈ ${(life/12).toLocaleString('ru-RU',{maximumFractionDigits:1})} лет`;$('calcPreview').innerHTML=`<div><span>Амортизируемая стоимость</span><strong>${money(base)}</strong></div><div><span>Амортизация в месяц</span><strong>${money(monthly)}</strong></div><div><span>После срока службы</span><strong>${money(salvage)}</strong></div>`}
function fillRestaurants(){const list=binding?.restaurants||[];const selects=[$('assetRestaurant')];selects.forEach(s=>{if(!s)return;s.innerHTML=list.length?list.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join(''):'<option value="">Ресторан не определён</option>'});const filter=$('restaurantFilter');if(filter){filter.innerHTML='<option value="">Все рестораны</option>'+list.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}}
function renderKpis(){const active=assets.filter(x=>x.status==='ACTIVE'||x.status==='REPAIR');$('kpiCount').textContent=assets.length;$('kpiCost').textContent=money(assets.reduce((s,x)=>s+Number(x.purchase_cost||0),0));$('kpiMonthly').textContent=money(active.reduce((s,x)=>s+Number(x.monthlyDepreciation||0),0));$('kpiBook').textContent=money(assets.reduce((s,x)=>s+Number(x.bookValue||0),0))}
function filtered(){const q=String($('search').value||'').trim().toLowerCase(),rest=$('restaurantFilter').value,status=$('statusFilter').value;return assets.filter(x=>(!rest||x.restaurant_id===rest)&&(!status||x.status===status)&&(!q||[x.name,x.category,x.inventory_number,x.serial_number,x.location].join(' ').toLowerCase().includes(q)))}
function renderRows(){const list=filtered(),tb=$('assetRows');$('assetCountNote').textContent=`${list.length} из ${assets.length}`;$('assetEmpty').hidden=list.length>0;tb.innerHTML=list.map(x=>`<tr data-id="${esc(x.id)}"><td><div class="asset-name">${esc(x.name)}</div><div class="asset-sub">${esc(x.category||'Без категории')}${x.inventory_number?' · '+esc(x.inventory_number):''}</div></td><td>${esc(restaurantName(x.restaurant_id))}<div class="asset-sub">${esc(x.location||'Место не указано')}</div></td><td><div class="money-main">${money(x.purchase_cost)}</div><div class="asset-sub">введён ${esc(x.in_service_date||'—')}</div></td><td><div class="money-main">${money(x.monthlyDepreciation)}</div><div class="asset-sub">${x.depreciatedMonths||0} мес. начислено</div></td><td><div class="money-main">${money(x.bookValue)}</div><div class="asset-sub">накоплено ${money(x.accumulatedDepreciation)}</div></td><td><span class="status-badge ${esc(x.status)}">${esc(statusText[x.status]||x.status)}</span></td><td class="row-actions"><button data-edit="${esc(x.id)}">Изменить</button></td></tr>`).join('');tb.querySelectorAll('tr[data-id]').forEach(tr=>tr.addEventListener('click',e=>{if(e.target.closest('[data-edit]'))return;showDetail(tr.dataset.id)}));tb.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editAsset(b.dataset.edit)))}
function render(){renderKpis();renderRows()}
function resetAssetForm(){currentAsset=null;$('assetId').value='';$('assetModalTitle').textContent='Новое имущество';$('assetForm').reset();$('usefulLifeMonths').value='60';$('salvageValue').value='0';$('assetStatus').value='ACTIVE';$('purchaseDate').value=today();$('inServiceDate').value=today();if(binding?.departmentIds?.[0])$('assetRestaurant').value=binding.departmentIds[0];$('deleteAsset').hidden=true;calcPreview()}
function editAsset(id){const x=assets.find(a=>a.id===id);if(!x)return;currentAsset=x;$('assetModalTitle').textContent='Редактировать имущество';$('assetId').value=x.id;$('assetName').value=x.name||'';$('assetCategory').value=x.category||'';$('assetRestaurant').value=x.restaurant_id||'';$('inventoryNumber').value=x.inventory_number||'';$('serialNumber').value=x.serial_number||'';$('assetLocation').value=x.location||'';$('purchaseDate').value=x.purchase_date||'';$('inServiceDate').value=x.in_service_date||'';$('purchaseCost').value=x.purchase_cost||0;$('salvageValue').value=x.salvage_value||0;$('usefulLifeMonths').value=x.useful_life_months||60;$('assetStatus').value=x.status||'ACTIVE';$('disposedAt').value=x.disposed_at||'';$('assetNotes').value=x.notes||'';$('deleteAsset').hidden=false;calcPreview();openModal('assetModal')}
function detailFacts(x){return[['Ресторан',restaurantName(x.restaurant_id)],['Категория',x.category||'—'],['Инвентарный №',x.inventory_number||'—'],['Серийный №',x.serial_number||'—'],['Место',x.location||'—'],['Дата покупки',x.purchase_date||'—'],['Ввод в эксплуатацию',x.in_service_date||'—'],['Срок службы',`${x.useful_life_months||0} мес.`],['Окончание амортизации',x.depreciationEndMonth||'—'],['Статус',statusText[x.status]||x.status]].map(([a,b])=>`<div class="fact"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}
function showDetail(id){const x=assets.find(a=>a.id===id);if(!x)return;currentAsset=x;$('detailName').textContent=x.name;$('detailMeta').textContent=[x.category,restaurantName(x.restaurant_id),x.inventory_number].filter(Boolean).join(' · ');$('detailKpis').innerHTML=`<article><span>Стоимость</span><strong>${money(x.purchase_cost)}</strong></article><article><span>В месяц</span><strong>${money(x.monthlyDepreciation)}</strong></article><article><span>Накоплено</span><strong>${money(x.accumulatedDepreciation)}</strong></article><article><span>Остаток</span><strong>${money(x.bookValue)}</strong></article>`;$('detailFacts').innerHTML=detailFacts(x);renderEvents(x.id);openModal('detailModal')}
function renderEvents(assetId){const list=events.filter(e=>e.asset_id===assetId).sort((a,b)=>String(b.event_date).localeCompare(String(a.event_date)));$('eventList').innerHTML=list.length?list.map(e=>`<div class="timeline-item ${esc(e.event_type)}"><div class="timeline-top"><strong>${esc(e.title||eventText[e.event_type]||'Событие')}</strong><span>${esc(e.event_date)}${Number(e.cost)>0?' · <span class="timeline-cost">'+money(e.cost)+'</span>':''}</span></div><p><b>${esc(eventText[e.event_type]||e.event_type)}</b>${e.vendor?' · '+esc(e.vendor):''}${e.description?'<br>'+esc(e.description):''}</p></div>`).join(''):'<div class="timeline-empty">История пока пустая. Добавьте поломку, ремонт или обслуживание.</div>'}
async function refresh(){const j=await api();assets=j.assets||[];events=j.events||[];render()}
async function saveAsset(e){e.preventDefault();const body={action:'saveAsset',id:$('assetId').value||undefined,name:$('assetName').value,category:$('assetCategory').value,restaurantId:$('assetRestaurant').value,inventoryNumber:$('inventoryNumber').value,serialNumber:$('serialNumber').value,location:$('assetLocation').value,purchaseDate:$('purchaseDate').value,inServiceDate:$('inServiceDate').value,purchaseCost:$('purchaseCost').value,salvageValue:$('salvageValue').value,usefulLifeMonths:$('usefulLifeMonths').value,status:$('assetStatus').value,disposedAt:$('disposedAt').value,notes:$('assetNotes').value};await api(body);closeModal('assetModal');await refresh()}
async function deleteAsset(){if(!currentAsset||!confirm(`Удалить «${currentAsset.name}» вместе с историей?`))return;await api({action:'deleteAsset',id:currentAsset.id});closeModal('assetModal');closeModal('detailModal');await refresh()}
async function addEvent(e){e.preventDefault();if(!currentAsset)return;await api({action:'addEvent',assetId:currentAsset.id,eventType:$('eventType').value,eventDate:$('eventDate').value,title:$('eventTitle').value,description:$('eventDescription').value,cost:$('eventCost').value,vendor:$('eventVendor').value});closeModal('eventModal');$('eventForm').reset();$('eventDate').value=today();await refresh();showDetail(currentAsset.id)}
function bind(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));$('addAsset').onclick=()=>{resetAssetForm();openModal('assetModal')};$('assetForm').onsubmit=e=>saveAsset(e).catch(err=>alert(err.message));$('eventForm').onsubmit=e=>addEvent(e).catch(err=>alert(err.message));$('deleteAsset').onclick=()=>deleteAsset().catch(err=>alert(err.message));$('addEvent').onclick=()=>{$('eventForm').reset();$('eventDate').value=today();openModal('eventModal')};$('editFromDetail').onclick=()=>{const id=currentAsset?.id;closeModal('detailModal');if(id)editAsset(id)};['purchaseCost','salvageValue','usefulLifeMonths'].forEach(id=>$(id).addEventListener('input',calcPreview));['search','restaurantFilter','statusFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderRows))}
async function init(){try{bind();if(!window.SH_IikoContext?.getBinding)throw new Error('Контекст ресторана не готов');binding=await window.SH_IikoContext.getBinding(true);fillRestaurants();resetAssetForm();await refresh()}catch(e){console.error(e);$('assetCountNote').textContent='Ошибка: '+e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();