(()=>{
'use strict';
const $=id=>document.getElementById(id);let assets=[],insights=[],binding=null;
const money=v=>Number(v||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₼';
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
async function token(){const c=await window.SHAuth?.createClient?.();if(!c)throw new Error('Supabase Auth не готов');const{data,error}=await c.auth.getSession();const t=data?.session?.access_token;if(error||!t)throw new Error('Сессия пользователя не найдена');return t}
async function api(url){const t=await token(),r=await fetch(url,{headers:{Authorization:`Bearer ${t}`}}),j=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!j.success)throw new Error(j.message||`HTTP ${r.status}`);return j}
function restaurantName(id){return binding?.restaurants?.find(x=>String(x.id)===String(id))?.name||id||'—'}
function merged(){const map=new Map(insights.map(x=>[x.assetId,x]));return assets.map(a=>({...a,insight:map.get(a.id)||null}))}
function active(x){return !['DISPOSED','SOLD'].includes(String(x.status||'').toUpperCase())}
function priority(x){const i=x.insight||{},life=Math.max(0,Number(i.lifeRatio||0)),base=Number(i.replacementCost||x.purchase_cost||x.bookValue||1),repair=Number(i.repairCost12m||0);let s=i.code==='REVIEW_REPLACE'?100:i.code==='SERVICE_DUE'?72:i.code==='WARRANTY'?24:18;s+=Math.round(life*30);if(base>0)s+=Math.min(40,Math.round(repair/base*100));if(Number(i.nextServiceDays)<0)s+=15;return Math.max(0,Math.min(180,s))}
function priorityClass(s){return s>=100?'high':s>=70?'mid':''}
function recClass(code){return code==='REVIEW_REPLACE'?'replace':code==='SERVICE_DUE'?'service':code==='WARRANTY'?'warranty':''}
function fillRestaurants(){const list=binding?.restaurants||[];$('planRestaurant').innerHTML='<option value="">Все рестораны</option>'+list.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}
function filtered(){const q=String($('planSearch').value||'').trim().toLowerCase(),rest=$('planRestaurant').value,code=$('planFilter').value;return merged().filter(x=>active(x)&&(!rest||String(x.restaurant_id)===String(rest))&&(!code||x.insight?.code===code)&&(!q||[x.name,x.category,x.inventory_number,x.serial_number,x.location].join(' ').toLowerCase().includes(q)))}
function renderKpis(){const list=merged().filter(active),now=list;const service=now.filter(x=>x.insight?.nextServiceDays!=null&&Number(x.insight.nextServiceDays)<=30).length,warranty=now.filter(x=>x.insight?.warrantyDaysRemaining!=null&&Number(x.insight.warrantyDaysRemaining)>=0&&Number(x.insight.warrantyDaysRemaining)<=60).length,replace=now.filter(x=>x.insight?.code==='REVIEW_REPLACE').length,repair=now.reduce((s,x)=>s+Number(x.insight?.repairCost12m||0),0);$('kpiActive').textContent=list.length;$('kpiService').textContent=service;$('kpiWarranty').textContent=warranty;$('kpiReplace').textContent=replace;$('kpiRepair12').textContent=money(repair)}
function renderAlerts(){const list=filtered(),alerts=[];for(const x of list){const i=x.insight||{};if(i.nextServiceDays!=null&&Number(i.nextServiceDays)<=30){const d=Number(i.nextServiceDays);alerts.push({sort:d<0?0:10+d,type:d<0?'overdue':'soon',icon:'⚙',name:x.name,text:d<0?`ТО просрочено на ${Math.abs(d)} дн.`:d===0?'Плановое ТО сегодня':`Плановое ТО через ${d} дн.`,side:i.nextServiceDate||'',asset:x})}if(i.warrantyDaysRemaining!=null&&Number(i.warrantyDaysRemaining)>=0&&Number(i.warrantyDaysRemaining)<=60){const d=Number(i.warrantyDaysRemaining);alerts.push({sort:100+d,type:'warranty',icon:'◈',name:x.name,text:d===0?'Гарантия заканчивается сегодня':`Гарантия заканчивается через ${d} дн.`,side:i.warrantyUntil||'',asset:x})}}alerts.sort((a,b)=>a.sort-b.sort);$('alertsCount').textContent=alerts.length;$('alertsList').innerHTML=alerts.length?alerts.slice(0,12).map(a=>`<div class="alert-item ${a.type}"><div class="alert-icon">${a.icon}</div><div class="alert-copy"><b>${esc(a.name)}</b><span>${esc(a.text)} · ${esc(restaurantName(a.asset.restaurant_id))}</span></div><div class="alert-days">${esc(a.side)}</div></div>`).join(''):'<div class="alerts-empty">Ближайших ТО и окончаний гарантии нет.</div>'}
function renderRanking(){const list=filtered().filter(x=>Number(x.insight?.repairCost12m||0)>0).sort((a,b)=>Number(b.insight.repairCost12m)-Number(a.insight.repairCost12m)).slice(0,10),max=Math.max(1,...list.map(x=>Number(x.insight.repairCost12m||0)));$('repairRanking').innerHTML=list.length?list.map((x,idx)=>{const v=Number(x.insight.repairCost12m||0),pct=Math.max(4,Math.min(100,v/max*100));return`<div class="rank-row"><span class="rank-no">${idx+1}</span><div class="rank-main"><b>${esc(x.name)}</b><small>${esc(restaurantName(x.restaurant_id))} · всего ремонтов ${money(x.insight.totalRepairCost||0)}</small><div class="rank-bar"><i style="width:${pct}%"></i></div></div><strong class="rank-value">${money(v)}</strong></div>`}).join(''):'<div class="ranking-empty">За последние 12 месяцев расходы на ремонты не зафиксированы.</div>'}
function renderReplacement(){const list=filtered().sort((a,b)=>priority(b)-priority(a)||Number(b.insight?.repairCost12m||0)-Number(a.insight?.repairCost12m||0));$('replaceCount').textContent=`${list.length} объектов`;$('replacementEmpty').hidden=list.length>0;$('replacementRows').innerHTML=list.map(x=>{const i=x.insight||{},p=priority(x),life=Math.round(Number(i.lifeRatio||0)*100),reason=i.reason||'Недостаточно данных для оценки.';return`<tr><td><span class="priority ${priorityClass(p)}">${p}</span></td><td><div class="obj-name">${esc(x.name)}</div><div class="obj-sub">${esc(x.category||'Без категории')} · ${esc(x.location||'место не указано')}</div></td><td>${esc(restaurantName(x.restaurant_id))}</td><td>${life}%<div class="obj-sub">${Number(x.depreciatedMonths||0)} из ${Number(x.useful_life_months||0)} мес.</div></td><td>${money(x.bookValue)}</td><td>${money(i.repairCost12m||0)}</td><td>${Number(i.replacementCost)>0?money(i.replacementCost):'<span class="muted">не указано</span>'}</td><td><span class="rec-badge ${recClass(i.code)}">${esc(i.label||'Нет оценки')}</span><div class="obj-sub">${esc(reason)}</div></td></tr>`}).join('')}
function render(){renderKpis();renderAlerts();renderRanking();renderReplacement()}
async function refresh(){const btn=$('refreshPlan');btn.disabled=true;btn.textContent='Загрузка…';try{const[a,m]=await Promise.all([api('/api/assets'),api('/api/asset-meta')]);assets=a.assets||[];insights=m.items||[];render()}catch(e){console.error(e);alert('Не удалось загрузить план: '+e.message)}finally{btn.disabled=false;btn.textContent='↻ Обновить'}}
function bind(){$('refreshPlan').onclick=refresh;['planSearch','planRestaurant','planFilter'].forEach(id=>$(id).addEventListener(id==='planSearch'?'input':'change',render))}
async function init(){try{bind();binding=await window.SH_IikoContext?.getBinding?.(true);fillRestaurants();await refresh()}catch(e){console.error(e);alert(e.message)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();