(() => {
  const $ = id => document.getElementById(id);
  const state = { plugins: [], pluginId: '', orders: [], filter: 'all', search: '', busy: false, timer: null, detailCache: new Map(), paymentLoading: new Set() };
  const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const unwrap = v => { if (typeof v === 'string') { try { return JSON.parse(v); } catch { return v; } } return v; };
  const first = v => { if (v == null || v === '') return null; if (Array.isArray(v)) { for (const x of v) { const r=first(x); if(r!=null&&r!=='') return r; } return null; } if(typeof v!=='object') return v; for(const k of ['name','Name','title','Title','value','Value','sum','Sum','amount','Amount','typeName','TypeName','type','Type']) if(v[k]!=null&&v[k]!=='') return v[k]; return null; };
  const num = v => { const x=first(v); if(x==null||x==='') return NaN; if(typeof x==='number') return Number.isFinite(x)?x:NaN; const n=Number(String(x).replace(/\s/g,'').replace(',','.').replace(/[^0-9+\-.]/g,'')); return Number.isFinite(n)?n:NaN; };
  const money = v => { const n=num(v); return Number.isFinite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'; };
  const dt = v => { if(!v)return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?String(v):d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}); };
  const rawStatus = r => String(r?.orderStatus ?? r?.deliveryOrderStatus ?? '').trim();
  const orderState = r => { const s=rawStatus(r).toLowerCase(); if(/deleted|cancelled|canceled|отмен|удал/.test(s))return'other'; if(['closed','paid','закрыт','закрыто'].includes(s)||r?.orderCloseTime||r?.closeTime)return'closed'; if(['new','bill','open','opened','открыт','открыто','новый'].includes(s))return'open'; return'other'; };
  const orderNum = r => String(r?.orderNum ?? r?.number ?? '');
  const amount = r => num(r?.orderExpectedRevenue ?? r?.revenue ?? r?.resultSum ?? r?.orderSum);
  const table = r => r?.orderTables ?? r?.tables ?? '—'; const floor = r => r?.floor ?? r?.restaurantSectionName ?? r?.__sectionName ?? '—'; const waiter = r => r?.waiter ?? '—'; const cashier = r => r?.cashier ?? '—'; const openTime = r => r?.orderOpenDate ?? r?.openTime ?? r?.deliveryOpenTime; const closeTime = r => r?.orderCloseTime ?? r?.closeTime ?? r?.deliveryDeliveryCloseTime;
  const statusText = r => orderState(r)==='closed'?'Закрыт':orderState(r)==='open'?'Открыт':rawStatus(r)||'Другой';
  function extractRows(payload){ const root=unwrap(payload)?.data ?? unwrap(payload) ?? {},out=[]; for(const g of (Array.isArray(root.terminalsGroups)?root.terminalsGroups:[])) for(const s of (Array.isArray(g?.restaurantSections)?g.restaurantSections:[])){ for(const r of (Array.isArray(s.orders)?s.orders:[])) out.push({...r,__sectionName:s.restaurantSectionName||'',__source:'order'}); for(const r of (Array.isArray(s.deliveries)?s.deliveries:[])) out.push({...r,__sectionName:s.restaurantSectionName||'',__source:'delivery'}); for(const x of (Array.isArray(s.reserves)?s.reserves:[])) if(x?.reserveOrder) out.push({...x.reserveOrder,__sectionName:s.restaurantSectionName||'',__source:'reserve'}); } return out; }
  function detailRoot(payload){ const x=unwrap(payload); return x?.data ?? x?.orderDetails ?? x?.order ?? x; }
  function paymentArray(row){ const d=row?.__detail; for(const v of [row?.payments,row?.Payments,row?.paymentItems,row?.PaymentItems,d?.payments,d?.Payments,d?.paymentItems,d?.PaymentItems]) if(Array.isArray(v)) return v; return []; }
  function paymentParts(row){ return paymentArray(row).map(p=>({name:String(p?.name??p?.Name??p?.typeName??p?.TypeName??p?.type?.name??p?.Type?.Name??p?.type??p?.Type??'').trim(),amount:num(p?.value??p?.Value??p?.sum??p?.Sum??p?.amount??p?.Amount)})).filter(p=>p.name); }
  function paymentText(row){ const p=paymentParts(row); return p.length?p.map(x=>x.name).join(', '):'Загрузка…'; }
  async function getPlugins(){ const r=await fetch('/api/plugin/data',{cache:'no-store'}); if(!r.ok)throw Error(`HTTP ${r.status}`); const data=unwrap(await r.json()); let list=Array.isArray(data)?data:(data?.plugins||data?.data||data?.items||[]); if(!Array.isArray(list))list=[]; state.plugins=list.map(x=>x?.data?{...x,...x.data}:x).filter(Boolean); const p=state.plugins.find(x=>x?.pluginId)||state.plugins[0]; state.pluginId=p?.pluginId||''; $('cash-name').textContent=p?.pluginName||p?.groupName||'Касса'; $('cash-subtitle').textContent=p?'Заказы, выручка и оплаты непосредственно от подключённой кассы.':'Подключённая касса не найдена.'; $('connection').className=`cash-connection ${p?'online':'offline'}`; $('connection').textContent=p?'● Касса подключена':'● Нет подключения'; return p; }
  async function request(action,extra={}){ const body={action,...(state.pluginId?{pluginId:state.pluginId}:{}),...extra}; const r=await fetch('/api/plugin/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}); const text=await r.text(); let d; try{d=JSON.parse(text)}catch{throw Error(`Плагин вернул не JSON (HTTP ${r.status})`)} if(!r.ok||d?.success===false&&d?.error)throw Error(d?.error||`HTTP ${r.status}`); return unwrap(d); }
  async function requestDetail(n){ const params={orderNum:String(n),requestDetail:String(n),RequestDetail:String(n),orderNumber:String(n)}; try{const x=await request('Order',{params});const d=detailRoot(x);if(d&&typeof d==='object')return x;}catch{} return request('get_order',{params}); }
  async function enrichPayments(){ const q=state.orders.filter(x=>orderState(x.row)==='closed'&&!paymentParts(x.row).length&&!state.paymentLoading.has(x.num)); if(!q.length)return; q.forEach(x=>state.paymentLoading.add(x.num)); let i=0; const worker=async()=>{while(i<q.length){const x=q[i++];try{const payload=await requestDetail(x.num);const d=detailRoot(payload);if(d&&typeof d==='object'){x.row.__detail=d;state.detailCache.set(x.num,d);renderPayments();renderOrders();}}catch{}finally{state.paymentLoading.delete(x.num);}}}; await Promise.all([worker(),worker(),worker()]); renderPayments();renderOrders(); }
  async function loadOrders(){ if(state.busy)return; state.busy=true; try{await getPlugins(); if(!state.pluginId){state.orders=[];render();return;} const payload=await request('get_orders'); const rows=extractRows(payload),seen=new Set(); state.orders=rows.map(r=>({row:r,num:orderNum(r)})).filter(x=>x.num&&!seen.has(x.num)&&(seen.add(x.num),true)); for(const x of state.orders){const d=state.detailCache.get(x.num);if(d)x.row.__detail=d;} $('cash-updated').textContent=`Обновлено ${new Date().toLocaleTimeString('ru-RU')}`; $('technical-output').textContent=JSON.stringify(payload,null,2); render(); enrichPayments(); }catch(e){$('connection').className='cash-connection offline';$('connection').textContent='● Ошибка получения данных';$('orders').innerHTML=`<tr><td colspan="10" class="error-cell">${esc(e.message||e)}</td></tr>`;$('orders-footer').textContent='Не удалось получить данные от кассы.';}finally{state.busy=false;} }
  const filtered=()=>{const q=state.search.trim().toLowerCase();return state.orders.filter(x=>{const s=orderState(x.row);if(state.filter!=='all'&&s!==state.filter)return false;if(!q)return true;return [x.num,rawStatus(x.row),table(x.row),floor(x.row),waiter(x.row),cashier(x.row),paymentText(x.row)].join(' ').toLowerCase().includes(q);});};
  const plural=(n,a,b,c)=>{const x=Math.abs(n)%100,y=x%10;return x>10&&x<20?c:y===1?a:y>=2&&y<=4?b:c;};
  function renderKpis(){let cs=0,os=0,cc=0,oc=0,other=0;for(const x of state.orders){const s=orderState(x.row),a=amount(x.row);if(s==='closed'){cc++;if(Number.isFinite(a))cs+=a}else if(s==='open'){oc++;if(Number.isFinite(a))os+=a}else other++;}$('closed-sum').textContent=money(cs);$('open-sum').textContent=money(os);$('expected-sum').textContent=money(cs+os);$('orders-count').textContent=state.orders.length;$('closed-count').textContent=`${cc} ${plural(cc,'заказ','заказа','заказов')}`;$('open-count').textContent=`${oc} ${plural(oc,'заказ','заказа','заказов')}`;$('status-counts').textContent=`${cc} закрытых · ${oc} открытых · ${other} других`;}
  function renderPayments(){const map=new Map();let total=0;for(const x of state.orders)if(orderState(x.row)==='closed')for(const p of paymentParts(x.row)){if(!map.has(p.name))map.set(p.name,{name:p.name,amount:0,count:0});const z=map.get(p.name);z.count++;if(Number.isFinite(p.amount)){z.amount+=p.amount;total+=p.amount;}}$('payments-total').textContent=money(total);if(!map.size){$('payments').innerHTML='<div class="empty-state">Загружаем способы оплаты из закрытых заказов…</div>';return;}const max=Math.max(...[...map.values()].map(x=>x.amount),1);$('payments').innerHTML=[...map.values()].sort((a,b)=>b.amount-a.amount).map(p=>`<div class="payment-row"><div class="payment-name">${esc(p.name)}<span class="payment-meta">${p.count} ${plural(p.count,'заказ','заказа','заказов')}</span></div><div class="payment-track"><div class="payment-fill" style="width:${Math.max(2,p.amount/max*100)}%"></div></div><div class="payment-value">${money(p.amount)}</div></div>`).join('');}
  function renderStatus(){const counts={closed:0,open:0,other:0};state.orders.forEach(x=>counts[orderState(x.row)]++);const total=Math.max(state.orders.length,1);$('status-chart').innerHTML=[['closed','Закрытые',counts.closed],['open','Открытые',counts.open],['other','Другие',counts.other]].map(x=>`<div class="status-row"><span class="status-label">${x[1]}</span><div class="status-track"><div class="status-fill ${x[0]}" style="width:${x[2]/total*100}%"></div></div><span class="status-value">${x[2]} · ${(x[2]/total*100).toFixed(0)}%</span></div>`).join('');}
  function renderOrders(){const list=filtered();$('orders').innerHTML=list.map(x=>{const r=x.row,s=orderState(r);return `<tr data-num="${esc(x.num)}"><td class="order-num">#${esc(x.num)}</td><td><span class="order-status ${s}">${esc(statusText(r))}</span></td><td>${esc(table(r))}</td><td>${esc(floor(r))}</td><td>${esc(waiter(r))}</td><td class="order-amount">${money(amount(r))}</td><td>${esc(dt(openTime(r)))}</td><td>${esc(dt(closeTime(r)))}</td><td class="order-payment">${esc(s==='closed'?paymentText(r):'—')}</td><td><span class="open-order">Открыть ↗</span></td></tr>`}).join('')||'<tr><td colspan="10" class="empty-state">Заказы не найдены.</td></tr>';$('orders-footer').textContent=`Показано ${list.length} из ${state.orders.length} заказов · нажмите строку для подробностей`;}
  function detailValue(label,value){return `<div class="detail"><span>${label}</span><strong>${esc(value||'—')}</strong></div>`;}
  function renderItems(d){const items=d?.Items??d?.items??[];if(!Array.isArray(items)||!items.length)return '<div class="modal-empty">Состав заказа отсутствует.</div>';return `<div class="items-table-wrap"><table class="items-table"><thead><tr><th>Блюдо</th><th>Кол-во</th><th>Цена</th><th>Сумма</th><th>Статус</th></tr></thead><tbody>${items.map(i=>{const q=num(i.Amount??i.amount),p=num(i.Price??i.price),sum=num(i.ResultSum??i.resultSum??i.Cost??i.cost);const shown=Number.isFinite(sum)?sum:(Number.isFinite(q)&&Number.isFinite(p)?q*p:NaN);return `<tr><td><strong>${esc(i.Name??i.name??'—')}</strong>${i.Size?`<small>${esc(i.Size)}</small>`:''}${Array.isArray(i.Modifiers)&&i.Modifiers.length?`<div class="item-modifiers">${i.Modifiers.map(m=>`+ ${esc(m.Name??m.name)} × ${esc(m.Amount??m.amount??1)}`).join('<br>')}</div>`:''}</td><td>${Number.isFinite(q)?q:'—'}</td><td>${money(p)}</td><td class="item-total">${money(shown)}</td><td>${esc(i.Status??i.status??'—')}</td></tr>`}).join('')}</tbody></table></div>`;}
  function historyText(ev){const t=String(ev?.pluginEventType??ev?.eventType??ev?.type??ev?.Type??'').toLowerCase();if(/neworder|created|create/.test(t))return'Заказ создан';if(/close|closed/.test(t))return'Заказ закрыт';if(/payment|pay/.test(t))return'Оплата заказа';if(/add.*item|item.*add/.test(t))return'Добавлено блюдо';if(/remove.*item|item.*remove|delete.*item/.test(t))return'Удалено блюдо';if(/delete.*(surcharge|increase)|remove.*(surcharge|increase)|(surcharge|increase).*delete|(surcharge|increase).*remove|deletingsurcharge|removingsurcharge/.test(t))return'Удалена надбавка';if(/delete.*discount|remove.*discount|discount.*delete|discount.*remove|deletingdiscount|removingdiscount/.test(t))return'Удалена скидка';if(/discount/.test(t))return'Применена скидка';if(/surcharge|increase/.test(t))return'Применена надбавка';if(/update|change|edit/.test(t))return'Заказ обновлён';return ev?.pluginEventType||ev?.eventType||'Событие';}
  function historySummary(ev){
    const d=ev?.data||ev?.Data||{};
    const type=String(ev?.pluginEventType??ev?.eventType??ev?.type??ev?.Type??'').toLowerCase();
    const parts=[];
    const add=(label,v)=>{if(v!==undefined&&v!==null&&v!=='')parts.push(`<span><b>${label}</b>${esc(v)}</span>`)};
    const value=(...keys)=>{for(const k of keys){const v=d?.[k]??ev?.[k];if(v!==undefined&&v!==null&&v!=='')return v;}return null;};
    const nested=(obj,keys)=>{if(!obj||typeof obj!=='object')return null;for(const k of keys){if(obj[k]!==undefined&&obj[k]!==null&&obj[k]!=='')return obj[k];}return null;};
    const itemObject=value('product','Product','item','Item','dish','Dish','printedItem','PrintedItem','deletedItem','DeletedItem');
    const itemName=value('productName','ProductName','itemName','ItemName','dishName','DishName','name','Name')||nested(itemObject,['name','Name','title','Title']);
    const qtyRaw=value('quantity','Quantity','qty','Qty','count','Count','itemAmount','ItemAmount','productAmount','ProductAmount','value','Value')||nested(itemObject,['quantity','Quantity','qty','Qty','amount','Amount','count','Count']);
    const qty=num(qtyRaw);
    const itemSumRaw=value('itemSum','ItemSum','productSum','ProductSum','dishSum','DishSum','resultSum','ResultSum','lineSum','LineSum','totalSum','TotalSum','cost','Cost','sum','Sum','amountSum','AmountSum')||nested(itemObject,['resultSum','ResultSum','sum','Sum','totalSum','TotalSum','cost','Cost','price','Price']);
    const itemPriceRaw=value('itemPrice','ItemPrice','productPrice','ProductPrice','dishPrice','DishPrice','price','Price')||nested(itemObject,['price','Price']);
    const itemSum=num(itemSumRaw);
    const itemPrice=num(itemPriceRaw);
    const isItemEvent=/item|printeditem|dish|discount|surcharge|increase/.test(type);

    add('Стол',value('orderTables','OrderTables','table','Table','tables','Tables'));
    add('Официант',value('waiter','Waiter'));
    add('Статус',value('orderStatus','OrderStatus'));

    if(isItemEvent){
      add('Блюдо',itemName);
      if(Number.isFinite(qty))add('Кол-во',qty);
      if(Number.isFinite(itemPrice))add('Цена',money(itemPrice));
      if(Number.isFinite(itemSum))add('Сумма',money(itemSum));
    }else{
      const rev=value('revenue','Revenue');
      if(rev!==null)add('Сумма',money(rev));
      if(itemName)add('Блюдо',itemName);
      if(Number.isFinite(qty))add('Кол-во',qty);
    }
    return parts.join('')||'<span><b>Информация</b>Событие заказа</span>';
  }
  function renderHistory(events){if(!Array.isArray(events)||!events.length)return '<div class="modal-empty">История событий пока недоступна.</div>';const sorted=[...events].sort((a,b)=>new Date(a?.receivedAt??a?.ReceivedAt??0)-new Date(b?.receivedAt??b?.ReceivedAt??0));return `<div class="history-list">${sorted.map(e=>`<div class="history-row"><div class="history-dot"></div><div class="history-main"><div class="history-top"><strong>${esc(historyText(e))}</strong><time>${esc(dt(e?.receivedAt??e?.ReceivedAt))}</time></div><div class="history-info">${historySummary(e)}</div></div></div>`).join('')}</div>`;}
  async function loadHistory(n){const box=$('order-history');box.innerHTML='<div class="modal-loading">Загружаем историю…</div>';try{const r=await fetch(`/api/plugin/order-history?orderNum=${encodeURIComponent(n)}${state.pluginId?`&pluginId=${encodeURIComponent(state.pluginId)}`:''}`,{cache:'no-store'});const d=unwrap(await r.json());const events=d?.events??d?.data?.events??d?.history??d?.data??d;box.innerHTML=renderHistory(Array.isArray(events)?events:[]);}catch(e){box.innerHTML=`<div class="modal-empty">Не удалось загрузить историю: ${esc(e.message)}</div>`;}}
  async function openOrder(n){const modal=$('order-modal');modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');$('order-modal-title').textContent=`Заказ #${n}`;$('order-modal-subtitle').textContent='Загрузка полной информации…';$('order-details').innerHTML='<div class="modal-loading">Загружаем заказ…</div>';$('order-items').innerHTML='';$('order-history').innerHTML='<div class="modal-loading">Загружаем историю…</div>';try{let d=state.detailCache.get(String(n));if(!d){const payload=await requestDetail(n);d=detailRoot(payload);if(d)state.detailCache.set(String(n),d);}if(!d)throw Error('Детализация заказа не получена');const row=state.orders.find(x=>x.num===String(n))?.row;if(row)row.__detail=d;const revenue=d.Revenue??d.revenue??amount(row);const payments=paymentParts({Payments:d.Payments??d.payments});$('order-modal-subtitle').textContent=`${statusText(row||d)} · ${money(revenue)}`;$('order-details').innerHTML=[detailValue('Стол',d.Tables??d.tables??table(row)),detailValue('Зал',d.Floor??d.floor??floor(row)),detailValue('Официант',d.Waiter??d.waiter??waiter(row)),detailValue('Кассир',d.Cashier??d.cashier??cashier(row)),detailValue('Открыт',dt(d.OpenTime??d.openTime??openTime(row))),detailValue('Пробит',dt(d.BillTime??d.billTime)),detailValue('Закрыт',dt(d.CloseTime??d.closeTime??closeTime(row))),detailValue('Оплата',payments.length?payments.map(p=>`${p.name}${Number.isFinite(p.amount)?` · ${money(p.amount)}`:''}`).join(', '):'—')].join('');$('order-items').innerHTML=renderItems(d);loadHistory(n);}catch(e){$('order-details').innerHTML=`<div class="modal-empty">${esc(e.message||e)}</div>`;$('order-items').innerHTML='';loadHistory(n);}}
  function closeModal(){$('order-modal').classList.add('hidden');$('order-modal').setAttribute('aria-hidden','true');}
  function render(){renderKpis();renderPayments();renderStatus();renderOrders();}
  $('refresh')?.addEventListener('click',loadOrders);$('search')?.addEventListener('input',e=>{state.search=e.target.value;renderOrders();});$('filters')?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderOrders();});$('orders')?.addEventListener('click',e=>{const tr=e.target.closest('tr[data-num]');if(tr)openOrder(tr.dataset.num);});document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
  loadOrders(); state.timer=setInterval(loadOrders,30000);
})();