(function(){
"use strict";
const KEY="iikoConnection";
const $=id=>document.getElementById(id);
const money=n=>`${Number(n||0).toLocaleString("ru-RU",{maximumFractionDigits:2})} ₼`;
const num=n=>Number(n||0).toLocaleString("ru-RU",{maximumFractionDigits:2});
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
let conn=null, fields=[], charts={};
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function daysAgo(n){const d=new Date();d.setDate(d.getDate()-n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parseRows(data){let r=data?.report?.rawResponse??data?.report?.data??data?.data??data?.report??[];if(typeof r==="string"){try{r=JSON.parse(r)}catch{r=[]}}return Array.isArray(r)?r:(Array.isArray(r?.data)?r.data:[])}
function fieldName(candidates){const norm=s=>String(s||"").toLowerCase().replace(/[\s._()-]+/g,"");for(const c of candidates){const x=fields.find(f=>norm(f.name)===norm(c)||norm(f.title)===norm(c));if(x)return x.name}for(const c of candidates){const q=norm(c);const x=fields.find(f=>norm(f.name).includes(q)||norm(f.title).includes(q));if(x)return x.name}return null}
async function json(res){const t=await res.text();try{return t?JSON.parse(t):{}}catch{return {success:false,message:t||`HTTP ${res.status}`}}}
async function post(body){const r=await fetch("/api/iiko/olap",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({...body,ip:conn.ip,port:conn.port,login:conn.login,password:conn.password})});const d=await json(r);if(!r.ok||d.success===false)throw new Error(d.message||`OLAP HTTP ${r.status}`);return d}
async function loadFields(){const d=await post({action:"fields",reportType:"SALES"});fields=(d.fields||[]).map(f=>typeof f==="string"?{name:f,title:f}:f);if(!fields.length&&d.raw)fields=Object.keys(d.raw).map(x=>({name:x,title:x}));if(!fields.length)throw new Error("iiko не вернул OLAP-поля")}
async function query(rows,measures,from,to){return parseRows(await post({action:"query",reportType:"SALES",groupByRowFields:rows.filter(Boolean),groupByColumnFields:[],measures:measures.filter(Boolean),filters:[{field:fieldName(["OpenDate.Typed","OpenDate"]),operator:"DateRange",from,to}],from,to,buildSummary:true}))}
function setKpi(index,value,sub="OLAP iiko"){const cards=document.querySelectorAll(".kpis .card");if(!cards[index])return;const v=cards[index].querySelector(".kvalue"),s=cards[index].querySelector(".ksub");if(v)v.textContent=value;if(s)s.innerHTML=`<span class="up">●</span> ${esc(sub)}`}
function value(row,name){if(!row)return null;if(Object.prototype.hasOwnProperty.call(row,name))return row[name];const f=fields.find(x=>x.name===name);if(f&&Object.prototype.hasOwnProperty.call(row,f.title))return row[f.title];return null}
function sum(rows,name){return rows.reduce((a,r)=>a+(Number(value(r,name))||0),0)}
function dispose(id){if(charts[id]){charts[id].dispose();delete charts[id]}}
function draw(id,opt){dispose(id);const e=$(id);if(!e)return;charts[id]=echarts.init(e);charts[id].setOption(opt)}
const C={green:"#42d392",blue:"#5b8cff",orange:"#ffb454",red:"#ff6678",purple:"#9b7cff",muted:"#8994a3",grid:"#202a35"};
function axis(data){return{type:"category",data,axisLabel:{color:C.muted},axisLine:{lineStyle:{color:C.grid}},axisTick:{show:false}}}
function emptyChart(id,msg="Нет данных"){dispose(id);const e=$(id);if(e)e.innerHTML=`<div class="dash-empty">${esc(msg)}</div>`}
async function loadDashboard(from,to){
 if(!conn){showDisconnected();return}
 const dateField=fieldName(["OpenDate.Typed","OpenDate"]), revenueField=fieldName(["DishSumInt","DishDiscountSumInt","Sales"]), orderField=fieldName(["UniqOrderId","UniqOrderId.Id"]), categoryField=fieldName(["DishCategory","DishCategory.Accounting","Product.Category"]), dishField=fieldName(["DishName","Product.Name","Dish"]), amountField=fieldName(["DishAmountInt","Amount"]), payField=fieldName(["PayTypes","PayTypes.Group","PaymentType"]), hourField=fieldName(["OpenHour","OpenTime.Hour","Hour","Час открытия"]), profitField=fieldName(["ProductCostBase.Profit","Profit"]);
 if(!dateField||!revenueField)throw new Error("Не найдены необходимые OLAP-поля OpenDate/DishSumInt");
 const [daily,cats,pays,dishes,hours]=await Promise.all([
  query([dateField],[revenueField,orderField],from,to),
  categoryField?query([categoryField],[revenueField],from,to):Promise.resolve([]),
  payField?query([payField],[revenueField],from,to):Promise.resolve([]),
  dishField?query([dishField,categoryField],[revenueField,amountField],from,to):Promise.resolve([]),
  hourField?query([hourField],[revenueField],from,to):Promise.resolve([])
 ]);
 const revenue=sum(daily,revenueField), orders=orderField?sum(daily,orderField):daily.length, avg=orders?revenue/orders:0, profit=profitField?sum(daily,profitField):null;
 setKpi(0,money(revenue),`${from} — ${to} • OLAP`);setKpi(1,num(orders),`${from} — ${to} • OLAP`);setKpi(2,money(avg),"Выручка / чеки • OLAP");setKpi(3,profit!==null?money(profit):"—","Себестоимость/прибыль доступна в iiko OLAP");
 const labels=daily.map(r=>String(value(r,dateField)??"").slice(0,10));
 draw("dashRevenue",{tooltip:{trigger:"axis"},legend:{data:["Выручка"],textStyle:{color:C.muted}},grid:{left:50,right:15,top:40,bottom:35},xAxis:axis(labels),yAxis:{type:"value",axisLabel:{color:C.muted},splitLine:{lineStyle:{color:C.grid}}},series:[{name:"Выручка",type:"line",smooth:true,data:daily.map(r=>Number(value(r,revenueField))||0),symbol:"circle",symbolSize:6,lineStyle:{width:3,color:C.green},itemStyle:{color:C.green},areaStyle:{opacity:.08}}]});
 if(cats.length){draw("dashCat",{tooltip:{trigger:"item"},legend:{bottom:0,textStyle:{color:C.muted}},series:[{type:"pie",radius:["52%","75%"],label:{show:false},data:cats.map((r,i)=>({name:String(value(r,categoryField)||"Без категории"),value:Number(value(r,revenueField))||0,itemStyle:{color:[C.green,C.blue,C.orange,C.red,C.purple][i%5]}}))}]})}else emptyChart("dashCat","Нет данных по категориям");
 if(pays.length){draw("dashPay",{tooltip:{trigger:"item"},series:[{type:"pie",radius:["45%","72%"],label:{color:"#cdd5df"},data:pays.map((r,i)=>({name:String(value(r,payField)||"Другое"),value:Number(value(r,revenueField))||0,itemStyle:{color:[C.blue,C.green,C.orange,C.red,C.purple][i%5]}}))}]})}else emptyChart("dashPay","Нет данных по оплатам");
 const top=dishes.map(r=>({name:String(value(r,dishField)||"—"),cat:String(value(r,categoryField)||"—"),amount:Number(value(r,amountField))||0,revenue:Number(value(r,revenueField))||0})).sort((a,b)=>b.amount-a.amount).slice(0,5);const totalDish=top.reduce((a,x)=>a+x.revenue,0);const tbody=$("dashDishBody");if(tbody)tbody.innerHTML=top.map(x=>`<tr><td><div class="prod"><span class="pimg">🍽</span>${esc(x.name)}</div></td><td>${esc(x.cat)}</td><td>${num(x.amount)}</td><td>${money(x.revenue)}</td><td>${totalDish?((x.revenue/totalDish)*100).toFixed(1):"0.0"}%</td><td><span class="badge">OLAP</span></td></tr>`).join("")||`<tr><td colspan="6" class="dash-empty">Нет данных по блюдам</td></tr>`;
 if(hours.length){const map=new Map();hours.forEach(r=>{let raw=value(r,hourField),h=null;if(typeof raw==="number")h=raw;else{const s=String(raw??"");const m=s.match(/(?:T|\s)(\d{1,2})(?::|$)/);if(m)h=Number(m[1]);else if(/^\d{1,2}$/.test(s.trim()))h=Number(s.trim())}if(h!==null&&h>=0&&h<24)map.set(h,(map.get(h)||0)+(Number(value(r,revenueField))||0))});const hs=[...Array(24)].map((_,h)=>h),vals=hs.map(h=>map.get(h)||0);draw("dashHour",{tooltip:{trigger:"axis"},grid:{left:40,right:10,top:15,bottom:30},xAxis:axis(hs.map(h=>String(h).padStart(2,"0"))),yAxis:{type:"value",axisLabel:{color:C.muted},splitLine:{lineStyle:{color:C.grid}}},series:[{type:"bar",data:vals,barMaxWidth:18,itemStyle:{color:C.green,borderRadius:[5,5,0,0]}}]})}else emptyChart("dashHour","Нет данных по времени");
 let peak="Нет данных";if(hours.length){const m=new Map();hours.forEach(r=>{let raw=value(r,hourField),h=null;if(typeof raw==="number")h=raw;else{const s=String(raw??"");const mt=s.match(/(?:T|\s)(\d{1,2})(?::|$)/);if(mt)h=Number(mt[1]);else if(/^\d{1,2}$/.test(s.trim()))h=Number(s.trim())}if(h!==null&&h>=0&&h<24)m.set(h,(m.get(h)||0)+(Number(value(r,revenueField))||0))});let best=[0,0];m.forEach((v,h)=>{if(v>best[1])best=[h,v]});if(best[1])peak=`${String(best[0]).padStart(2,"0")}:00 — пик выручки`}
 const insights=document.querySelector(".insights");if(insights)insights.innerHTML=`<div class="insight"><b>Пиковое время</b><p>${esc(peak)}</p><div class="progress"><i style="width:87%"></i></div></div><div class="insight"><b>Средний чек</b><p>${money(avg)} по данным OLAP.</p><div class="progress"><i style="width:72%"></i></div></div><div class="insight"><b>Источник данных</b><p>Все показатели Dashboard получены из iiko OLAP.</p><div class="progress"><i style="width:100%"></i></div></div>`;
 const status=$("dashStatus");if(status)status.textContent=`🟢 iiko OLAP • ${from} — ${to}`;
}
function showDisconnected(){setKpi(0,"—","Подключите iiko в Настройках");setKpi(1,"—","Подключите iiko в Настройках");setKpi(2,"—","Подключите iiko в Настройках");setKpi(3,"—","Подключите iiko в Настройках");["dashRevenue","dashCat","dashHour","dashPay"].forEach(id=>emptyChart(id,"Нет подключения к iiko OLAP"));const b=$("dashDishBody");if(b)b.innerHTML=`<tr><td colspan="6" class="dash-empty">Подключите iiko в разделе «Настройки»</td></tr>`}
async function init(){try{const raw=localStorage.getItem(KEY);if(!raw){showDisconnected();return}conn=JSON.parse(raw);if(!conn?.ip||!conn?.port||!conn?.login||!conn?.password){showDisconnected();return}await loadFields();const from=daysAgo(6),to=today();await loadDashboard(from,to);document.querySelectorAll(".period button").forEach(btn=>btn.addEventListener("click",async()=>{document.querySelectorAll(".period button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const n=btn.textContent.trim()==="Сегодня"?0:btn.textContent.trim()==="30 дней"?29:6;try{await loadDashboard(daysAgo(n),today())}catch(e){console.error(e);const msg=$("dashStatus");if(msg)msg.textContent="🔴 OLAP: "+e.message}}));}catch(e){console.error("DASHBOARD OLAP ERROR",e);const msg=$("dashStatus");if(msg)msg.textContent="🔴 OLAP: "+e.message;showDisconnected()}}
window.addEventListener("resize",()=>Object.values(charts).forEach(c=>c.resize()));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
