(function () {
    "use strict";
    const $ = id => document.getElementById(id);
    const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
    function addTrace(level,message,detail=""){const trace=$("debug-trace");if(!trace)return;if(trace.querySelector(".trace-empty"))trace.innerHTML="";const item=document.createElement("div");item.className="trace-item";item.innerHTML=`<div><span class="trace-time">${esc(new Date().toLocaleTimeString("ru-RU"))}</span><span class="trace-level ${esc(level)}">${esc(level.toUpperCase())}</span>${esc(message)}</div>${detail?`<div class="trace-detail">${esc(detail)}</div>`:""}`;trace.appendChild(item);trace.scrollTop=trace.scrollHeight;}
    function clearTrace(){const trace=$("debug-trace");if(trace)trace.innerHTML='<div class="trace-empty">Нажмите «Проверить».</div>';const result=$("debug-result");if(result)result.textContent="Ожидание проверки.";}
    async function run(){clearTrace();const button=$("debug-run"),result=$("debug-result");let c=null;try{c=await window.SH_IikoContext?.get()}catch(_){}if(!c?.ip||!c?.port||!c?.login||!c?.password){addTrace("err","Проверка остановлена","Сначала подключитесь к iiko Server через «Настройки». Все параметры берутся из D1.");return}button.disabled=true;button.textContent="Проверяем...";result.textContent="Отправляем запрос в диагностический API...";addTrace("info","POST /api/iiko/debug",`server=${c.ip}:${c.port}`);addTrace("info","Единое подключение","Используется подключение текущего аккаунта из D1.");try{const response=await fetch("/api/iiko/debug",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(c)});const data=await response.json().catch(()=>({}));if(Array.isArray(data.trace))data.trace.forEach(item=>addTrace(item.level||"info",item.message||"",item.detail||""));if(!response.ok||data.success===false){result.innerHTML=`<span class="danger">Ошибка:</span> ${esc(data.message||`HTTP ${response.status}`)}`;return}result.textContent=data.message||"Проверка завершена."}catch(error){addTrace("err","Ошибка браузерного запроса",error.message||String(error));result.innerHTML='<span class="danger">Не удалось обратиться к диагностическому API.</span>'}finally{button.disabled=false;button.textContent="Проверить"}}
    document.addEventListener("DOMContentLoaded",()=>{$("debug-run")?.addEventListener("click",run);$("debug-clear")?.addEventListener("click",clearTrace);try{const c=window.SH_IikoContext?.getCached?.();if(c){$("debug-result").textContent=`Единое подключение: ${c.connection?.ip||"—"}:${c.connection?.port||"—"} · данные из D1.`}}catch(_){} });
})();
