(function(){
 const root=document.documentElement;
 const type=document.body.dataset.documentType;
 const title=document.body.dataset.documentTitle||'Документы';
 const api='/api/iiko/documents';
 async function getIikoState(){try{if(window.SH_IikoContext?.get)return await window.SH_IikoContext.get();}catch(e){console.warn('[documents] iiko context unavailable',e)}return null;}
 async function getConnection(){const state=await getIikoState();return state?.connection||{};}
 async function getDepartmentIds(){const state=await getIikoState();const ids=state?.identity?.departmentIds||state?.connection?.departmentIds||[];return Array.isArray(ids)?[...new Set(ids.map(String).map(x=>x.trim()).filter(Boolean))]:[];}
 const $=id=>document.getElementById(id);
 function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
 function money(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';}
 function fmtDate(v){const s=String(v||'');return s?new Date(s).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'}):'—';}
 function defaults(){const d=new Date(),to=d.toISOString().slice(0,10);d.setDate(d.getDate()-6);return [d.toISOString().slice(0,10),to];}
 function render(docs){const body=$('documents-body'),empty=$('documents-empty'),details=$('documents-details');if(!docs.length){body.innerHTML='';empty.hidden=false;details.classList.remove('open');return;}empty.hidden=true;body.innerHTML=docs.map((d,i)=>{const place=type==='internalTransfer'?`${esc(d.storeFromName)} → ${esc(d.storeToName)}`:esc(d.storeName);const total=(d.items||[]).reduce((s,x)=>s+(Number(x.cost)||0),0);return `<tr data-index="${i}"><td>${esc(d.documentNumber||d.id||'—')}</td><td>${esc(fmtDate(d.dateIncoming))}</td><td>${esc(d.status||'—')}</td><td>${place}</td><td>${(d.items||[]).length}</td><td>${money(total)}</td></tr>`;}).join('');body.querySelectorAll('tr').forEach(tr=>tr.addEventListener('click',()=>showDetails(docs[Number(tr.dataset.index)])));}
 function showDetails(d){const details=$('documents-details');details.classList.add('open');const rows=[['ID',d.id],['Номер',d.documentNumber],['Дата',fmtDate(d.dateIncoming)],['Статус',d.status],['Комментарий',d.comment],['Склад',type==='internalTransfer'?`${d.storeFromName} → ${d.storeToName}`:d.storeName],['Ревизия',d.revision]];details.innerHTML=`<div class="document-details-head">${esc(title)} № ${esc(d.documentNumber||'')}</div><table>${rows.filter(x=>x[1]!==undefined&&x[1]!==null&&x[1]!=='' ).map(x=>`<tr><td>${esc(x[0])}</td><td>${esc(x[1])}</td></tr>`).join('')}</table><table><thead><tr><th style="padding:9px;text-align:left;color:#6f7c8b;font-size:9px">№</th><th style="padding:9px;text-align:left;color:#6f7c8b;font-size:9px">Товар</th><th style="padding:9px;text-align:left;color:#6f7c8b;font-size:9px">Количество</th><th style="padding:9px;text-align:left;color:#6f7c8b;font-size:9px">Себестоимость</th></tr></thead><tbody>${(d.items||[]).map((x,i)=>`<tr><td>${esc(x.num||i+1)}</td><td>${esc(x.productName||x.productId)}</td><td>${esc(x.amount)}</td><td>${money(x.cost)}</td></tr>`).join('')}</tbody></table>`;}
 async function load(){const c=await getConnection();const departmentIds=await getDepartmentIds();if(!c.ip&&!c.host){$('documents-status').textContent='Нет подключения к SH Server';return;}if(!departmentIds.length){$('documents-status').textContent='Не найден Department ID выбранного SH Server';return;}const from=$('documents-from').value,to=$('documents-to').value;$('documents-status').textContent='Загрузка…';$('documents-load').disabled=true;try{const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...c,type,from,to,departmentIds})});const data=await r.json();if(!r.ok||data.success===false)throw new Error(data.message||`HTTP ${r.status}`);render(data.documents||[]);$('documents-status').textContent=`Готово · найдено ${data.count||0}`;}catch(e){$('documents-status').textContent=`Ошибка: ${e.message}`;render([]);}finally{$('documents-load').disabled=false;}}
 const [from,to]=defaults();$('documents-from').value=from;$('documents-to').value=to;$('documents-load').addEventListener('click',load);load();
})();