(function(){'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const META_KEY='shEventMetadata';
const fallbackNames={dbBackup:'Резервное копирование базы данных',terminalRegistered:'Регистрация терминала',terminalTokenIssued:'Выдача токена терминалу',frontLogout:'Выход пользователя',pinAuthorization:'Авторизация по PIN-коду',orderOpened:'Заказ открыт',addItemToOrder:'Добавление позиции в заказ',removeItemFromOrder:'Удаление позиции из заказа',orderClosed:'Заказ закрыт',orderPaid:'Оплата заказа',orderEdited:'Редактирование заказа',orderDeleted:'Удаление заказа',changeOrder:'Изменение заказа',incomingInvoiceCreated:'Создание приходной накладной',incomingInvoiceEdited:'Редактирование приходной накладной',incomingInvoiceDeleted:'Удаление приходной накладной'};
let metadata={};
function loadEventsStyles(){const id='events-page-styles';if(document.getElementById(id))return;const link=document.createElement('link');link.id=id;link.rel='stylesheet';link.href='events.css?v=3';document.head.appendChild(link);}
function localDateTime(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function setDefaultDates(){const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);$('events-from').value=localDateTime(start);$('events-to').value=localDateTime(now);}
function connection(){try{const raw=localStorage.getItem('iikoConnection');if(!raw)return null;const c=JSON.parse(raw);return c&&c.ip&&c.port&&c.login&&c.password?c:null;}catch{return null;}}
function loadMetadata(){try{const raw=localStorage.getItem(META_KEY);if(raw)metadata=JSON.parse(raw)||{};}catch{metadata={};}}
function saveMetadata(value){if(!value||typeof value!=='object'||!Object.keys(value).length)return;metadata={...metadata,...value};try{localStorage.setItem(META_KEY,JSON.stringify(metadata));}catch{}}
async function safeJson(r){const text=await r.text();if(!text)return{};try{return JSON.parse(text)}catch{return{success:false,message:text||`HTTP ${r.status}`}}}
function status(text,kind=''){const e=$('events-status');if(!e)return;e.textContent=text;e.className=`events-status ${kind}`;}
function formatDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'medium'});}
function eventName(type){const key=String(type||'').trim();return metadata[key]||fallbackNames[key]||key||'Событие';}
function eventUser(event){const a=event?.attributes||{};return a.userName||a.username||a.user||a.waiter||'—';}
function objectValue(event){const a=event?.attributes||{};const keys=['orderNum','orderNumber','orderId','documentNumber','incomingDocumentNumber','receiptSum','tableNum'];for(const k of keys)if(a[k]!==undefined&&String(a[k])!=='')return `${k}: ${a[k]}`;return event.departmentId?`Отдел: ${event.departmentId}`:'—';}
function details(event){const a=event?.attributes||{};const entries=Object.entries(a);if(!entries.length)return'<span class="event-muted">Нет дополнительных данных</span>';return`<details class="event-details"><summary>Показать детали · ${entries.length}</summary><div class="event-attrs">${entries.map(([k,v])=>`<div><b>${esc(k)}</b><span>${esc(v)}</span></div>`).join('')}</div></details>`;}
function iconFor(type){const t=String(type||'').toLowerCase();if(t.includes('open'))return'↗';if(t.includes('close'))return'✓';if(t.includes('add'))return'+';if(t.includes('remove')||t.includes('delete'))return'−';if(t.includes('edit')||t.includes('change'))return'✎';if(t.includes('pay'))return'₽';if(t.includes('login')||t.includes('authorization'))return'⇥';return'•';}
function render(events,total){$('events-count').textContent=events.length;$('events-result-title').innerHTML=(($('events-order').value.trim())?`История объекта <span class="events-object-chip">№ ${esc($('events-order').value.trim())}</span>`:'События')+` <span id="events-count" class="events-count">${events.length}</span>`;const body=$('events-body');body.innerHTML=events.map(e=>{const title=eventName(e.type);return `<tr><td class="event-time">${esc(formatDate(e.date))}</td><td class="event-what"><div class="event-title-row"><span class="event-icon">${esc(iconFor(e.type))}</span><div><strong>${esc(title)}</strong><small>${esc(e.type||'')}</small></div></div></td><td class="event-user"><strong>${esc(eventUser(e))}</strong></td><td class="event-object">${esc(objectValue(e))}</td><td class="event-detail-cell">${details(e)}</td></tr>`;}).join('');$('events-empty').hidden=true;$('events-table-wrap').hidden=false;$('events-summary').hidden=false;$('events-summary').innerHTML=`<span><b>${events.length}</b> событий</span><span>Период: ${esc(formatDate($('events-from').value))} — ${esc(formatDate($('events-to').value))}</span>${metadata&&Object.keys(metadata).length?'<span class="metadata-ready">Названия событий загружены</span>':''}`;return total;}
function resetResult(){$('events-count').textContent='0';$('events-result-title').innerHTML='События <span id="events-count" class="events-count">0</span>';$('events-period').textContent='Период не загружен';$('events-body').innerHTML='';$('events-empty').hidden=false;$('events-table-wrap').hidden=true;$('events-summary').hidden=true;status('Готово к запросу');}
async function load(){const c=connection();if(!c){status('Нет сохранённого подключения','error');return;}const from=$('events-from').value,to=$('events-to').value;if(!from||!to){status('Укажите период','error');return;}if(new Date(to)<=new Date(from)){status('Проверьте период','error');return;}const button=$('events-load');button.disabled=true;button.textContent='Загрузка…';status('Получаем историю из iiko…','loading');$('events-period').textContent=`${formatDate(from)} — ${formatDate(to)}`;try{const payload={ip:c.ip,port:c.port,login:c.login,password:c.password,from:`${from}:00.000`,to:`${to}:00.000`,type:$('events-type').value.trim(),user:$('events-user').value.trim(),order:$('events-order').value.trim(),includeMetadata:Object.keys(metadata).length===0};const r=await fetch('/api/iiko/events',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});const data=await safeJson(r);if(!r.ok||data.success===false)throw new Error(data.message||`HTTP ${r.status}`);saveMetadata(data.metadata);render(data.events||[],data.total||0);status(`Готово · найдено ${data.count||0} из ${data.total||0}`,'success');if(data.count!==data.total)$('events-period').textContent+=` · после фильтров ${data.count} из ${data.total}`;}catch(e){$('events-empty').hidden=false;$('events-table-wrap').hidden=true;$('events-empty').innerHTML=`<div class="events-empty-icon">!</div><strong>Не удалось получить историю</strong><span>${esc(e?.message||'Неизвестная ошибка')}</span>`;status('Ошибка запроса','error');}finally{button.disabled=false;button.textContent='Показать историю';}}
function clear(){setDefaultDates();$('events-type').value='';$('events-user').value='';$('events-order').value='';resetResult();}
function init(){loadEventsStyles();loadMetadata();setDefaultDates();$('events-load').addEventListener('click',load);$('events-clear').addEventListener('click',clear);['events-from','events-to','events-type','events-user','events-order'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')load();}));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
