(function(){'use strict';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const pad=n=>String(n).padStart(2,'0');const META_KEY='shEventMetadata';let metadata={},lastEvents=[];
const fallbackNames={dbBackup:'Резервное копирование базы данных',terminalRegistered:'Регистрация терминала',terminalTokenIssued:'Генерация токена аутентификации',frontLogout:'Выход из iikoFront',pinAuthorization:'Авторизация PIN-кодом',orderOpened:'Открытие заказа',addItemToOrder:'Добавление позиции в заказ',removeItemFromOrder:'Удаление позиции из заказа',orderClosed:'Закрытие заказа',orderPaid:'Оплата заказа',orderEdited:'Редактирование заказа',orderDeleted:'Удаление заказа',changeOrder:'Изменение заказа',documentCreated:'Создание документа',documentEdited:'Редактирование документа',documentDeleted:'Удаление документа'};
function loadEventsStyles(){const id='events-page-styles';if(document.getElementById(id))return;const link=document.createElement('link');link.id=id;link.rel='stylesheet';link.href='events.css?v=8';document.head.appendChild(link)}
function localDateTime(d){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function setDefaultDates(){const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);$('events-from').value=localDateTime(start);$('events-to').value=localDateTime(now)}
function connection(){try{const c=JSON.parse(localStorage.getItem('iikoConnection')||'null');return c&&c.ip&&c.port&&c.login&&c.password?c:null}catch{return null}}
function loadMetadata(){try{metadata=JSON.parse(localStorage.getItem(META_KEY)||'{}')||{}}catch{metadata={}}}
function saveMetadata(v){if(!v||typeof v!=='object'||!Object.keys(v).length)return;metadata={...metadata,...v};try{localStorage.setItem(META_KEY,JSON.stringify(metadata))}catch{}}
function status(t,k=''){$('events-status').textContent=t;$('events-status').className=`events-status ${k}`}
function formatDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'medium'})}
function attrs(e){return e?.attributes||{}}
function attrExact(e,names){const a=attrs(e);for(const n of names){if(a[n]!==undefined&&String(a[n]).trim()!=='')return String(a[n]).trim()}return''}
function attr(e,patterns){for(const[k,v]of Object.entries(attrs(e))){if(patterns.some(p=>p.test(k))&&String(v??'').trim()!=='')return String(v).trim()}return''}
function eventMeta(t){return metadata[String(t||'').trim()]||null}
function eventName(t){const k=String(t||'').trim(),m=eventMeta(k);return typeof m==='object'?(m.name||k):m||fallbackNames[k]||k||'Событие'}
function eventUser(e){return attrExact(e,['resolvedUserName','userName','username','employeeName','employeeFullName'])||attr(e,[/waiterName/i,/employee.*name/i,/user.*name/i,/login/i])||'—'}
function terminal(e){return attrExact(e,['resolvedTerminalName','terminalName','terminalAddress','terminalIp','terminalIP','terminalHost','computerName','computerAddress','computerIp','computerIP'])||attr(e,[/terminal(name|address|ip|host)?/i,/computer(name|address|ip|host)?/i,/machine(name|address|ip|host)?/i,/host(name|address|ip|host)?/i])||'—'}
function shift(e){return attrExact(e,['shiftNumber','sessionNumber','cashSessionNumber','cashShiftNumber'])||attr(e,[/shift(number)?/i,/session(number)?/i])||'—'}
function username(e){return eventUser(e)}
function position(e){return attrExact(e,['position','roleName','post','jobTitle','positionName'])||attr(e,[/role|post|job|долж/i])||'—'}
function documentNumber(e){return attrExact(e,['documentNumber','incomingDocumentNumber','documentNum','invoiceNumber','incomingInvoiceNumber','documentNo','invoiceNo','number','orderNumber','orderNum'])||''}
function documentTitle(e){return attrExact(e,['documentName','documentTitle','documentTypeName','documentCaption','invoiceName','incomingInvoiceName','documentType','name','title','caption'])||attr(e,[/document.*(name|title|type|caption)/i,/invoice.*(name|title|type|caption)/i])||''}
function objectValue(e){const name=documentTitle(e),num=documentNumber(e);if(name&&num)return`${name} №${num}`;if(name)return name;if(num)return`№${num}`;const a=attrs(e);for(const k of ['receiptSum','tableNum'])if(a[k]!==undefined&&String(a[k])!=='')return String(a[k]);if(a.resolvedDocumentId)return`Документ ${a.resolvedDocumentId}`;return e.departmentId||'—'}
function details(e){const parts=[];const name=documentTitle(e),num=documentNumber(e);if(name)parts.push(name);if(num)parts.push(`№${num}`);const terminalValue=terminal(e);if(terminalValue!=='—')parts.push(`Терминал: ${terminalValue}`);const user=eventUser(e);if(user!=='—')parts.push(`Пользователь: ${user}`);if(e.attributes?.resolvedDocumentId&&!name)parts.push(`ID документа: ${e.attributes.resolvedDocumentId}`);return parts.join(' · ')||'—'}
function level(e){const m=eventMeta(e.type);if(m&&m.severity!==null&&m.severity!==undefined)return({0:'Низкая',1:'Средняя',2:'Высокая'}[String(m.severity)]||String(m.severity));return attr(e,[/severity|importance|level/i])||'—'}
function icon(t){const x=String(t||'').toLowerCase();if(x.includes('open'))return'↗';if(x.includes('close'))return'✓';if(x.includes('add'))return'+';if(x.includes('remove')||x.includes('delete'))return'−';if(x.includes('edit')||x.includes('change'))return'✎';if(x.includes('pay'))return'₽';if(x.includes('login')||x.includes('authorization'))return'⇥';if(x.includes('document'))return'▱';return'•'}
function fillSelect(id,values,first){const s=$(id),old=s.value;const unique=[...new Set(values.filter(v=>v&&v!=='—').map(String))].sort((a,b)=>a.localeCompare(b,'ru'));s.innerHTML=`<option value="">${first}</option>`+unique.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(unique.includes(old))s.value=old}
function populateFilters(events){fillSelect('events-type',events.map(e=>eventName(e.type)),'Все события');fillSelect('events-user',events.map(e=>eventUser(e)),'Все сотрудники');fillSelect('events-terminal',events.map(e=>terminal(e)),'Все терминалы')}
function render(events){lastEvents=events;const q=($('events-table-search').value||'').trim().toLowerCase();const visible=q?events.filter(e=>JSON.stringify(e).toLowerCase().includes(q)||eventName(e.type).toLowerCase().includes(q)||details(e).toLowerCase().includes(q)):events;$('events-count').textContent=visible.length;$('events-footer-count').textContent=visible.length;$('events-result-title').textContent='События';const body=$('events-body');body.innerHTML=visible.map(e=>`<tr><td class="event-time">${esc(formatDate(e.date))}</td><td><span class="event-type-icon">${esc(icon(e.type))}</span><strong class="event-human-name">${esc(eventName(e.type))}</strong></td><td>${esc(eventUser(e))}</td><td>${esc(terminal(e))}</td><td>${esc(shift(e))}</td><td>${esc(username(e))}</td><td title="${esc(details(e))}">${esc(objectValue(e))}</td><td>${esc(level(e))}</td><td>${esc(position(e))}</td></tr>`).join('');$('events-table-wrap').hidden=false;$('events-period').textContent=`${formatDate($('events-from').value)} — ${formatDate($('events-to').value)}`}
function applyPreset(){const p=$('events-period-preset').value,now=new Date(),start=new Date(now);if(p==='today')start.setHours(0,0,0,0);else if(p==='yesterday'){start.setDate(start.getDate()-1);start.setHours(0,0,0,0);now.setDate(now.getDate()-1);now.setHours(23,59,0,0)}else if(p==='7days')start.setDate(start.getDate()-6);else return;$('events-from').value=localDateTime(start);$('events-to').value=localDateTime(now)}
async function safeJson(r){const t=await r.text();if(!t)return{};try{return JSON.parse(t)}catch{return{success:false,message:t||`HTTP ${r.status}`}}}
async function load(){const c=connection();if(!c){status('Нет сохранённого подключения','error');return}const from=$('events-from').value,to=$('events-to').value;if(!from||!to){status('Укажите период','error');return}if(new Date(to)<=new Date(from)){status('Проверьте период','error');return}const button=$('events-load');button.disabled=true;button.textContent='Загрузка…';status('Получаем события и справочники…','loading');try{const order=$('events-order').value.trim();const payload={ip:c.ip,port:c.port,login:c.login,password:c.password,from:`${from}:00.000`,to:`${to}:00.000`,type:$('events-type').value,user:$('events-user').value,terminal:$('events-terminal').value,order,document:$('events-document').value.trim(),shift:$('events-shift').value.trim(),severity:$('events-severity').value,includeMetadata:true};const r=await fetch('/api/iiko/events',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});const data=await safeJson(r);if(!r.ok||data.success===false)throw new Error(data.message||`HTTP ${r.status}`);saveMetadata(data.metadata);populateFilters(data.events||[]);render(data.events||[]);status(`Готово · найдено ${data.count||0}`,'success')}catch(e){lastEvents=[];status(e?.message||'Ошибка запроса','error')}finally{button.disabled=false;button.textContent='Показать события'}}
function clear(){setDefaultDates();$('events-period-preset').value='custom';$('events-severity').value='';$('events-type').value='';$('events-user').innerHTML='<option value="">Все сотрудники</option>';$('events-terminal').innerHTML='<option value="">Все терминалы</option>';$('events-order').value='';$('events-document').value='';$('events-shift').value='';$('events-table-search').value='';lastEvents=[];$('events-body').innerHTML='';$('events-count').textContent='0';$('events-footer-count').textContent='0';$('events-table-wrap').hidden=false;$('events-period').textContent='';status('Готово к запросу')}
function init(){loadEventsStyles();loadMetadata();setDefaultDates();$('events-load').addEventListener('click',load);$('events-clear').addEventListener('click',clear);$('events-period-preset').addEventListener('change',applyPreset);$('events-table-search').addEventListener('input',()=>render(lastEvents));$('events-actions').addEventListener('click',()=>{$('events-actions').classList.toggle('open')});['events-from','events-to','events-order','events-document','events-shift'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')load()}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
