(function(){
'use strict';
const SHIFT='/api/iiko/cash-shifts',DETAIL='/api/iiko/cash-shift-detail',ACCOUNTS='/api/iiko/accounts',KEY='iikoConnection';
const $=id=>document.getElementById(id);let accounts=new Map(),accountItems=[],rows=[],shifts=[];
const TYPES={CASH:'Денежные средства',ACCOUNTS_RECEIVABLE:'Дебиторская задолженность',DEBTS_OF_EMPLOYEES:'Долги сотрудников',CURRENT_ASSET:'Текущие активы',OTHER_CURRENT_ASSET:'Основные средства',INVENTORY_ASSETS:'Складские запасы',EMPLOYEES_LIABILITY:'Расчёты с сотрудниками',ACCOUNTS_PAYABLE:'Расчёты с поставщиками',CLIENTS_LIABILITY:'Расчёты с гостями',OTHER_CURRENT_LIABILITY:'Прочие текущие обязательства',LONG_TERM_LIABILITY:'Долгосрочные обязательства',EQUITY:'Капитал',COST_OF_GOODS_SOLD:'Прямые издержки',INCOME:'Доходы',EXPENSES:'Расходы',OTHER_INCOME:'Прочие доходы',OTHER_EXPENSES:'Прочие расходы'};
const money=n=>Number(n||0).toLocaleString('ru-RU',{minimumFractionDigits:0,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const conn=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const iso=d=>d.toISOString().slice(0,10);
const fmtDate=v=>{if(!v)return'—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}.${p[1]}`:String(v)};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const typeName=t=>TYPES[String(t||'').toUpperCase()]||t||'—';
function status(t,k=''){const e=$('fin-status');e.textContent=t;e.className='fin-status '+k}
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({success:false,message:`HTTP ${r.status}`}));if(!r.ok||!d.success)throw new Error(d.message||`HTTP ${r.status}`);return d}
function addMovement(date,accountId,group,sum,comment,shift){const s=Math.abs(num(sum));if(!s)return;const g=String(group||'').toUpperCase();const out=g==='PAYOUT'||g==='PAYOUTS';rows.push({date,accountId,group:g,income:out?0:s,expense:out?s:0,comment,shift})}
function renderAccounts(){const q=($('fin-account-search')?.value||'').trim().toLowerCase(),t=$('fin-account-type')?.value||'';const list=accountItems.filter(a=>(!t||a.type===t)&&(!q||[a.name,a.code,a.id,a.type].join(' ').toLowerCase().includes(q)));$('fin-account-total').textContent=accountItems.length;$('fin-account-types').textContent=new Set(accountItems.map(x=>x.type).filter(Boolean)).size;$('fin-account-system').textContent=accountItems.filter(x=>x.system).length;$('fin-account-custom').textContent=accountItems.filter(x=>!x.system).length;$('fin-accounts-body').innerHTML=list.length?list.map(a=>`<tr><td><b>${esc(a.name)}</b>${a.system?'<span class="fin-system">SYSTEM</span>':''}</td><td>${esc(a.code||'—')}</td><td><span class="fin-type">${esc(typeName(a.type))}</span><small class="fin-type-code">${esc(a.type||'')}</small></td><td>${a.deleted?'<span class="fin-deleted">Удалён</span>':'<span class="fin-active">Активен</span>'}</td><td>${a.customTransactionsAllowed?'Да':'Нет'}</td></tr>`).join(''):'<tr><td colspan="5" class="fin-empty">Счета не найдены</td></tr>'}
function render(){const income=shifts.reduce((s,x)=>{const sh=x.shift||{};return s+num(sh.salesCash)+num(sh.salesCredit)+num(sh.salesCard)+num(sh.payIn)},0),expense=shifts.reduce((s,x)=>{const sh=x.shift||{};return s+num(sh.payOut)+Math.abs(num(sh.payIncome))},0);$('fin-income').textContent=money(income);$('fin-expense').textContent=money(expense);$('fin-turnover').textContent=money(income+expense);const closed=shifts.filter(x=>x.success&&x.shift);const cash=closed.length?closed.reduce((s,x)=>s+num(x.shift.cashRemain),0):0;$('fin-cash').textContent=money(cash);$('fin-count').textContent=`${rows.length} операций`;
const byAccount=new Map();for(const r of rows){const name=accounts.get(String(r.accountId))||r.accountId||'Счёт не указан';const x=byAccount.get(name)||{in:0,out:0};x.in+=r.income;x.out+=r.expense;byAccount.set(name,x)}$('fin-account-list').innerHTML=byAccount.size?[...byAccount.entries()].sort((a,b)=>(b[1].in+b[1].out)-(a[1].in+a[1].out)).slice(0,12).map(([name,x])=>`<div class="fin-account"><div><div class="fin-account-name">${esc(name)}</div><div class="fin-account-meta">Приход ${money(x.in)} · Расход ${money(x.out)}</div></div><div class="fin-account-sum ${x.out>x.in?'expense':''}">${money(x.in-x.out)}</div></div>`).join(''):'<div class="fin-empty">Нет проводок за период</div>';
const byDay=new Map();for(const r of rows){const d=String(r.date||'').slice(0,10);const x=byDay.get(d)||{in:0,out:0};x.in+=r.income;x.out+=r.expense;byDay.set(d,x)}const days=[...byDay.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const max=Math.max(1,...days.map(x=>Math.max(x[1].in,x[1].out)));$('fin-chart').innerHTML=days.length?days.slice(-14).map(([d,x])=>{const hi=Math.max(2,x.in/max*100),ho=Math.max(2,x.out/max*100);return`<div class="fin-bar-col"><div class="fin-bars"><div class="fin-bar in" title="Приход ${money(x.in)}" style="height:${hi}%"></div><div class="fin-bar out" title="Расход ${money(x.out)}" style="height:${ho}%"></div></div><div class="fin-day">${fmtDate(d)}</div></div>`}).join(''):'<div class="fin-empty">Нет движений за выбранный период</div>';
const sorted=[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('fin-body').innerHTML=sorted.length?sorted.map(r=>{const name=accounts.get(String(r.accountId))||r.accountId||'Счёт не указан';const op=r.group==='PAYIN'?'Внесение':r.group==='PAYOUT'?'Изъятие':r.group==='CREDIT'?'Кредит':'Безналичная оплата';return`<tr><td>${fmtDate(r.date)}</td><td><b>${esc(name)}</b><div class="muted">${esc(r.accountId||'')}</div></td><td><span class="fin-op ${r.expense?'out':'in'}">${op}</span></td><td class="plus">${r.income?'+ '+money(r.income):'—'}</td><td class="minus">${r.expense?'− '+money(r.expense):'—'}</td><td class="muted">${esc(r.comment||'—')}</td></tr>`}).join(''):'<tr><td colspan="6" class="fin-empty">Проводки не найдены</td></tr>'}
async function load(){const c=conn();if(!c?.ip||!c?.port||!c?.login||!c?.password){status('Нет сохранённого подключения к SH Server.','error');return}const from=$('fin-from').value,to=$('fin-to').value;if(!from||!to){status('Укажите период.','error');return}const b=$('fin-load');b.disabled=true;rows=[];shifts=[];status('Получаем финансовые данные…');try{const a=await post(ACCOUNTS,{ip:c.ip,port:c.port,login:c.login,password:c.password,includeDeleted:false});accountItems=a.accounts||[];accounts=new Map(accountItems.map(x=>[String(x.id),x.name]));const types=[...new Set(accountItems.map(x=>x.type).filter(Boolean))].sort();$('fin-account-type').innerHTML='<option value="">Все типы</option>'+types.map(t=>`<option value="${esc(t)}">${esc(typeName(t))}</option>`).join('');renderAccounts();const d=await post(SHIFT,{ip:c.ip,port:c.port,login:c.login,password:c.password,from,to});const list=(d.shifts||[]).filter(x=>x._sessionId||x.id);shifts=await Promise.all(list.map(async s=>{try{return await post(DETAIL,{ip:c.ip,port:c.port,login:c.login,password:c.password,sessionId:s._sessionId||s.id})}catch(e){return{success:false,error:e.message,shift:s}}}));for(const item of shifts){if(!item.success)continue;const sh=item.shift||{};const baseDate=String(sh.openDate||item.operationDay||'').slice(0,10)||String(from);const sales=num(sh.salesCash)+num(sh.salesCredit)+num(sh.salesCard);if(sales)addMovement(baseDate,null,'CARD',sales,'Продажи за смену',sh);if(num(sh.payIn))addMovement(baseDate,null,'PAYIN',sh.payIn,'Внесения за смену',sh);if(num(sh.payOut))addMovement(baseDate,null,'PAYOUT',sh.payOut,'Изъятия за смену',sh);if(num(sh.payIncome))addMovement(baseDate,null,'PAYOUT',Math.abs(num(sh.payIncome)),'Изъятие при закрытии смены',sh);for(const p of(item.payments||[]))addMovement(p.date||p.creationDate||baseDate,p.accountId,p.group,p.sum,p.comment,sh)}render();const failed=shifts.filter(x=>!x.success).length;status(`Загружено ${list.length} смен, ${rows.length} движений.${failed?` Не удалось получить детали: ${failed}.`:''}`,'ok')}catch(e){render();status(e.message||'Ошибка загрузки финансов','error')}finally{b.disabled=false}}
function bind(){const now=new Date(),prior=new Date(now);prior.setDate(now.getDate()-6);$('fin-from').value=iso(prior);$('fin-to').value=iso(now);$('fin-load').addEventListener('click',load);$('fin-account-search').addEventListener('input',renderAccounts);$('fin-account-type').addEventListener('change',renderAccounts);document.querySelectorAll('.fin-tabs a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.fin-tabs a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
