(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${(Number(v)||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} ₼`;
const hours=v=>`${((Number(v)||0)/60).toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1})} ч`;
function monthNow(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');return y===2026?`${y}-${m}`:'2026-09'}
async function token(){const c=await window.SHAuth?.createClient?.();if(!c)throw new Error('Supabase Auth не готов');const{data,error}=await c.auth.getSession();const t=data?.session?.access_token;if(error||!t)throw new Error('Сессия пользователя не найдена');return t}
async function api(){const t=await token(),month=$('hrpMonth').value||monthNow(),r=await fetch(`/api/hr/payroll?month=${encodeURIComponent(month)}`,{headers:{Authorization:`Bearer ${t}`,Accept:'application/json'}}),j=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!j.success)throw new Error(j.message||`HTTP ${r.status}`);return j}
function status(text,kind=''){const e=$('hrpStatus');e.textContent=text;e.className=`hr-status ${kind}`.trim()}
function error(text=''){const e=$('hrpError');e.hidden=!text;e.textContent=text}
function source(r){if(r.sourceType==='EMPLOYEE')return'<span class="hrp-source employee">Индивидуально</span>';if(r.sourceType==='ROLE')return'<span class="hrp-source role">По должности</span>';return'<span class="hr-badge pending">Не настроено</span>'}
function badge(r){if(r.status==='READY')return'<span class="hrp-status ready">Готово</span>';if(r.status==='NO_TERMS')return'<span class="hrp-status missing">Нет условий</span>';return'<span class="hrp-status review">Проверить</span>'}
function delta(v){const n=Number(v)||0,cls=n>0?'pos':n<0?'neg':'',sign=n>0?'+':'';return `<span class="hrp-delta ${cls}">${sign}${hours(n)}</span>`}
function summary(d){const s=d.summary||{},t=d.totals||{};$('hrpSummary').innerHTML=`<article class="hr-summary-card"><span>Сотрудники</span><strong>${Number(s.employees||0)}</strong><small>Готово: ${Number(s.ready||0)} · проверить: ${Number(s.review||0)}</small></article><article class="hr-summary-card"><span>Норма месяца</span><strong>${Number(d.calendar?.normHours||0)} ч</strong><small>${Number(d.calendar?.workDays||0)} рабочих дней · на 1 сотрудника</small></article><article class="hr-summary-card"><span>Факт по Face ID</span><strong>${hours(s.actualMinutes||0)}</strong><small>По всем сотрудникам</small></article><article class="hr-summary-card"><span>К выплате сотрудникам</span><strong class="hr-text-value">${money(t.employeeReceives||0)}</strong><small>Стоимость ресторану: ${money(t.employerCost||0)}</small></article>`}
function rows(d){const list=d.rows||[];$('hrpCount').textContent=`${list.length} сотрудников`;$('hrpPeriod').textContent=`${d.period?.from||''} — ${d.period?.to||''} · официальный календарь ${d.calendar?.year||''}`;$('hrpRows').innerHTML=list.map(r=>{const c=r.calculation,o=c?.official,employer=c?.combined?.employer?.total||0,flags=(r.flags||[]).join(' · ')||'—',schedule=r.schedule?.name?`<div class="hr-sub">${esc(r.schedule.name)}</div>`:'';return `<tr><td class="text-left"><div class="hr-name">${esc(r.employeeName)}</div><div class="hr-sub">${esc(r.roleName||'Без должности')} · ${esc(r.employeeCode||'')}</div></td><td>${source(r)}</td><td>${hours(r.normMinutes)}</td><td>${hours(r.plannedMinutes)}${schedule}</td><td class="${r.actualMinutes?'':'hrp-zero'}">${hours(r.actualMinutes)}</td><td>${delta(r.varianceMinutes)}</td><td>${Number(r.attendanceIssues||0)}</td><td class="hrp-money">${o?money(o.gross):'—'}</td><td class="hrp-money">${o?money(o.net):'—'}</td><td>${r.term?money(r.term.additionalAmount):'—'}</td><td class="hrp-money">${c?money(c.totalEmployeeReceives):'—'}</td><td>${c?money(employer):'—'}</td><td class="hrp-money">${c?money(c.totalEmployerCost):'—'}</td><td>${badge(r)}</td><td class="text-left hrp-flags">${esc(flags)}</td></tr>`}).join('')||'<tr><td colspan="15" class="hr-empty">Сотрудники не найдены.</td></tr>'}
async function load(){try{$('hrpRefresh').disabled=true;error();status('Загрузка…','loading');const d=await api();summary(d);rows(d);status('Готово','ok')}catch(e){error(e.message);status('Ошибка','error')}finally{$('hrpRefresh').disabled=false}}
function init(){$('hrpMonth').value=monthNow();$('hrpRefresh').onclick=load;$('hrpMonth').onchange=load;load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();