(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${(Number(v)||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} ₼`;
const hours=v=>`${((Number(v)||0)/60).toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1})} ч`;
function monthNow(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');return y===2026?`${y}-${m}`:'2026-09'}
async function token(){const c=await window.SHAuth?.createClient?.();if(!c)throw new Error('Supabase Auth не готов');const{data,error}=await c.auth.getSession();const t=data?.session?.access_token;if(error||!t)throw new Error('Сессия пользователя не найдена');return t}
async function fetchJson(url,t){const r=await fetch(url,{headers:{Authorization:`Bearer ${t}`,Accept:'application/json'}}),j=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!j.success)throw new Error(j.message||`HTTP ${r.status}`);return j}
async function api(){const t=await token(),month=$('hrpMonth').value||monthNow();const[p,a]=await Promise.all([fetchJson(`/api/hr/payroll?month=${encodeURIComponent(month)}`,t),fetchJson(`/api/hr/payroll-adjustments?month=${encodeURIComponent(month)}`,t)]);return{payroll:p,adjustments:a}}
function status(text,kind=''){const e=$('hrpStatus');e.textContent=text;e.className=`hr-status ${kind}`.trim()}
function error(text=''){const e=$('hrpError');e.hidden=!text;e.textContent=text}
function source(r){if(r.sourceType==='EMPLOYEE')return'<span class="hrp-source employee">Индивидуально</span>';if(r.sourceType==='ROLE')return'<span class="hrp-source role">По должности</span>';return'<span class="hr-badge pending">Не настроено</span>'}
function delta(v){const n=Number(v)||0,cls=n>0?'pos':n<0?'neg':'',sign=n>0?'+':'';return `<span class="hrp-delta ${cls}">${sign}${hours(n)}</span>`}
function combinedBadge(r,a){if(r.status==='NO_TERMS')return'<span class="hrp-status missing">Нет условий</span>';const review=r.status!=='READY'||a?.payroll?.deductionOverCap||Number(a?.meal?.pendingDeduction||0)>0||Number(a?.totals?.drafts||0)>0;return review?'<span class="hrp-status review">Проверить</span>':'<span class="hrp-status ready">Готово</span>'}
function summary(p,a){const s=p.summary||{},x=a.summary||{};$('hrpSummary').innerHTML=`<article class="hr-summary-card"><span>Сотрудники</span><strong>${Number(s.employees||0)}</strong><small>На проверке: ${Number(x.review||s.review||0)}</small></article><article class="hr-summary-card"><span>Норма месяца</span><strong>${Number(p.calendar?.normHours||0)} ч</strong><small>${Number(p.calendar?.workDays||0)} рабочих дней · на 1 сотрудника</small></article><article class="hr-summary-card"><span>Корректировки</span><strong>${money(x.rewards||0)}</strong><small>Авансы: ${money(x.advances||0)} · удержания: ${money(x.deductions||0)}</small></article><article class="hr-summary-card"><span>К выплате сотрудникам</span><strong class="hr-text-value">${money(x.finalPayable||p.totals?.employeeReceives||0)}</strong><small>Стоимость ресторану: ${money(x.employerCost||p.totals?.employerCost||0)}</small></article>`}
function rows(p,a){const adjMap=new Map((a.employees||[]).map(x=>[String(x.id),x])),list=p.rows||[];$('hrpCount').textContent=`${list.length} сотрудников`;$('hrpPeriod').textContent=`${p.period?.from||''} — ${p.period?.to||''} · официальный календарь ${p.calendar?.year||''}`;$('hrpRows').innerHTML=list.map(r=>{const c=r.calculation,o=c?.official,x=adjMap.get(String(r.employeeId)),xt=x?.totals||{},meal=x?.meal||{},final=x?.payroll||{},calc=final.calculation||c,employer=calc?.combined?.employer?.total||0,flags=[...(r.flags||[])];if(Number(xt.drafts||0)>0)flags.push(`Черновики корректировок: ${xt.drafts}`);if(Number(meal.pendingDeduction||0)>0)flags.push(`Питание к подтверждению: ${money(meal.pendingDeduction)}`);if(final.deductionOverCap)flags.push(`Удержания выше обычного лимита 20%: ${money(final.deductionCap)}`);const flagText=flags.join(' · ')||'—',schedule=r.schedule?.name?`<div class="hr-sub">${esc(r.schedule.name)}</div>`:'',mealText=meal.source?`<b>${money(meal.monthNetIncrease)}</b><div class="hr-sub">лимит ${money(meal.limit)} · сверх ${money(meal.overLimit)}</div>`:'—';return `<tr><td class="text-left"><div class="hr-name">${esc(r.employeeName)}</div><div class="hr-sub">${esc(r.roleName||'Без должности')} · ${esc(r.employeeCode||'')}</div></td><td>${source(r)}</td><td>${hours(r.normMinutes)}</td><td>${hours(r.plannedMinutes)}${schedule}</td><td class="${r.actualMinutes?'':'hrp-zero'}">${hours(r.actualMinutes)}</td><td>${delta(r.varianceMinutes)}</td><td>${Number(r.attendanceIssues||0)}</td><td class="hrp-money">${o?money(o.gross):'—'}</td><td class="hrp-money">${o?money(o.net):'—'}</td><td>${r.term?money(r.term.additionalAmount):'—'}</td><td class="hrp-plus">${money(xt.rewards||0)}</td><td class="hrp-minus">${money(xt.advances||0)}</td><td class="hrp-minus">${money(xt.deductions||0)}</td><td>${mealText}</td><td class="hrp-final">${final.baseConfigured?money(final.finalPayable):(c?money(c.totalEmployeeReceives):'—')}</td><td>${calc?money(employer):'—'}</td><td class="hrp-money">${final.baseConfigured?money(final.employerCost):(c?money(c.totalEmployerCost):'—')}</td><td>${combinedBadge(r,x)}</td><td class="text-left hrp-flags">${esc(flagText)}</td></tr>`}).join('')||'<tr><td colspan="19" class="hr-empty">Сотрудники не найдены.</td></tr>'}
async function load(){try{$('hrpRefresh').disabled=true;error();status('Загрузка…','loading');const d=await api();summary(d.payroll,d.adjustments);rows(d.payroll,d.adjustments);status('Готово','ok')}catch(e){error(e.message);status('Ошибка','error')}finally{$('hrpRefresh').disabled=false}}
function init(){$('hrpMonth').value=monthNow();$('hrpRefresh').onclick=load;$('hrpMonth').onchange=load;load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();