(function(){'use strict';
function installPageStyles(){if(document.getElementById('nakladnye-page-style'))return;const l=document.createElement('link');l.id='nakladnye-page-style';l.rel='stylesheet';l.href='/nakladnye.css?v=4';document.head.appendChild(l)}installPageStyles();
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));let documents=[];
function connection(){try{const c=JSON.parse(localStorage.getItem('iikoConnection')||'null');return c&&c.ip&&c.port&&c.login&&c.password?c:null}catch{return null}}
function isoDate(d){const x=new Date(d);if(Number.isNaN(x.getTime()))return'';return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function setDefaults(){const now=new Date();$('invoice-from').value=isoDate(new Date(now.getFullYear(),now.getMonth(),1));$('invoice-to').value=isoDate(now)}
function status(text,kind=''){const el=$('invoice-status');el.textContent=text;el.className=`invoice-status ${kind}`}
function formatMoney(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
function formatDate(v){if(!v)return'—';const s=String(v).trim();const m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:[T\s](\d{2}):(\d{2}))?/);if(m){const d=`${m[3]}.${m[2]}.${m[1]}`;return m[4]?`${d} ${m[4]}:${m[5]}`:d}const d=s.match(/^(\d{2})\.(\d{2})\.(\d{4})/);return d?`${d[1]}.${d[2]}.${d[3]}`:s}
function normalizeStatus(v){return({NEW:'Новая',PROCESSED:'Проведена',DELETED:'Удалена'}[String(v||'').toUpperCase()]||v||'—')}
function supplier(d){return d.supplierName||d.supplier||d.supplierId||'—'}function store(d){return d.storeName||d.store||d.storeId||'—'}
function visibleDocs(){const q=($('invoice-search').value||'').trim().toLowerCase();return q?documents.filter(d=>JSON.stringify(d).toLowerCase().includes(q)):documents}
function render(){const rows=visibleDocs();$('invoice-count').textContent=rows.length;$('invoice-items-count').textContent=rows.reduce((s,d)=>s+Number(d.itemsCount||0),0);$('invoice-total').textContent=formatMoney(rows.reduce((s,d)=>s+Number(d.sum||0),0));$('invoice-body').innerHTML=rows.map(d=>`<tr data-index="${documents.indexOf(d)}"><td><strong>${esc(d.documentNumber||'—')}</strong></td><td>${esc(formatDate(d.dateIncoming||d.incomingDate))}</td><td title="${esc(supplier(d))}">${esc(supplier(d))}</td><td title="${esc(store(d))}">${esc(store(d))}</td><td>${esc(d.invoice||'—')}</td><td>${esc(d.incomingDocumentNumber||'—')}</td><td>${esc(formatDate(d.dueDate))}</td><td><span class="invoice-status-pill status-${String(d.status||'').toLowerCase()}">${esc(normalizeStatus(d.status))}</span></td><td>${esc(d.itemsCount||0)}</td><td class="num">${formatMoney(d.sum)}</td></tr>`).join('');$('invoice-empty').hidden=rows.length>0;if(rows.length)$('invoice-body').querySelectorAll('tr').forEach(tr=>tr.addEventListener('click',()=>openDetails(documents[Number(tr.dataset.index)])))}
function openDetails(d){if(!d)return;$('invoice-details').hidden=false;$('invoice-details-title').textContent=`Накладная №${d.documentNumber||'—'}`;const fields=[['Дата документа',formatDate(d.dateIncoming||d.incomingDate)],['Счёт-фактура',d.invoice],['Входящий номер',d.incomingDocumentNumber],['ТТН',d.transportInvoiceNumber],['Поставщик',supplier(d)],['Склад',store(d)],['Срок оплаты',formatDate(d.dueDate)],['Статус',normalizeStatus(d.status)],['Комментарий',d.comment],['Сумма',formatMoney(d.sum)]];$('invoice-details-grid').innerHTML=fields.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v||'—')}</strong></div>`).join('');$('invoice-items-body').innerHTML=(d.items||[]).map(x=>`<tr><td>${esc(x.num)}</td><td title="${esc(x.productId||'')}">${esc(x.productName||x.productId||'—')}</td><td>${esc(x.productArticle||x.supplierProductArticle||'—')}</td><td>${esc(x.actualAmount??x.amount??'—')}</td><td>${formatMoney(x.price)}</td><td>${esc(x.vatPercent??'—')}</td><td>${formatMoney(x.sum)}</td></tr>`).join('');$('invoice-details').scrollIntoView({behavior:'smooth',block:'start'})}
async function safeJson(r){const t=await r.text();if(!t)return{};try{return JSON.parse(t)}catch{return{success:false,message:t||`HTTP ${r.status}`}}}
async function loadSupplierNames(c){try{const r=await fetch('/api/iiko/contractors',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(c)});const data=await safeJson(r);if(!r.ok||data.success===false)return data;const map=data.suppliers||{};documents=documents.map(d=>{const id=String(d.supplierId||'').trim().replace(/^\{+|\}+$/g,'').toLowerCase();return {...d,supplierName:map[id]||d.supplierName||d.supplierId||'—'};});return data}catch(e){return{success:false,message:e?.message||'Ошибка справочника поставщиков'}}}
async function load(){const c=connection();if(!c){status('Нет сохранённого подключения','error');return}const from=$('invoice-from').value,to=$('invoice-to').value;if(!from||!to){status('Укажите период','error');return}if(to<from){status('Дата «По» раньше даты «С»','error');return}const btn=$('invoice-load');btn.disabled=true;btn.textContent='Загрузка…';status('Получаем накладные из SH Server…','loading');try{const r=await fetch('/api/iiko/incoming-invoices',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...c,from,to})});const data=await safeJson(r);if(!r.ok||data.success===false)throw new Error(data.message||`HTTP ${r.status}`);documents=Array.isArray(data.documents)?data.documents:[];const supplierData=await loadSupplierNames(c);$('invoice-period').textContent=`${formatDate(from)} — ${formatDate(to)}`;render();if(documents.length){const unresolved=documents.filter(d=>!d.supplierName||d.supplierName===d.supplierId).length;const diag=Array.isArray(supplierData?.diagnostics)?supplierData.diagnostics.map(x=>`${x.path}: HTTP ${x.status}, найдено ${x.parsedCount}`).join(' · '):'';status(unresolved?`Готово · найдено ${documents.length} · не сопоставлено ${unresolved} · ${diag}`:`Готово · найдено ${documents.length} · поставщики сопоставлены`,'success')}else status('Накладные не найдены','error')}catch(e){documents=[];render();status(e?.message||'Ошибка загрузки','error')}finally{btn.disabled=false;btn.textContent='Показать накладные'}}
function clear(){documents=[];setDefaults();$('invoice-search').value='';$('invoice-period').textContent='';$('invoice-details').hidden=true;render();status('Готово к запросу')}
function init(){$('invoice-load').addEventListener('click',load);$('invoice-clear').addEventListener('click',clear);$('invoice-search').addEventListener('input',render);$('invoice-details-close').addEventListener('click',()=>$('invoice-details').hidden=true);setDefaults();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
