(function(){'use strict';
function installPageStyles(){if(document.getElementById('nakladnye-page-style'))return;const l=document.createElement('link');l.id='nakladnye-page-style';l.rel='stylesheet';l.href='/nakladnye.css?v=5';document.head.appendChild(l)}installPageStyles();
const PERIOD_KEY='shIncomingInvoicesPeriodV1';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));let documents=[];
async function connection(){if(!window.SH_IikoContext?.get)throw new Error('Единый iiko-контекст D1 не загружен.');const state=await window.SH_IikoContext.get();const c=state?.connection;if(!c?.ip||!c?.port||!c?.login||!c?.password)throw new Error('Нет сохранённого подключения к SH Server. Откройте «Настройки» и подключитесь.');return c}
function isoDate(d){const x=new Date(d);if(Number.isNaN(x.getTime()))return'';return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function setDefaults(){const now=new Date();$('invoice-from').value=isoDate(new Date(now.getFullYear(),now.getMonth(),1));$('invoice-to').value=isoDate(now)}
function savePeriod(){try{localStorage.setItem(PERIOD_KEY,JSON.stringify({from:$('invoice-from').value,to:$('invoice-to').value}))}catch(_){}}
function restorePeriod(){try{const x=JSON.parse(localStorage.getItem(PERIOD_KEY)||'null');if(x?.from&&x?.to){$('invoice-from').value=x.from;$('invoice-to').value=x.to;return true}}catch(_){}setDefaults();return false}
function clearSavedPeriod(){try{localStorage.removeItem(PERIOD_KEY)}catch(_){}}
function status(text,kind=''){const el=$('invoice-status');el.textContent=text;el.className=`invoice-status ${kind}`}
function formatMoney(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
function formatDate(v){if(!v)return'—';const s=String(v).trim();const m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:[T\s](\d{2}):(\d{2}))?/);if(m){const d=`${m[3]}.${m[2]}.${m[1]}`;return m[4]?`${d} ${m[4]}:${m[5]}`:d}const d=s.match(/^(\d{2})\.(\d{2})\.(\d{4})/);return d?`${d[1]}.${d[2]}.${d[3]}`:s}
function normalizeStatus(v){return({NEW:'Новая',PROCESSED:'Проведена',DELETED:'Удалена'}[String(v||'').toUpperCase()]||v||'—')}
function supplier(d){return d.supplierName||d.supplier||d.supplierId||'—'}function store(d){return d.storeName||d.store||d.storeId||'—'}
function visibleDocs(){const q=($('invoice-search').value||'').trim().toLowerCase();return q?documents.filter(d=>JSON.stringify(d).toLowerCase().includes(q)):documents}
function render(){const rows=visibleDocs();$('invoice-count').textContent=rows.length;$('invoice-items-count').textContent=rows.reduce((s,d)=>s+Number(d.itemsCount||0),0);$('invoice-total').textContent=formatMoney(rows.reduce((s,d)=>s+Number(d.sum||0),0));$('invoice-body').innerHTML=rows.map(d=>`<tr data-index="${documents.indexOf(d)}"><td><strong>${esc(d.documentNumber||'—')}</strong></td><td>${esc(formatDate(d.dateIncoming||d.incomingDate))}</td><td title="${esc(supplier(d))}">${esc(supplier(d))}</td><td title="${esc(store(d))}">${esc(store(d))}</td><td>${esc(d.invoice||'—')}</td><td>${esc(d.incomingDocumentNumber||'—')}</td><td>${esc(formatDate(d.dueDate))}</td><td><span class="invoice-status-pill status-${String(d.status||'').toLowerCase()}">${esc(normalizeStatus(d.status))}</span></td><td>${esc(d.itemsCount||0)}</td><td class="num">${formatMoney(d.sum)}</td></tr>`).join('');$('invoice-empty').hidden=rows.length>0;if(rows.length)$('invoice-body').querySelectorAll('tr').forEach(tr=>tr.addEventListener('click',()=>openDetails(documents[Number(tr.dataset.index)])))}
function openDetails(d){if(!d)return;window.SHIncomingInvoices=window.SHIncomingInvoices||{};window.SHIncomingInvoices.selected=d;window.dispatchEvent(new CustomEvent('sh:incoming-invoice-selected',{detail:d}));$('invoice-details').hidden=false;$('invoice-details-title').textContent=`Накладная №${d.documentNumber||'—'}`;const fields=[['Дата документа',formatDate(d.dateIncoming||d.incomingDate)],['Счёт-фактура',d.invoice],['Входящий номер',d.incomingDocumentNumber],['ТТН',d.transportInvoiceNumber],['Поставщик',supplier(d)],['Склад',store(d)],['Срок оплаты',formatDate(d.dueDate)],['Статус',normalizeStatus(d.status)],['Комментарий',d.comment],['Сумма',formatMoney(d.sum)]];$('invoice-details-grid').innerHTML=fields.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v||'—')}</strong></div>`).join('');$('invoice-items-body').innerHTML=(d.items||[]).map(x=>{const packs=Number(x.amount);const actual=Number(x.actualAmount);const pack=Number(x.actualUnitWeight)>0?Number(x.actualUnitWeight):(Number.isFinite(actual)&&Number.isFinite(packs)&&packs>0?actual/packs:1);return `<tr><td>${esc(x.num)}</td><td title="${esc(x.productId||'')}">${esc(x.productName||x.productId||'—')}</td><td>${esc(x.productArticle||x.supplierProductArticle||'—')}</td><td>${esc(Number.isFinite(pack)?pack.toLocaleString('ru-RU',{maximumFractionDigits:3}):'—')} ${esc(x.amountUnit||'')}</td><td>${esc(Number.isFinite(packs)?packs.toLocaleString('ru-RU',{maximumFractionDigits:3}):'—')}</td><td>${esc(Number.isFinite(actual)?actual.toLocaleString('ru-RU',{maximumFractionDigits:3}):(Number.isFinite(packs*pack)?(packs*pack).toLocaleString('ru-RU',{maximumFractionDigits:3}):'—'))} ${esc(x.amountUnit||'')}</td><td>${formatMoney(x.price)}</td><td>${esc(x.vatPercent??0)}%</td><td>${formatMoney(x.sum)}</td></tr>`}).join('');$('invoice-details').scrollIntoView({behavior:'smooth',block:'start'})}
async function safeJson(r){const t=await r.text();if(!t)return{};try{return JSON.parse(t)}catch{return{success:false,message:t||`HTTP ${r.status}`}}}
function unresolvedSuppliers(){return documents.filter(d=>{const id=String(d.supplierId||'').trim();const name=String(d.supplierName||'').trim();return id&&(!name||name===id||name==='—')}).length}
async function load(){let binding,c;try{binding=window.SH_IikoContext?.getBinding?await window.SH_IikoContext.getBinding():null;c=binding?.connection||await connection()}catch(e){status(e.message,'error');return}const from=$('invoice-from').value,to=$('invoice-to').value;if(!from||!to){status('Укажите период','error');return}if(to<from){status('Дата «По» раньше даты «С»','error');return}savePeriod();const departmentIds=Array.isArray(binding?.departmentIds)?binding.departmentIds.map(String).filter(Boolean):[];const allowedDepartmentIds=Array.isArray(binding?.allDepartmentIds)?binding.allDepartmentIds.map(String).filter(Boolean):departmentIds;const chainScope={mode:String(binding?.identity?.mode||c?.connectionType||'RMS').toUpperCase(),allowedDepartmentIds,selectedDepartmentIds:departmentIds};const btn=$('invoice-load');btn.disabled=true;btn.textContent='Загрузка…';status('Получаем накладные и справочники из SH Server…','loading');try{const r=await (window.SH_IikoContext?.fetchWithTimeout||fetch)('/api/iiko/incoming-invoices',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...c,from,to,departmentIds,chainScope})},90000);const data=await safeJson(r);if(!r.ok||data.success===false)throw new Error(data.message||`HTTP ${r.status}`);documents=Array.isArray(data.documents)?data.documents:[];$('invoice-period').textContent=`${formatDate(from)} — ${formatDate(to)}`;render();if(documents.length){const unresolved=unresolvedSuppliers();const diag=data.referenceDiagnostics?Object.entries(data.referenceDiagnostics).map(([k,x])=>`${k}: ${x?.parsedCount??0}`).join(' · '):'';status(unresolved?`Готово · найдено ${documents.length} · не сопоставлено поставщиков ${unresolved}${diag?` · ${diag}`:''}`:`Готово · найдено ${documents.length} · справочники получены одним запросом`,'success')}else status('Накладные не найдены','error')}catch(e){documents=[];render();status(e?.message||'Ошибка загрузки','error')}finally{btn.disabled=false;btn.textContent='Показать накладные'}}
function clear(){documents=[];window.SHIncomingInvoices=window.SHIncomingInvoices||{};window.SHIncomingInvoices.selected=null;clearSavedPeriod();setDefaults();$('invoice-search').value='';$('invoice-period').textContent='';$('invoice-details').hidden=true;render();status('Готово к запросу')}
window.SHIncomingInvoices=window.SHIncomingInvoices||{};window.SHIncomingInvoices.reload=load;window.SHIncomingInvoices.getSelected=()=>window.SHIncomingInvoices.selected||null;
function init(){$('invoice-load').addEventListener('click',load);$('invoice-clear').addEventListener('click',clear);$('invoice-search').addEventListener('input',render);$('invoice-details-close').addEventListener('click',()=>$('invoice-details').hidden=true);restorePeriod();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();