(()=>{'use strict';
const $=id=>document.getElementById(id);
let products=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadSaleState(){try{const s=await window.SH_IikoContext.get(),c=s?.connection;if(!c?.ip||!c?.port||!c?.login||!c?.password)return;const r=await fetch('/api/iiko/nomenclature',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({action:'products.list',connection:c,params:{includeDeleted:true},payload:null})});const d=await r.json();if(!r.ok||d.success===false)return;const x=d.data;products=Array.isArray(x)?x:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:[];paint() }catch(e){console.warn('nomenclature-sale',e)}}
function key(p){return String(p?.id||'')+'|'+String(p?.num||'')+'|'+String(p?.code||'')}
function paint(){const body=$('products-body');if(!body)return;const table=body.closest('table');if(!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('[data-sale-head]')){const th=document.createElement('th');th.dataset.saleHead='1';th.textContent='В продаже';head.insertBefore(th,head.firstElementChild)}[...body.querySelectorAll('tr')].forEach(row=>{if(row.children.length<3)return;const name=row.children[0]?.textContent?.trim()||'';const num=row.children[2]?.textContent?.trim()||'';const code=row.children[3]?.textContent?.trim()||'';const p=products.find(x=>String(x.num||'')===num&&num!=='—')||products.find(x=>String(x.code||'')===code&&code!=='—')||products.find(x=>String(x.name||'').trim()===name);if(!row.querySelector('[data-sale-cell]')){const td=document.createElement('td');td.dataset.saleCell='1';td.className='sale-cell';row.insertBefore(td,row.firstElementChild)}const td=row.querySelector('[data-sale-cell]');const inSale=!!p?.defaultIncludedInMenu;td.innerHTML=inSale?'<span class="sale-check" title="В продаже">✓</span>':'<span class="sale-empty" title="Не в продаже">—</span>'})}
function boot(){let tries=0,ready=setInterval(()=>{if($('products-body')){clearInterval(ready);loadSaleState();new MutationObserver(()=>{clearTimeout(window.__nomSaleTimer);window.__nomSaleTimer=setTimeout(paint,30)}).observe($('products-body'),{childList:true})}else if(++tries>80)clearInterval(ready)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();