(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let groups=[],selectedId='__all',page=1,pageSize=25;
const $=id=>document.getElementById(id);
async function connection(){const s=await window.SH_IikoContext.get();const c=s?.connection;if(!c?.ip||!c?.port||!c?.login||!c?.password)throw Error('Нет сохранённого подключения iiko Server.');return c}
async function api(action,params={},payload=null){const c=await connection();const r=await fetch('/api/iiko/nomenclature',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({action,connection:c,params,payload})});const d=await r.json().catch(()=>({success:false,message:'Некорректный ответ'}));if(!r.ok||d.success===false)throw Error(d.message||`HTTP ${r.status}`);return d.data}
function arr(x){return Array.isArray(x)?x:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:[]}
function setup(){const tab=$('tab-products'),card=tab?.querySelector('.table-card');if(!tab||!card||tab.querySelector('.nom-browser'))return false;
 const browser=document.createElement('div');browser.className='nom-browser';
 const tree=document.createElement('aside');tree.className='nom-tree';tree.innerHTML='<div class="nom-tree-head"><strong>Структура групп</strong><span id="nom-tree-count"></span></div><div class="nom-tree-search"><span>⌕</span><input id="nom-tree-search-input" placeholder="Поиск группы…"></div><div id="nom-tree-body" class="nom-tree-body"></div>';
 const right=document.createElement('section');right.className='nom-items-pane';
 const head=document.createElement('div');head.className='nom-items-head';head.innerHTML='<div><div class="nom-items-title" id="nom-items-title">Элементы: все группы</div><div class="nom-breadcrumb" id="nom-breadcrumb">Все группы</div></div><div class="nom-items-meta" id="nom-items-meta"></div>';
 card.parentNode.insertBefore(browser,card);right.appendChild(head);right.appendChild(card);browser.appendChild(tree);browser.appendChild(right);
 $('nom-tree-search-input').addEventListener('input',renderTree);return true}
function childrenOf(id){return groups.filter(g=>String(g.parent||'')===String(id||''))}
function descendants(id){const out=new Set([String(id)]),walk=x=>childrenOf(x).forEach(g=>{const k=String(g.id);if(!out.has(k)){out.add(k);walk(k)}});walk(id);return out}
function renderTree(){const body=$('nom-tree-body');if(!body)return;const q=($('nom-tree-search-input')?.value||'').trim().toLowerCase();const visible=new Set();groups.forEach(g=>{if(!q||String(g.name||'').toLowerCase().includes(q)){visible.add(String(g.id));let p=g.parent;while(p){visible.add(String(p));const pg=groups.find(x=>String(x.id)===String(p));p=pg?.parent}}});
 const roots=groups.filter(g=>!g.parent&&!g.deleted);const total=groups.filter(g=>!g.deleted).length;$('nom-tree-count').textContent=total?`(${total})`:'';
 let html=`<button class="nom-tree-node root ${selectedId==='__all'?'selected':''}" data-group="__all"><span class="tree-chevron">⌄</span><span class="folder">▣</span><span class="tree-name">Все группы</span><span class="tree-count">${countFor(null)}</span></button>`;
 const draw=(g,level)=>{if(g.deleted|| (q&&!visible.has(String(g.id))))return '';const kids=childrenOf(g.id).filter(x=>!x.deleted);const open=level<1||selectedId===String(g.id)||descendants(selectedId).has(String(g.id));return `<div class="nom-tree-wrap"><button class="nom-tree-node ${selectedId===String(g.id)?'selected':''}" data-group="${esc(g.id)}" style="--level:${level}"><span class="tree-chevron">${kids.length?(open?'⌄':'›'):''}</span><span class="folder">▣</span><span class="tree-name">${esc(g.name)}</span><span class="tree-count">${countFor(g.id)}</span></button>${open?kids.map(x=>draw(x,level+1)).join(''):''}</div>`};
 html+=roots.map(g=>draw(g,0)).join('');body.innerHTML=html;body.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{selectedId=b.dataset.group;page=1;renderTree();filterRows()}));}
function countFor(id){const set=id===null?null:descendants(id);const rows=[...document.querySelectorAll('#products-body tr')];if(!rows.length)return 0;return rows.filter(r=>{const c=r.children?.[4]?.textContent?.trim();if(id===null)return !!r.querySelector('[data-edit-product],[data-delete-product],[data-restore-product]');return set.has(groupIdByName(c))}).length}
function groupIdByName(name){const g=groups.find(x=>String(x.name).trim()===String(name).trim());return g?String(g.id):'__none'}
function filterRows(){const tbody=$('products-body');if(!tbody)return;const rows=[...tbody.querySelectorAll('tr')].filter(r=>r.children.length>1);const set=selectedId==='__all'?null:descendants(selectedId);let filtered=rows.filter(r=>{if(!set)return true;return set.has(groupIdByName(r.children?.[4]?.textContent?.trim()))});
 const q=($('product-search')?.value||'').trim().toLowerCase(),typ=$('product-type')?.value||'';filtered=filtered.filter(r=>{const txt=r.textContent.toLowerCase();return (!q||txt.includes(q))&&(!typ||String(r.children?.[1]?.textContent||'')===typ)});
 rows.forEach(r=>r.style.display='none');const max=Math.max(1,Math.ceil(filtered.length/pageSize));if(page>max)page=max;filtered.slice((page-1)*pageSize,page*pageSize).forEach(r=>r.style.display='');
 const title=selectedId==='__all'?'Элементы: все группы':`Элементы: ${groups.find(g=>String(g.id)===selectedId)?.name||'группа'}`;$('nom-items-title').textContent=title;$('nom-breadcrumb').textContent=selectedId==='__all'?'Все группы':breadcrumb(selectedId);$('nom-items-meta').textContent=`Показано ${Math.min(filtered.length,(page-1)*pageSize+1)}–${Math.min(filtered.length,page*pageSize)} из ${filtered.length}`;
 renderPager(filtered.length)}
function breadcrumb(id){const out=[],seen=new Set();let g=groups.find(x=>String(x.id)===String(id));while(g&&!seen.has(String(g.id))){seen.add(String(g.id));out.unshift(g.name);g=groups.find(x=>String(x.id)===String(g.parent))}return ['Все группы',...out].join(' / ')}
function renderPager(total){let p=$('nom-pagination');if(!p){p=document.createElement('div');p.id='nom-pagination';p.className='nom-pagination';$('products-body').closest('.table-card').appendChild(p)}const pages=Math.max(1,Math.ceil(total/pageSize));let html=`<span>Показано ${(total?((page-1)*pageSize+1):0)}–${Math.min(page*pageSize,total)} из ${total}</span><div>${page>1?'<button data-pg="prev">‹</button>':''}`;for(let i=1;i<=pages&&i<=7;i++)html+=`<button class="${i===page?'active':''}" data-pg="${i}">${i}</button>`;if(pages>7)html+='<span>…</span>';if(page<pages)html+='<button data-pg="next">›</button>';html+='</div>';p.innerHTML=html;p.querySelectorAll('[data-pg]').forEach(b=>b.onclick=()=>{const v=b.dataset.pg;page=v==='prev'?page-1:v==='next'?page+1:Number(v);filterRows()})}
async function load(){try{groups=arr(await api('groups.list',{includeDeleted:true})).filter(x=>x?.id);setup();renderTree();filterRows();const ps=$('product-search'),pt=$('product-type');['input','change'].forEach(e=>{ps?.addEventListener(e,()=>{page=1;filterRows()});pt?.addEventListener(e,()=>{page=1;filterRows()})});}catch(e){console.warn('nomenclature-tree',e)}}
function boot(){let tries=0;const t=setInterval(()=>{if($('products-body')){clearInterval(t);load()}else if(++tries>60)clearInterval(t)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
