(()=>{'use strict';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let groups=[],selectedId='__all',page=1,pageSize=25;
async function conn(){const s=await window.SH_IikoContext.get(),c=s?.connection;if(!c?.ip||!c?.port||!c?.login||!c?.password)throw Error('Нет подключения iiko Server');return c}
async function api(action,params={}){const c=await conn(),r=await fetch('/api/iiko/nomenclature',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({action,connection:c,params,payload:null})}),d=await r.json().catch(()=>({success:false}));if(!r.ok||d.success===false)throw Error(d.message||`HTTP ${r.status}`);return d.data}
const activeRows=()=>[...($('products-body')?.querySelectorAll('tr')||[])].filter(r=>r.children.length>1);
const children=id=>groups.filter(g=>String(g.parent||'')===String(id||''));
const descendants=id=>{const out=new Set([String(id)]),walk=x=>children(x).forEach(g=>{const k=String(g.id);if(!out.has(k)){out.add(k);walk(k)}});walk(id);return out};
const idByName=name=>{const g=groups.find(x=>String(x.name||'').trim()===String(name||'').trim());return g?String(g.id):'__none'};
function productMatches(r){const q=($('product-search')?.value||'').trim().toLowerCase(),typ=$('product-type')?.value||'',txt=r.textContent.toLowerCase();return(!q||txt.includes(q))&&(!typ||String(r.children?.[1]?.textContent||'').trim()===typ)}
function groupCount(id){const set=id==='__all'?null:descendants(id);return activeRows().filter(r=>{if(!productMatches(r))return false;if(!set)return true;return set.has(idByName(r.children?.[4]?.textContent))}).length}
function matchingGroups(){const visible=new Set();groups.filter(g=>!g.deleted).forEach(g=>{if(groupCount(String(g.id))>0){visible.add(String(g.id));let p=g.parent;while(p){visible.add(String(p));const pg=groups.find(x=>String(x.id)===String(p));p=pg?.parent}}});return visible}
function breadcrumb(id){const a=[],seen=new Set();let g=groups.find(x=>String(x.id)===String(id));while(g&&!seen.has(String(g.id))){seen.add(String(g.id));a.unshift(g.name);g=groups.find(x=>String(x.id)===String(g.parent))}return['Все группы',...a].join(' / ')}
function setup(){const tab=$('tab-products'),card=tab?.querySelector('.table-card');if(!tab||!card||tab.querySelector('.nom-browser'))return;if(!card.parentNode)return;
 const browser=document.createElement('div');browser.className='nom-browser';const tree=document.createElement('aside');tree.className='nom-tree';tree.innerHTML='<div class="nom-tree-head"><strong>Структура групп</strong><span id="nom-tree-count"></span></div><div class="nom-tree-search"><span>⌕</span><input id="nom-tree-search-input" placeholder="Поиск группы…"></div><div id="nom-tree-body" class="nom-tree-body"></div>';
 const right=document.createElement('section');right.className='nom-items-pane';right.innerHTML='<div class="nom-items-head"><div><div class="nom-items-title" id="nom-items-title">Элементы: все группы</div><div class="nom-breadcrumb" id="nom-breadcrumb">Все группы</div></div><div class="nom-items-meta" id="nom-items-meta"></div></div>';
 card.parentNode.insertBefore(browser,card);right.appendChild(card);browser.append(tree,right);$('nom-tree-search-input').addEventListener('input',()=>{renderTree()})}
function renderTree(){const body=$('nom-tree-body');if(!body)return;const q=($('nom-tree-search-input')?.value||'').trim().toLowerCase(),valid=matchingGroups();const roots=groups.filter(g=>!g.parent&&!g.deleted&&valid.has(String(g.id)));$('nom-tree-count').textContent=`(${valid.size})`;
 let html=`<button class="nom-tree-node root ${selectedId==='__all'?'selected':''}" data-group="__all"><span class="tree-chevron">⌄</span><span class="folder">▣</span><span class="tree-name">Все группы</span><span class="tree-count">${groupCount('__all')}</span></button>`;
 const draw=(g,level)=>{const gid=String(g.id);if(g.deleted||!valid.has(gid))return'';if(q&&!String(g.name||'').toLowerCase().includes(q)&&!children(g.id).some(x=>valid.has(String(x.id))&&String(x.name||'').toLowerCase().includes(q)))return'';const kids=children(g.id).filter(x=>!x.deleted&&valid.has(String(x.id)));const open=q||level===0||selectedId===gid||descendants(selectedId).has(gid);return `<div class="nom-tree-wrap"><button class="nom-tree-node ${selectedId===gid?'selected':''}" data-group="${esc(gid)}" style="--level:${level}"><span class="tree-chevron">${kids.length?(open?'⌄':'›'):''}</span><span class="folder">▣</span><span class="tree-name">${esc(g.name)}</span><span class="tree-count">${groupCount(gid)}</span></button>${open?kids.map(x=>draw(x,level+1)).join(''):''}</div>`};
 html+=roots.map(g=>draw(g,0)).join('');body.innerHTML=html;body.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{selectedId=b.dataset.group;page=1;filterRows();renderTree()})}
function filterRows(){const rows=activeRows(),set=selectedId==='__all'?null:descendants(selectedId),matches=rows.filter(r=>productMatches(r)&&(!set||set.has(idByName(r.children?.[4]?.textContent))));rows.forEach(r=>r.style.display='none');matches.slice((page-1)*pageSize,page*pageSize).forEach(r=>r.style.display='');const total=matches.length,pages=Math.max(1,Math.ceil(total/pageSize));if(page>pages)page=pages;const shownStart=total?(page-1)*pageSize+1:0;$('nom-items-title').textContent=selectedId==='__all'?'Элементы: все группы':`Элементы: ${groups.find(g=>String(g.id)===selectedId)?.name||'группа'}`;$('nom-breadcrumb').textContent=selectedId==='__all'?'Все группы':breadcrumb(selectedId);$('nom-items-meta').textContent=`Показано ${shownStart}–${Math.min(page*pageSize,total)} из ${total}`;renderPager(total)}
function renderPager(total){let p=$('nom-pagination');if(!p){p=document.createElement('div');p.id='nom-pagination';p.className='nom-pagination';$('products-body').closest('.table-card').appendChild(p)}const pages=Math.max(1,Math.ceil(total/pageSize));let h=`<span>Показано ${total?((page-1)*pageSize+1):0}–${Math.min(page*pageSize,total)} из ${total}</span><div>`;if(page>1)h+='<button data-pg="prev">‹</button>';for(let i=1;i<=Math.min(pages,7);i++)h+=`<button class="${i===page?'active':''}" data-pg="${i}">${i}</button>`;if(page<pages)h+='<button data-pg="next">›</button>';p.innerHTML=h+'</div>';p.querySelectorAll('[data-pg]').forEach(b=>b.onclick=()=>{const v=b.dataset.pg;page=v==='prev'?page-1:v==='next'?page+1:Number(v);filterRows()})}
function observe(){const body=$('products-body');if(!body||body.dataset.nomTreeObserved)return;body.dataset.nomTreeObserved='1';let t=0;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{filterRows();renderTree()},60)}).observe(body,{childList:true})}
async function load(){try{groups=(Array.isArray(await api('groups.list',{includeDeleted:true}))?await api('groups.list',{includeDeleted:true}):[])}catch(e){try{const d=await api('groups.list',{includeDeleted:true});groups=Array.isArray(d)?d:(d?.items||d?.data||[])}catch(err){console.warn('nomenclature-tree',err);return}}setup();observe();renderTree();filterRows();['input','change'].forEach(ev=>{$('product-search')?.addEventListener(ev,()=>{page=1;filterRows();renderTree()});$('product-type')?.addEventListener(ev,()=>{page=1;filterRows();renderTree()})})}
function boot(){let n=0,t=setInterval(()=>{if($('products-body')){clearInterval(t);load()}else if(++n>80)clearInterval(t)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
