(() => {
  const actionSelect = document.getElementById("action-select");
  const resultSummary = document.getElementById("result-summary");
  const resultOutput = document.getElementById("result-output");
  const pluginSelect = document.getElementById("plugin-select");
  if (!actionSelect || !resultSummary || !resultOutput) return;

  const style = document.createElement("style");
  style.textContent = `
    .orders-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:14px}.order-stat{appearance:none;border:1px solid var(--line);border-radius:14px;background:var(--surface2);padding:13px 15px;text-align:left;color:inherit;cursor:pointer}.order-stat:hover,.order-stat.active{border-color:var(--pc-green);background:var(--pc-green-soft)}.order-stat span{display:block;font-size:9px;color:var(--muted);font-weight:800;text-transform:uppercase;letter-spacing:.07em}.order-stat strong{display:block;font-size:22px;margin-top:4px}.order-stat.open strong{color:var(--pc-green)}.order-stat.closed strong{color:var(--pc-red,#ff6b6b)}
    .orders-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:4px 0 10px}.orders-toolbar strong{font-size:12px}.orders-toolbar span{display:block;color:var(--muted);font-size:10px;margin-top:3px}.orders-live{display:flex!important;align-items:center;gap:6px;color:var(--pc-green)!important}.orders-live i{width:6px;height:6px;border-radius:50%;background:var(--pc-green);display:inline-block}.order-state{display:inline-flex;align-items:center;padding:5px 8px;border-radius:999px;font-size:9px;font-weight:850}.order-state.open{background:var(--pc-green-soft);color:var(--pc-green)}.order-state.closed{background:rgba(255,107,107,.1);color:var(--pc-red,#ff6b6b)}.order-state.unknown{background:var(--surface2);color:var(--muted)}.orders-table td{vertical-align:middle}.orders-table tr[hidden]{display:none}.orders-pay strong{color:var(--pc-green)}
    .order-click{cursor:pointer}.order-click:hover td{background:var(--pc-green-soft)}.order-open-link{color:var(--pc-green);font-weight:800;white-space:nowrap;font-size:10px;margin-top:3px}
    .order-modal{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:24px}.order-modal-card{width:min(1150px,96vw);max-height:92vh;overflow:auto;background:var(--surface,#101916);border:1px solid var(--line);border-radius:20px;box-shadow:0 25px 80px rgba(0,0,0,.45);padding:22px;color:inherit}.order-modal-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:18px}.order-modal-head h2{margin:0;font-size:20px}.order-modal-close{border:1px solid var(--line);background:var(--surface2);color:inherit;border-radius:10px;padding:8px 12px;cursor:pointer}.order-detail-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:20px}.order-detail-box{border:1px solid var(--line);background:var(--surface2);border-radius:12px;padding:11px}.order-detail-box span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;font-weight:800}.order-detail-box strong{display:block;margin-top:4px;font-size:12px;word-break:break-word}.order-modal-section{margin-top:18px}.order-modal-section h3{font-size:13px;margin:0 0 10px}.order-items{width:100%;border-collapse:collapse;font-size:11px}.order-items th,.order-items td{border-bottom:1px solid var(--line);padding:9px 7px;text-align:left}.order-items th{font-size:9px;color:var(--muted);text-transform:uppercase}.order-timeline{position:relative;margin-left:8px;padding-left:28px}.order-timeline:before{content:"";position:absolute;left:5px;top:5px;bottom:5px;width:2px;background:var(--line)}.timeline-item{position:relative;padding:0 0 18px}.timeline-item:before{content:"";position:absolute;left:-24px;top:15px;width:10px;height:10px;border-radius:50%;background:var(--pc-green);border:2px solid var(--surface,#101916)}.timeline-event{border:1px solid var(--line);border-radius:12px;padding:10px 12px;background:var(--surface2)}.timeline-event:hover{border-color:var(--pc-green)}.timeline-time{font-size:10px;color:var(--muted)}.timeline-title{font-size:12px;font-weight:850;margin-top:2px}.timeline-meta{font-size:10px;color:var(--muted);margin-top:4px}.timeline-data{margin-top:7px;padding:9px;border:1px solid var(--line);border-radius:9px;background:var(--surface2);font-size:10px;white-space:pre-wrap;word-break:break-word}.timeline-details{margin-top:8px}.timeline-details summary{cursor:pointer;color:var(--muted);font-size:10px}.order-loading{color:var(--muted);padding:20px;text-align:center}.order-empty{padding:16px;border:1px dashed var(--line);border-radius:12px;color:var(--muted)}
    @media(max-width:900px){.orders-stats{grid-template-columns:1fr 1fr 1fr}.order-detail-grid{grid-template-columns:1fr 1fr}}@media(max-width:500px){.orders-stats{grid-template-columns:1fr 1fr}.orders-table{min-width:980px}.order-modal{padding:8px}.order-detail-grid{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  const escapeHtml=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const text=value=>String(value??"").toLowerCase();
  function keyOf(row,names){const entries=Object.entries(row||{});for(const name of names){const hit=entries.find(([key])=>key.toLowerCase()===name.toLowerCase());if(hit&&hit[1]!==null&&hit[1]!==undefined&&hit[1]!=="")return hit[1];}return null;}
  function firstText(value){if(value===null||value===undefined||value==="")return null;if(typeof value==="string"||typeof value==="number"||typeof value==="boolean")return value;if(Array.isArray(value)){for(const item of value){const v=firstText(item);if(v!==null)return v;}return null;}if(typeof value==="object")for(const key of ["name","title","value","number","code","id"]){const v=firstText(value[key]);if(v!==null)return v;}return null;}
  const field=(row,names)=>firstText(keyOf(row,names));
  const orderNumber=(row,index)=>field(row,["OrderNum","orderNum","orderNumber","orderNo","number","num"])??index+1;
  function orderState(row){const s=text(field(row,["OrderStatus","status","state","orderState","statusName"]));if(/(closed|close|completed|complete|paid|закрыт|закрыто|оплачен|заверш|deleted|удал)/.test(s))return"closed";if(/(new|bill|open|opened|active|новый|пречек|открыт|открыто|актив)/.test(s))return"open";const closed=keyOf(row,["isClosed","closed","isClosedOrder"]);if(closed===true||text(closed)==="true")return"closed";if(closed===false||text(closed)==="false")return"open";if(keyOf(row,["CloseTime","closeTime","closedAt","closingTime","closeDate"]))return"closed";if(keyOf(row,["OpenTime","openTime","openedAt","openingTime","openDate"]))return"open";return"unknown";}
  function paymentText(row){const direct=field(row,["paymentType","paymentTypeName","paymentMethod","paymentName","payType","payTypeName"]);if(direct)return direct;const payments=keyOf(row,["Payments","payments","payment"]);if(!Array.isArray(payments))return null;const result=[];for(const p of payments){if(!p||typeof p!=="object")continue;const name=firstText(p.name??p.Name);const type=text(p.type??p.Type);let value=name;if(!value)value=/cash|налич/.test(type)?"Наличные":/card|карта|банков/.test(type)?"Карта":firstText(p.value??p.Value);if(value&&!result.includes(String(value)))result.push(String(value));}return result.length?result.join(", "):null;}
  function formatDate(value){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString("ru-RU");}
  function collectArrays(value,out=[],depth=0){if(depth>10||value==null)return out;if(Array.isArray(value)){const objects=value.filter(x=>x&&typeof x==="object"&&!Array.isArray(x));if(objects.length)out.push(objects);objects.forEach(x=>collectArrays(x,out,depth+1));return out;}if(typeof value!=="object")return out;Object.values(value).forEach(x=>collectArrays(x,out,depth+1));return out;}
  function findOrdersDetails(value,depth=0){if(!value||typeof value!=="object"||depth>10)return null;if(Array.isArray(value))return null;for(const [key,child] of Object.entries(value)){if(/^orders?details?$/i.test(key)&&Array.isArray(child)&&child.length)return child.filter(Boolean);if(child&&typeof child==="object"){const found=findOrdersDetails(child,depth+1);if(found?.length)return found;}}return null;}
  function orderScore(rows){const keys=["OrderNum","OrderStatus","Tables","Floor","Waiter","Cashier","OpenTime","BillTime","CloseTime","Revenue","Payments","Items"];return rows.reduce((s,row)=>s+keys.filter(k=>Object.keys(row).some(x=>x.toLowerCase()===k.toLowerCase())).length,0);}
  function findRows(value){const exact=findOrdersDetails(value);if(exact)return exact;const arrays=collectArrays(value);if(!arrays.length)return null;arrays.sort((a,b)=>orderScore(b)-orderScore(a)||b.length-a.length);return arrays[0];}

  function renderOrderRows(rows){return rows.slice(0,200).map((row,index)=>{const state=orderState(row),number=orderNumber(row,index),tables=field(row,["Tables","orderTables","table","tables","tableName"]),floor=field(row,["Floor","floor","floorName","orderFloor","restaurantSection"]),waiter=field(row,["Waiter","waiter","waiterName","orderWaiter","employee","employeeName","waiterFullName"]),cashier=field(row,["Cashier","cashier","cashierName","orderCashier","cashierFullName"]),amount=field(row,["Revenue","orderExpectedRevenue","revenue","sum","total","amount","orderSum"]),opened=field(row,["OpenTime","orderOpenDate","openTime","openedAt","openingTime","createdAt"]),bill=field(row,["BillTime","orderBillTime","billTime","precheckTime","precheckAt"]),closed=field(row,["CloseTime","orderCloseTime","closeTime","closedAt","closingTime","closedDate"]),payment=paymentText(row),status=state==="closed"?"Закрыт":state==="open"?"Открыт":"Не определён";return `<tr class="order-click" data-order-number="${escapeHtml(number)}" data-order-index="${index}" data-order-state="${state}" title="Открыть историю заказа"><td><strong>#${escapeHtml(number)}</strong><div class="order-open-link">Открыть ↗</div></td><td><span class="order-state ${state}">${status}</span></td><td>${escapeHtml(tables??"—")}</td><td>${escapeHtml(floor??"—")}</td><td>${escapeHtml(waiter??"—")}</td><td>${escapeHtml(cashier??"—")}</td><td>${escapeHtml(amount??"—")}</td><td>${escapeHtml(opened??"—")}</td><td>${escapeHtml(bill??"—")}</td><td>${escapeHtml(closed??"—")}</td><td class="orders-pay">${payment?`<strong>${escapeHtml(payment)}</strong>`:"—"}</td></tr>`;}).join("");}

  function renderOrders(rows){const states=rows.map(orderState),open=states.filter(s=>s==="open").length,closed=states.filter(s=>s==="closed").length,unknown=states.filter(s=>s==="unknown").length,payments=rows.map(paymentText).filter(Boolean).map(text),cash=payments.filter(s=>/(cash|налич|касса)/.test(s)).length,card=payments.filter(s=>/(card|банков|карта|terminal|терминал)/.test(s)).length;resultSummary.innerHTML=`<div class="orders-dashboard"><div class="orders-stats"><button type="button" class="order-stat active" data-order-filter="all"><span>Все заказы</span><strong>${rows.length}</strong></button><button type="button" class="order-stat open" data-order-filter="open"><span>Открытые</span><strong>${open}</strong></button><button type="button" class="order-stat closed" data-order-filter="closed"><span>Закрытые</span><strong>${closed}</strong></button>${unknown?`<button type="button" class="order-stat unknown" data-order-filter="unknown"><span>Без статуса</span><strong>${unknown}</strong></button>`:""}<button type="button" class="order-stat"><span>Оплата</span><strong>${cash+card?`${cash}/${card}`:"—"}</strong></button></div><div class="orders-toolbar"><div><strong>Заказы текущей смены</strong><span>${rows.length} записей · оплата: ${cash} наличные / ${card} карта</span></div><span class="orders-live"><i></i> обновляется автоматически</span></div><div class="data-table-wrap orders-table-wrap"><table class="data-table orders-table"><thead><tr><th>Заказ</th><th>Статус</th><th>Стол</th><th>Зал</th><th>Официант</th><th>Кассир</th><th>Сумма</th><th>Открыт</th><th>Пречек</th><th>Закрыт</th><th>Оплата</th></tr></thead><tbody id="orders-table-body">${renderOrderRows(rows)}</tbody></table></div>${rows.length>200?`<div class="table-note">Показаны первые 200 заказов.</div>`:""}</div>`;resultSummary.querySelectorAll("[data-order-filter]").forEach(button=>button.addEventListener("click",()=>{resultSummary.querySelectorAll("[data-order-filter]").forEach(x=>x.classList.remove("active"));button.classList.add("active");const filter=button.dataset.orderFilter;resultSummary.querySelectorAll("#orders-table-body tr").forEach(row=>row.hidden=filter!=="all"&&row.dataset.orderState!==filter);}));resultSummary.querySelectorAll(".order-click").forEach(row=>row.addEventListener("click",()=>{const index=Number(row.dataset.orderIndex);const number=row.dataset.orderNumber;if(rows[index])openOrderHistory(number,rows[index]);}));}

  const eventMap={newOrder:"🟢 Заказ открыт",deletionOfNotPrintedItem:"🗑️ Удалено нераспечатанное блюдо",deletionOfPrintedItem:"🗑️ Удалено распечатанное блюдо",addingDiscount:"🏷️ Добавлена скидка",removingDiscount:"🏷️ Удалена скидка",orderGuestBill:"🧾 Пречек сформирован",cancellationOfGuestBill:"↩️ Пречек отменён",voidReceipt:"↩️ Чек аннулирован",deletingAnOrder:"🗑️ Заказ удалён",closingOrder:"🔒 Заказ закрыт",orderTableHasBeenChanged:"🪑 Изменён стол",ordersWaiterHasChanged:"👤 Изменён официант",addingSurcharge:"➕ Добавлена наценка",removingSurcharge:"➖ Удалена наценка",printer:"🖨️ Печать",cashRegisterStart:"⚡ Касса запущена",cashRegisterShutDown:"⏹️ Касса остановлена",severalOrderShifts:"⚠️ Заказ пересёк смену",orderAmountHasReachedMaximum:"⚠️ Достигнута максимальная сумма",deleteAnEmptyOrder:"🗑️ Пустой заказ удалён",changeItemsAmountOnStopList:"📦 Изменено количество в стоп-листе",removeFromStopList:"📦 Товар убран из стоп-листа",deliveryTimeEditing:"🚚 Изменено время доставки",deliveryCancellationApplyingDiscountAndPayment:"🚚 Отмена доставки / скидка / оплата",cancellationForClosedDelivery:"🚚 Отмена закрытой доставки",newBanquetOrReservation:"📅 Создан банкет / резерв",reserveIsCancelled:"📅 Резерв отменён"};
  function eventTitle(type){return eventMap[type]||`🔹 ${type||"Событие заказа"}`;}
  function eventTime(event){return event?.data?.updateTime||event?.data?.openTime||event?.data?.billTime||event?.data?.closeTime||event?.data?.time||event?.receivedAt||event?.lastEventAt||null;}
  function eventActor(data){return field(data,["user","userName","employee","employeeName","employeeFullName","waiter","waiterName","cashier","cashierName"]);}
  function eventDescription(data){const parts=[],actor=eventActor(data),item=field(data,["item","itemName","product","productName","dishName","name"]),qty=field(data,["amount","quantity","count","itemsAmount"]),discount=field(data,["discount","discountPercent","discountSum","discountAmount"]),sum=field(data,["revenue","sum","amountSum","resultSum","orderSum"]),table=field(data,["table","tables","tableName","orderTables"]),floor=field(data,["floor","floorName","restaurantSection"]),reason=field(data,["reason","comment","reasonName"]),payment=field(data,["payment","paymentType","paymentTypeName","paymentMethod","paymentName"]);if(actor)parts.push(`Сотрудник: ${firstText(actor)}`);if(item)parts.push(`Блюдо: ${firstText(item)}`);if(qty!==null)parts.push(`Количество: ${firstText(qty)}`);if(discount!==null)parts.push(`Скидка: ${firstText(discount)}`);if(sum!==null)parts.push(`Сумма: ${firstText(sum)}`);if(table!==null)parts.push(`Стол: ${firstText(table)}`);if(floor!==null)parts.push(`Зал: ${firstText(floor)}`);if(payment!==null)parts.push(`Оплата: ${firstText(payment)}`);if(reason!==null)parts.push(`Причина: ${firstText(reason)}`);return parts.join(" · ");}
  function compactData(data){if(!data||typeof data!=="object")return data;const important=["orderNum","number","tables","floor","waiter","cashier","revenue","item","itemName","product","productName","dishName","amount","quantity","discount","discountPercent","discountSum","discountAmount","payment","payments","paymentType","paymentTypeName","reason","comment","updateTime","openTime","billTime","closeTime"];const out={};for(const [key,value] of Object.entries(data))if(important.some(k=>k.toLowerCase()===key.toLowerCase()))out[key]=value;return Object.keys(out).length?out:data;}

  function selectedPluginQuery(){const value=pluginSelect?.value||"";const option=pluginSelect?.selectedOptions?.[0];const pluginId=option?.dataset?.pluginId||option?.getAttribute("data-plugin-id")||"";return {value,pluginId};}
  async function openOrderHistory(number,order){const modal=document.createElement("div");modal.className="order-modal";modal.innerHTML=`<div class="order-modal-card"><div class="order-modal-head"><div><div class="panel-muted">ДЕТАЛИ ЗАКАЗА</div><h2>История заказа #${escapeHtml(number)}</h2><div class="timeline-meta">Полный журнал действий, полученный от плагина</div></div><button class="order-modal-close" type="button">Закрыть</button></div><div class="order-detail-grid"><div class="order-detail-box"><span>Стол</span><strong>${escapeHtml(field(order,["Tables","orderTables","table","tables"])??"—")}</strong></div><div class="order-detail-box"><span>Зал</span><strong>${escapeHtml(field(order,["Floor","floor","floorName","restaurantSection"])??"—")}</strong></div><div class="order-detail-box"><span>Официант</span><strong>${escapeHtml(field(order,["Waiter","waiter","waiterName","employeeName"])??"—")}</strong></div><div class="order-detail-box"><span>Кассир</span><strong>${escapeHtml(field(order,["Cashier","cashier","cashierName","employeeName"])??"—")}</strong></div><div class="order-detail-box"><span>Сумма</span><strong>${escapeHtml(field(order,["Revenue","orderExpectedRevenue","revenue","sum","total"])??"—")}</strong></div><div class="order-detail-box"><span>Открыт</span><strong>${escapeHtml(formatDate(field(order,["OpenTime","openTime","orderOpenDate"])))}</strong></div><div class="order-detail-box"><span>Пречек</span><strong>${escapeHtml(formatDate(field(order,["BillTime","billTime","orderBillTime"])))}</strong></div><div class="order-detail-box"><span>Закрыт</span><strong>${escapeHtml(formatDate(field(order,["CloseTime","closeTime","orderCloseTime"])))}</strong></div></div><div class="order-modal-section"><h3>Состав заказа</h3><div id="order-items-slot"></div></div><div class="order-modal-section"><h3>История событий</h3><div id="order-history-slot" class="order-loading">Загружаем историю событий…</div></div></div>`;document.body.appendChild(modal);renderItems(order,modal.querySelector("#order-items-slot"));const close=()=>modal.remove();modal.querySelector(".order-modal-close").addEventListener("click",close);modal.addEventListener("click",e=>{if(e.target===modal)close();});
    try{const {value,pluginId}=selectedPluginQuery();const qs=new URLSearchParams({orderNum:String(number)});if(pluginId)qs.set("pluginId",pluginId);else if(value)qs.set("socketId",value);const response=await fetch(`/api/plugin/order-history?${qs.toString()}`,{cache:"no-store"});const json=await response.json();if(!response.ok||!json.success)throw new Error(json.error||`HTTP ${response.status}`);const history=Array.isArray(json.history)?json.history:[];const slot=modal.querySelector("#order-history-slot");if(!history.length){slot.innerHTML=`<div class="order-empty">Для этого заказа пока нет сохранённых событий. Новые действия будут появляться здесь автоматически.</div>`;return;}history.sort((a,b)=>new Date(eventTime(a)||0)-new Date(eventTime(b)||0));slot.className="order-timeline";slot.innerHTML=history.map(event=>{const data=event.data||{},desc=eventDescription(data),details=compactData(data);return `<div class="timeline-item"><div class="timeline-event"><div class="timeline-time">${escapeHtml(formatDate(eventTime(event)))}</div><div class="timeline-title">${escapeHtml(eventTitle(event.pluginEventType))}</div>${desc?`<div class="timeline-meta">${escapeHtml(desc)}</div>`:""}<details class="timeline-details"><summary>Показать данные события</summary><div class="timeline-data">${escapeHtml(JSON.stringify(details,null,2))}</div></details></div></div>`;}).join("");}
    catch(error){modal.querySelector("#order-history-slot").innerHTML=`<div class="order-empty">Не удалось загрузить историю: ${escapeHtml(error.message)}</div>`;}
  }

  function findItems(order){const preferred=["items","orderItems","itemsDetails","products","orderDetailsItems"];for(const key of preferred)if(Array.isArray(order?.[key])&&order[key].length)return order[key];const arrays=collectArrays(order).filter(a=>a.length&&a.some(x=>field(x,["Name","name","ProductName","productName"])!==null&&(keyOf(x,["Amount","amount","Price","price","Status","status"])!==null)));arrays.sort((a,b)=>b.length-a.length);return arrays[0]||[];}
  function renderItems(order,target){const items=findItems(order);if(!target)return;if(!items.length){target.innerHTML=`<div class="order-empty">Состав заказа в ответе плагина не найден.</div>`;return;}target.innerHTML=`<table class="order-items"><thead><tr><th>Позиция</th><th>Кол-во</th><th>Цена</th><th>Сумма</th><th>Статус</th><th>Печать</th><th>Готово</th><th>Подача</th></tr></thead><tbody>${items.slice(0,300).map(item=>`<tr><td>${escapeHtml(field(item,["Name","name","ProductName","productName"])??"—")}</td><td>${escapeHtml(field(item,["Amount","amount","Quantity","quantity"])??"—")}</td><td>${escapeHtml(field(item,["Price","price"])??"—")}</td><td>${escapeHtml(field(item,["ResultSum","resultSum","Sum","sum"])??"—")}</td><td>${escapeHtml(field(item,["Status","status"])??"—")}</td><td>${escapeHtml(formatDate(field(item,["PrintTime","printTime"])))}</td><td>${escapeHtml(formatDate(field(item,["CookingFinishTime","cookingFinishTime"])))}</td><td>${escapeHtml(formatDate(field(item,["ServeTime","serveTime"])))}</td></tr>`).join("")}</tbody></table>`;}

  function tryRenderOrders(){if(actionSelect.value!=="get_orders")return;try{const response=JSON.parse(resultOutput.textContent||"{}");if(!response.success)return;let data=response.data;if(typeof data==="string"){try{data=JSON.parse(data);}catch(_){}}const rows=findRows(data);if(rows?.length)renderOrders(rows);}catch(_){} }
  const observer=new MutationObserver(tryRenderOrders);observer.observe(resultOutput,{childList:true,characterData:true,subtree:true});actionSelect.addEventListener("change",()=>setTimeout(tryRenderOrders,250));setInterval(tryRenderOrders,1000);
})();