(()=>{
const $=id=>document.getElementById(id),key='iikoConnection';let last=null,tree=[];
function conn(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function pad(n){return String(n).padStart(2,'0')}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function initDates(){const n=new Date(),f=new Date(n.getFullYear(),n.getMonth(),1);$('from').value=iso(f);$('to').value=iso(n)}
function setPeriod(v){const n=new Date(),t=new Date(n);if(v==='month'){t.setDate(1);$('from').value=iso(t);$('to').value=iso(n)}else if(v==='prev'){const f=new Date(n.getFullYear(),n.getMonth()-1,1),e=new Date(n.getFullYear(),n.getMonth(),0);$('from').value=iso(f);$('to').value=iso(e)}else if(v==='7'||v==='30'){t.setDate(t.getDate()-Number(v)+1);$('from').value=iso(t);$('to').value=iso(n)}}
function money(v){return Number(v||0).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})}
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function render(rows,rev){const tb=$('pnl-table').querySelector('tbody');tb.innerHTML='';const totalRev=Number(rev||0);rows.forEach(r=>{const tr=document.createElement('tr');tr.className=(r.kind||'')+' '+(Number(r.value)<0?'negative':'')+(r.revenueCategory?' revenue-category':'');const pct=totalRev?Number(r.value)/totalRev*100:0;const categoryPct=r.revenueCategory&&Number.isFinite(Number(r.share))?Number(r.share):pct;tr.innerHTML=`<td>${r.level?'<span class="toggle">'+(r.open?'⌄':'›')+'</span>':''}${esc(r.name)}</td><td>${money(r.value)}</td><td class="pct-col">${$('pct').checked?(categoryPct.toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1})+' %'):'—'}</td>`;if(r.level)tr.querySelector('.toggle').onclick=()=>{r.open=!r.open;render(rows,rev)};tb.appendChild(tr)})}
function renderCategorySummary(categories,rev){const host=$('revenue-category-summary');if(!host)return;const items=(categories||[]).slice().sort((a,b)=>Number(b.share)-Number(a.share));if(!items.length){host.innerHTML='';return}host.innerHTML=`<div class="revenue-category-head"><div><strong>Структура выручки по категориям</strong><span>Только категории блюд · без детализации по блюдам</span></div><b>${money(rev)}</b></div><div class="revenue-category-list">${items.map(x=>`<div class="revenue-category-row"><div class="revenue-category-name"><span>${esc(x.name)}</span><div class="revenue-category-bar"><i style="width:${Math.max(0,Math.min(100,Number(x.share)||0))}%"></i></div></div><strong>${money(x.value)}</strong><b>${Number(x.share||0).toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1})}%</b></div>`).join('')}</div><div class="revenue-category-total"><span>Итого</span><strong>${money(rev)}</strong><b>100,0%</b></div>`}
async function load(){const c=conn();if(!c){$('pnl-status').textContent='Нет подключения iiko';$('message').textContent='Не найдены сохранённые данные подключения iiko.';return}const from=$('from').value,to=$('to').value;if(!from||!to)return;$('load').disabled=true;$('pnl-status').textContent='Загрузка…';$('message').style.display='block';$('message').textContent='Получаем P&L и структуру выручки по категориям из iiko OLAP…';try{const r=await fetch('/api/iiko/pnl',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...c,from,to,byDate:$('byDate').checked,byConcept:$('byConcept').checked,allocate:$('allocate').checked})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||'Ошибка P&L');last=j;$('source-note').textContent=j.sourceNote||'iiko Server / OLAP';$('pnl-status').textContent=`Данные: ${from} — ${to}`;tree=j.rows||[];render(tree,j.revenue||0);renderCategorySummary(j.revenueCategories||[],j.revenue||0);$('message').style.display='none';$('excel').disabled=false;const all=[...(j.salesFields||[]).map(x=>({s:'SALES',x})),...(j.transactionFields||[]).map(x=>({s:'TRANSACTIONS',x}))];$('field-list').innerHTML=all.map(o=>`<div class="field-chip"><b>${esc(o.s)}</b> · ${esc(o.x.name)} — ${esc(o.x.title)}</div>`).join('')||'<span>Поля не получены</span>'}catch(e){$('pnl-status').textContent='Ошибка';$('message').style.display='block';$('message').textContent=e.message;$('excel').disabled=true}finally{$('load').disabled=false}}
function excelBorder(){return{top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}}}
function excelFill(color){return{type:'pattern',pattern:'solid',fgColor:{argb:color}}}
function excelFont(size,bold,color){return{name:'Calibri',size:size||11,bold:!!bold,color:{argb:color||'FF1F2937'}}}
function styleCell(cell,opts={}){cell.font=opts.font||excelFont(11,!!opts.bold,opts.color);cell.alignment=opts.alignment||{vertical:'middle'};if(opts.fill)cell.fill=excelFill(opts.fill);if(opts.border!==false)cell.border=excelBorder();if(opts.numFmt)cell.numFmt=opts.numFmt}
function addExcelRow(ws,r,rev){const row=ws.addRow([r.name,Number(r.value)||0,rev?Number(r.value)/rev:0]);const kind=r.kind||'';row.getCell(1).alignment={vertical:'middle',indent:r.level?0:1};row.getCell(2).alignment={vertical:'middle',horizontal:'right'};row.getCell(3).alignment={vertical:'middle',horizontal:'right'};row.getCell(2).numFmt='#,##0.00;[Red]-#,##0.00';row.getCell(3).numFmt='0.0%';for(let i=1;i<=3;i++)row.getCell(i).border=excelBorder();if(kind.includes('section')){row.font=excelFont(11,true,'FF0F172A');row.fill=excelFill('FFE8EEF7');row.height=23}else if(kind.includes('profit')){row.font=excelFont(12,true,'FF0F172A');row.fill=excelFill('FFDDEFE2');row.height=25}else if(kind.includes('total')){row.font=excelFont(11,true,'FF0F172A');row.fill=excelFill('FFF1F5F9');row.height=22}else{row.font=excelFont(11,false,'FF334155');row.height=20}if(Number(r.value)<0)row.getCell(2).font=excelFont(11,kind.includes('total')||kind.includes('section'),'FFC62828');return row}
async function exportExcel(){if(!last){alert('Сначала загрузите отчёт.');return}if(!window.ExcelJS){alert('Excel-модуль ещё не загрузился. Попробуйте обновить страницу.');return}const btn=$('excel');btn.disabled=true;btn.textContent='Создание…';try{const wb=new ExcelJS.Workbook();wb.creator='Smart Horeca Control';wb.company='Smart Horeca Control';wb.subject='Отчёт о прибылях и убытках';wb.title='P&L';wb.created=new Date();
const ws=wb.addWorksheet('P&L',{views:[{showGridLines:false}]});ws.pageSetup={orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0};ws.pageMargins={left:0.3,right:0.3,top:0.5,bottom:0.5,header:0.2,footer:0.2};ws.freezePanes={xSplit:0,ySplit:5};ws.mergeCells('A1:C1');const title=ws.getCell('A1');title.value='ОТЧЁТ О ПРИБЫЛЯХ И УБЫТКАХ';styleCell(title,{font:excelFont(16,true,'FFFFFFFF'),fill:'FF166534',alignment:{vertical:'middle',horizontal:'left'}});ws.getRow(1).height=30;ws.mergeCells('A2:C2');const period=ws.getCell('A2');period.value=`Период: ${$('from').value} — ${$('to').value}`;styleCell(period,{font:excelFont(11,false,'FF475569'),fill:'FFF8FAFC'});ws.getRow(2).height=22;ws.mergeCells('A3:C3');const source=ws.getCell('A3');source.value='Источник: iiko Server · без кассовых смен';styleCell(source,{font:excelFont(10,false,'FF64748B'),fill:'FFF8FAFC'});ws.getRow(3).height=20;ws.addRow([]);const head=ws.addRow(['Статья','Сумма','% к выручке']);head.height=23;for(let i=1;i<=3;i++)styleCell(head.getCell(i),{font:excelFont(11,true,'FFFFFFFF'),fill:'FF334155',alignment:{vertical:'middle',horizontal:i===1?'left':'center'}});const rev=Number(last.revenue||0);(last.rows||[]).forEach(r=>addExcelRow(ws,r,rev));
const cats=(last.revenueCategories||[]).slice().sort((a,b)=>Number(b.share)-Number(a.share));
if(cats.length){
 const sep=ws.addRow([]);sep.height=8;
 ws.mergeCells(`A${sep.number+1}:C${sep.number+1}`);const sh=ws.getCell(`A${sep.number+1}`);sh.value='СТРУКТУРА ВЫРУЧКИ ПО КАТЕГОРИЯМ';styleCell(sh,{font:excelFont(13,true,'FFFFFFFF'),fill:'FF166534',alignment:{vertical:'middle',horizontal:'left'}});ws.getRow(sep.number+1).height=26;
 const sub=ws.addRow(['Категория','Выручка','Доля']);sub.height=22;for(let i=1;i<=3;i++)styleCell(sub.getCell(i),{font:excelFont(11,true,'FFFFFFFF'),fill:'FF334155',alignment:{vertical:'middle',horizontal:i===1?'left':'center'}});
 cats.forEach(x=>{const row=ws.addRow([x.name,Number(x.value)||0,Number(x.share||0)/100]);row.getCell(2).numFmt='#,##0.00;[Red]-#,##0.00';row.getCell(3).numFmt='0.0%';for(let i=1;i<=3;i++)row.getCell(i).border=excelBorder();row.getCell(1).font=excelFont(11,false,'FF334155');row.getCell(2).alignment={vertical:'middle',horizontal:'right'};row.getCell(3).alignment={vertical:'middle',horizontal:'right'};row.height=20});
 const total=ws.addRow(['ИТОГО',rev,1]);for(let i=1;i<=3;i++){total.getCell(i).font=excelFont(11,true,'FF0F172A');total.getCell(i).fill=excelFill('FFF1F5F9');total.getCell(i).border=excelBorder()}total.getCell(2).numFmt='#,##0.00';total.getCell(3).numFmt='0.0%';total.height=22;
}
ws.getColumn(1).width=38;ws.getColumn(2).width=17;ws.getColumn(3).width=17;
const buf=await wb.xlsx.writeBuffer();const blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`pnl-${$('from').value}-${$('to').value}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){console.error('Excel export error',e);alert('Не удалось сформировать Excel: '+(e.message||e))}finally{btn.disabled=false;btn.textContent='Excel'}}
function bind(){if(!$('load'))return;$('period').onchange=e=>setPeriod(e.target.value);$('load').onclick=load;$('expand').onclick=()=>{tree.forEach(x=>{if(x.level)x.open=true});render(tree,last?.revenue||0)};$('collapse').onclick=()=>{tree.forEach(x=>{if(x.level)x.open=false});render(tree,last?.revenue||0)};$('pct').onchange=()=>render(tree,last?.revenue||0);$('excel').onclick=exportExcel;initDates()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind()
})();