const KEY='horeca_qr_menu_v1';
const DEFAULT_DESIGN={name:'Мой ресторан',tagline:'QR Menu',about:'Добро пожаловать! Мы создаём вкусные блюда и приятные моменты для наших гостей.',accent:'#D4AF37',text:'#17211c',bg:'#f4f6f5',surface:'#ffffff',theme:'light',font:'Inter',radius:'16px',hero:'',logo:'',phone:'',address:'',hours:'',social:'',wifi:'',showPrices:true,showDescriptions:true,showComposition:true,showAbout:true,showContacts:true};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{categories:[{id:'main',name:'Основные блюда',source:'local'},{id:'salads',name:'Салаты',source:'local'},{id:'pizza',name:'Пицца',source:'local'},{id:'drinks',name:'Напитки',source:'local'},{id:'desserts',name:'Десерты',source:'local'}],active:'main',dishes:[{id:1,cat:'main',name:'Шашлык из телятины',price:16,desc:'Телятина, лук, зелень',source:'local'},{id:2,cat:'main',name:'Паста Карбонара',price:13,desc:'Паста, сливочный соус, сыр',source:'local'},{id:3,cat:'salads',name:'Цезарь с курицей',price:13,desc:'Курица, салат, соус Цезарь',source:'local'},{id:4,cat:'pizza',name:'Пицца Маргарита',price:12,desc:'Томат, моцарелла, базилик',source:'local'},{id:5,cat:'drinks',name:'Лимонад',price:9,desc:'Лимон, мята, вода',source:'local'}]};
state.design={...DEFAULT_DESIGN,...(state.design||{})};state.categories=(state.categories||[]).map(c=>({...c,source:c.source||'local'}));state.dishes=(state.dishes||[]).map(d=>({...d,source:d.source||'local'}));
let editId=null,sortAsc=true;
function save(){localStorage.setItem(KEY,JSON.stringify(state));const s=document.getElementById('saveStatus');if(s)s.textContent='● Изменения сохранены';}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function renderCats(){const el=document.getElementById('categories');el.innerHTML=state.categories.map(c=>`<div class="cat ${c.id===state.active?'active':''}" data-cat="${esc(c.id)}"><span>☷ &nbsp;${esc(c.name)}${c.source==='iiko'?'<span class="source-badge">iiko</span>':''}</span><span>${state.dishes.filter(d=>d.cat===c.id).length}</span></div>`).join('');el.querySelectorAll('.cat').forEach(x=>x.onclick=()=>{state.active=x.dataset.cat;save();render();});const fCat=document.getElementById('fCat');if(fCat)fCat.innerHTML=state.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');}
function renderItems(){const q=(document.getElementById('searchDish')?.value||'').toLowerCase();let ds=state.dishes.filter(d=>d.cat===state.active&&(d.name+' '+(d.desc||'')).toLowerCase().includes(q));ds.sort((a,b)=>sortAsc?a.name.localeCompare(b.name):b.name.localeCompare(a.name));const el=document.getElementById('items');el.innerHTML=ds.length?ds.map(d=>`<div class="item" draggable="true" data-id="${esc(d.id)}"><div class="photo">${d.photo?`<img src="${d.photo}">`:'🍽'}</div><div><h4>${esc(d.name)}${d.source==='iiko'?'<span class="source-badge">iiko</span>':''}</h4><p>${esc(d.desc||'Состав не указан')}</p><div class="item-actions"><button class="mini edit" data-id="${esc(d.id)}">Изменить</button><button class="mini photoBtn" data-id="${esc(d.id)}">Фото</button><button class="mini del" data-id="${esc(d.id)}">Удалить</button></div></div><div class="price">${Number(d.price).toFixed(2)} ₼</div></div>`).join(''):'<div class="empty">В этой категории пока нет блюд.<br>Нажмите «Добавить блюдо».</div>';el.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openEdit(b.dataset.id));el.querySelectorAll('.del').forEach(b=>b.onclick=()=>{const d=state.dishes.find(x=>String(x.id)===String(b.dataset.id));if(d&&d.source==='iiko'){alert('Это блюдо является зеркалом iiko. Измените его в iiko и выполните синхронизацию.');return;}state.dishes=state.dishes.filter(d=>String(d.id)!==String(b.dataset.id));save();render();});el.querySelectorAll('.photoBtn').forEach(b=>b.onclick=()=>{editId=b.dataset.id;document.getElementById('fPhoto').click();});}
function renderPreview(){const d=state.design;const body=document.getElementById('previewBody');body.innerHTML=state.categories.map(c=>{const ds=state.dishes.filter(x=>x.cat===c.id);if(!ds.length)return'';return`<div class="p-cat">${esc(c.name)}</div>`+ds.map(x=>`<div class="p-item"><div class="p-photo">${x.photo?`<img src="${x.photo}">`:'🍽'}</div><div><b>${esc(x.name)}</b>${d.showDescriptions&&x.desc?`<span>${esc(x.desc)}</span>`:''}${d.showComposition&&x.composition&&x.composition!==x.desc?`<span>Состав: ${esc(x.composition)}</span>`:''}</div>${d.showPrices?`<div class="p-price">${Number(x.price).toFixed(2)} ₼</div>`:''}</div>`}).join('')}).join('');document.getElementById('previewName').textContent=d.name||'Мой ресторан';document.getElementById('previewTagline').textContent=d.tagline||'QR Menu';document.getElementById('phoneTop').style.background=d.theme==='dark'?'#111':d.accent;document.getElementById('phoneScreen').style.fontFamily=d.font==='system'?'system-ui':d.font+',Georgia,serif';document.getElementById('phoneScreen').style.borderRadius=d.radius;document.getElementById('phoneHero').style.backgroundImage=d.hero?`url("${d.hero}")`:'';document.getElementById('phoneHero').style.display=d.hero?'block':'none';document.getElementById('phoneLogo').innerHTML=d.logo?`<img src="${d.logo}" alt="logo">`:esc((d.name||'M').slice(0,1));document.getElementById('phoneLogo').style.borderColor=d.accent;document.getElementById('phoneLogo').style.color=d.accent;document.getElementById('previewInfo').innerHTML=(d.showAbout&&d.about?`<b>О ресторане</b><br>${esc(d.about)}`:'')+(d.showContacts&&[d.phone,d.address,d.hours,d.social,d.wifi].filter(Boolean).length?`<div style="margin-top:8px"><b>Контакты</b><br>${[d.phone,d.address,d.hours,d.social,d.wifi].filter(Boolean).map(esc).join('<br>')}</div>`:'');document.getElementById('phoneScreen').style.background=d.surface;document.getElementById('phoneScreen').style.color=d.text;document.getElementById('previewBody').style.background=d.bg;}
function render(){renderCats();renderItems();renderPreview();}
function setColor(key,inputId,textId){const value=document.getElementById(inputId).value;state.design[key]=value;document.getElementById(textId).value=value;renderPreview();save();}
function fillDesignForm(){const d=state.design;dName.value=d.name;dTagline.value=d.tagline;dAbout.value=d.about;[['accent','dAccent','dAccentText'],['text','dText','dTextText'],['bg','dBg','dBgText'],['surface','dSurface','dSurfaceText']].forEach(([k,i,t])=>{document.getElementById(i).value=d[k];document.getElementById(t).value=d[k]});dTheme.value=d.theme;dFont.value=d.font;dRadius.value=d.radius;dPhone.value=d.phone;dAddress.value=d.address;dHours.value=d.hours;dSocial.value=d.social;dWifi.value=d.wifi;dShowPrices.checked=d.showPrices;dShowDescriptions.checked=d.showDescriptions;dShowComposition.checked=d.showComposition;dShowAbout.checked=d.showAbout;dShowContacts.checked=d.showContacts;}
function readDesignForm(){const d=state.design;d.name=dName.value.trim()||'Мой ресторан';d.tagline=dTagline.value.trim()||'QR Menu';d.about=dAbout.value.trim();d.theme=dTheme.value;d.font=dFont.value;d.radius=dRadius.value;d.phone=dPhone.value.trim();d.address=dAddress.value.trim();d.hours=dHours.value.trim();d.social=dSocial.value.trim();d.wifi=dWifi.value.trim();d.showPrices=dShowPrices.checked;d.showDescriptions=dShowDescriptions.checked;d.showComposition=dShowComposition.checked;d.showAbout=dShowAbout.checked;d.showContacts=dShowContacts.checked;save();renderPreview();}
async function fileToDataUrl(file,max=1400){return new Promise(resolve=>{const r=new FileReader();r.onload=e=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82));};im.src=e.target.result;};r.readAsDataURL(file);});}
function openEdit(id=null){editId=id;const d=id?state.dishes.find(x=>String(x.id)===String(id)):{cat:state.active,name:'',price:'',desc:'',source:'local'};if(d&&d.source==='iiko'){alert('Это блюдо является зеркалом iiko. Измените его в iiko и выполните синхронизацию.');return;}document.getElementById('modalTitle').textContent=id?'Изменить блюдо':'Добавить блюдо';fName.value=d.name||'';fPrice.value=d.price??'';fDesc.value=d.desc||'';fCat.value=d.cat||state.active;fPhoto.value='';modal.classList.add('show');}
const modal=document.getElementById('modal'),fName=document.getElementById('fName'),fPrice=document.getElementById('fPrice'),fDesc=document.getElementById('fDesc'),fCat=document.getElementById('fCat');
document.getElementById('addDishBtn').onclick=()=>openEdit();document.getElementById('closeModal').onclick=document.getElementById('cancelModal').onclick=()=>modal.classList.remove('show');document.getElementById('saveDish').onclick=async()=>{let photo=null;if(document.getElementById('fPhoto').files[0])photo=await resizeImage(document.getElementById('fPhoto').files[0]);if(editId){const d=state.dishes.find(x=>String(x.id)===String(editId));if(!d)return;if(d.source==='iiko'){alert('Блюдо iiko изменяется только в iiko.');return;}Object.assign(d,{name:fName.value.trim(),price:Number(fPrice.value)||0,desc:fDesc.value.trim(),cat:fCat.value});if(photo)d.photo=photo;}else state.dishes.push({id:'local_'+Date.now(),name:fName.value.trim(),price:Number(fPrice.value)||0,desc:fDesc.value.trim(),cat:fCat.value,photo,source:'local'});state.active=fCat.value;save();modal.classList.remove('show');render();};
document.getElementById('fPhoto').onchange=async()=>{if(editId&&document.getElementById('fPhoto').files[0]){const d=state.dishes.find(x=>String(x.id)===String(editId));if(d){d.photo=await resizeImage(document.getElementById('fPhoto').files[0]);save();render();}}};
function resizeImage(file){return new Promise(resolve=>{const r=new FileReader();r.onload=e=>{const im=new Image();im.onload=()=>{const max=900,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78));};im.src=e.target.result;};r.readAsDataURL(file);});}
document.getElementById('addCatBtn').onclick=()=>{const name=prompt('Название новой категории:');if(!name)return;const id='local_cat_'+Date.now();state.categories.push({id,name:name.trim(),source:'local'});state.active=id;save();render();};
document.getElementById('sortBtn').onclick=()=>{sortAsc=!sortAsc;renderItems();};document.getElementById('searchDish').oninput=renderItems;
async function syncIiko(){const btn=document.getElementById('syncBtn');const old=btn.textContent;btn.disabled=true;btn.textContent='↻ Синхронизация...';try{const connection=JSON.parse(localStorage.getItem('iikoConnection')||'null')||JSON.parse(localStorage.getItem('iiko')||'null')||JSON.parse(localStorage.getItem('iikoSettings')||'null');if(!connection){alert('Сначала подключитесь к локальному iiko Server в «Настройки».');return;}const ip=connection.ip||connection.host||connection.serverIp;const port=connection.port||connection.serverPort||'8080';const login=connection.login||connection.username;const password=connection.password||connection.pass;if(!ip||!login||!password){alert('Не найдены IP, порт, логин или пароль локального iiko Server.');return;}const response=await fetch('/api/iiko/qr-menu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip,port,login,password})});const data=await response.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!response.ok||!data.success)throw new Error(data.message||`HTTP ${response.status}`);const iikoCategories=(data.categories||[]).map(c=>({id:'iiko_cat_'+c.iikoId,iikoId:c.iikoId,name:c.name,source:'iiko',sortOrder:c.sortOrder??0}));const iikoDishes=(data.products||[]).map(p=>({id:'iiko_'+p.id,iikoId:p.id,cat:'iiko_cat_'+p.categoryId,name:p.name,price:p.price??0,desc:p.description||'',source:'iiko',code:p.code||'',num:p.num||'',frontImageId:p.frontImageId||null,sortOrder:p.sortOrder??0}));const localCategories=state.categories.filter(c=>c.source!=='iiko');const localDishes=state.dishes.filter(d=>d.source!=='iiko');const oldActive=state.active;state.categories=[...localCategories,...iikoCategories];state.dishes=[...localDishes,...iikoDishes];state.active=state.categories.some(c=>c.id===oldActive)?oldActive:(iikoCategories[0]?.id||localCategories[0]?.id||'');save();render();alert(`Синхронизация успешна. iiko: ${iikoDishes.length} блюд, ${iikoCategories.length} групп. Снятые с продажи блюда не добавлены.`);}catch(error){alert(`Не удалось синхронизировать меню iiko:\n${error.message||error}`);}finally{btn.disabled=false;btn.textContent=old;}}
document.getElementById('syncBtn').onclick=syncIiko;
const settingsModal=document.getElementById('settingsModal');document.getElementById('designBtn').onclick=()=>{fillDesignForm();settingsModal.classList.add('show')};document.getElementById('closeSettings').onclick=()=>settingsModal.classList.remove('show');settingsModal.onclick=e=>{if(e.target===settingsModal)settingsModal.classList.remove('show')};
['dName','dTagline','dAbout','dTheme','dFont','dRadius','dPhone','dAddress','dHours','dSocial','dWifi','dShowPrices','dShowDescriptions','dShowComposition','dShowAbout','dShowContacts'].forEach(id=>{document.getElementById(id).addEventListener('input',readDesignForm);document.getElementById(id).addEventListener('change',readDesignForm)});
[['accent','dAccent','dAccentText'],['text','dText','dTextText'],['bg','dBg','dBgText'],['surface','dSurface','dSurfaceText']].forEach(([k,i,t])=>{document.getElementById(i).oninput=()=>setColor(k,i,t);document.getElementById(t).onchange=()=>{const v=document.getElementById(t).value.trim();if(/^#[0-9a-fA-F]{6}$/.test(v)){state.design[k]=v;document.getElementById(i).value=v;save();renderPreview();}}});
document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{const p=b.dataset.palette;const palettes={gold:{accent:'#D4AF37',text:'#17211c',bg:'#f4f1ea',surface:'#fffdf8',theme:'light'},green:{accent:'#42D392',text:'#17211c',bg:'#f1f5f3',surface:'#ffffff',theme:'light'},blue:{accent:'#4DA3FF',text:'#162333',bg:'#eef4fa',surface:'#ffffff',theme:'light'},rose:{accent:'#E98AA3',text:'#281a20',bg:'#f8f0f3',surface:'#fffafb',theme:'light'},cream:{accent:'#B87932',text:'#33251a',bg:'#fff9ef',surface:'#ffffff',theme:'warm'}};Object.assign(state.design,palettes[p]||{});save();fillDesignForm();renderPreview();});
document.getElementById('dHero').onchange=async e=>{if(e.target.files[0]){state.design.hero=await fileToDataUrl(e.target.files[0]);save();renderPreview();}};document.getElementById('dLogo').onchange=async e=>{if(e.target.files[0]){state.design.logo=await fileToDataUrl(e.target.files[0],600);save();renderPreview();}};
document.getElementById('resetDesign').onclick=()=>{if(confirm('Сбросить настройки дизайна?')){state.design={...DEFAULT_DESIGN};save();fillDesignForm();renderPreview();}};document.getElementById('saveDesign').onclick=()=>{readDesignForm();settingsModal.classList.remove('show');alert('Дизайн сохранён. Нажмите «Опубликовать меню», чтобы применить его в публичном QR Menu.');};
document.getElementById('publishBtn').onclick=async()=>{const btn=document.getElementById('publishBtn');const organizationId=localStorage.getItem('iikoOrganizationId')||localStorage.getItem('organizationId')||state.organizationId||'';if(!organizationId){alert('Не найден ID организации iiko. Сначала выполните подключение/синхронизацию iiko.');return;}btn.disabled=true;btn.textContent='Публикация...';try{const payload={organizationId,restaurantName:state.design.name||'Мой ресторан',menu:{categories:state.categories.map((c,i)=>({...c,sortOrder:c.sortOrder??i})),dishes:state.dishes,design:state.design}};const r=await fetch('/api/qr-menu/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!d.success)throw new Error(d.message||`HTTP ${r.status}`);state.publicUrl=d.publicUrl;save();alert(`Меню опубликовано!\n${d.publicUrl}`);}catch(e){alert(`Ошибка публикации: ${e.message||e}`)}finally{btn.disabled=false;btn.textContent='Опубликовать меню';}};
render();
