(() => {
  'use strict';
  const KEY='horeca_qr_menu_v1';
  const DEFAULT_DESIGN={name:'Мой ресторан',tagline:'QR Menu',about:'Добро пожаловать! Мы создаём вкусные блюда и приятные моменты для наших гостей.',accent:'#D4AF37',text:'#17211c',bg:'#f4f6f5',surface:'#ffffff',theme:'light',font:'Inter',radius:'16px',hero:'',logo:'',phone:'',address:'',hours:'',social:'',wifi:'',showPrices:true,showDescriptions:true,showComposition:true,showAbout:true,showContacts:true};
  const DEFAULT_STATE={categories:[{id:'main',name:'Основные блюда',source:'local'},{id:'salads',name:'Салаты',source:'local'},{id:'pizza',name:'Пицца',source:'local'},{id:'drinks',name:'Напитки',source:'local'},{id:'desserts',name:'Десерты',source:'local'}],active:'main',dishes:[{id:1,cat:'main',name:'Шашлык из телятины',price:16,desc:'Телятина, лук, зелень',source:'local'},{id:2,cat:'main',name:'Паста Карбонара',price:13,desc:'Паста, сливочный соус, сыр',source:'local'},{id:3,cat:'salads',name:'Цезарь с курицей',price:13,desc:'Курица, салат, соус Цезарь',source:'local'},{id:4,cat:'pizza',name:'Пицца Маргарита',price:12,desc:'Томат, моцарелла, базилик',source:'local'},{id:5,cat:'drinks',name:'Лимонад',price:9,desc:'Лимон, мята, вода',source:'local'}],design:{...DEFAULT_DESIGN}};
  let state=null,editId=null,sortAsc=true;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function loadState(){try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){state=null}if(!state||typeof state!=='object')state=JSON.parse(JSON.stringify(DEFAULT_STATE));state.design={...DEFAULT_DESIGN,...(state.design||{})};state.categories=Array.isArray(state.categories)?state.categories.map(c=>({...c,source:c.source||'local'})):[];state.dishes=Array.isArray(state.dishes)?state.dishes.map(d=>({...d,source:d.source||'local'})):[];if(!state.categories.length)state.categories=JSON.parse(JSON.stringify(DEFAULT_STATE.categories));if(!state.active||!state.categories.some(c=>c.id===state.active))state.active=state.categories[0].id}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));if($('saveStatus'))$('saveStatus').textContent='● Изменения сохранены'}
  function renderCats(){const el=$('categories');if(!el)return;el.innerHTML=state.categories.map(c=>`<div class="cat ${c.id===state.active?'active':''}" data-cat="${esc(c.id)}"><span>☷ &nbsp;${esc(c.name)}${c.source==='iiko'?'<span class="source-badge">iiko</span>':''}</span><span>${state.dishes.filter(d=>d.cat===c.id).length}</span></div>`).join('');el.querySelectorAll('.cat').forEach(x=>x.addEventListener('click',()=>{state.active=x.dataset.cat;save();render()}));if($('fCat'))$('fCat').innerHTML=state.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}
  function renderItems(){const el=$('items');if(!el)return;const q=($('searchDish')?.value||'').toLowerCase();let ds=state.dishes.filter(d=>d.cat===state.active&&(d.name+' '+(d.desc||'')).toLowerCase().includes(q));ds.sort((a,b)=>sortAsc?a.name.localeCompare(b.name):b.name.localeCompare(a.name));el.innerHTML=ds.length?ds.map(d=>`<div class="item" data-id="${esc(d.id)}"><div class="photo">${d.photo?`<img src="${d.photo}" alt="">`:'🍽'}</div><div><h4>${esc(d.name)}${d.source==='iiko'?'<span class="source-badge">iiko</span>':''}</h4><p>${esc(d.desc||'Состав не указан')}</p><div class="item-actions"><button type="button" class="mini edit" data-id="${esc(d.id)}">Изменить</button><button type="button" class="mini photoBtn" data-id="${esc(d.id)}">Фото</button><button type="button" class="mini del" data-id="${esc(d.id)}">Удалить</button></div></div><div class="price">${Number(d.price||0).toFixed(2)} ₼</div></div>`).join(''):'<div class="empty">В этой категории пока нет блюд.<br>Нажмите «Добавить блюдо».</div>';el.querySelectorAll('.edit').forEach(b=>b.addEventListener('click',()=>openEdit(b.dataset.id)));el.querySelectorAll('.del').forEach(b=>b.addEventListener('click',()=>deleteDish(b.dataset.id)));el.querySelectorAll('.photoBtn').forEach(b=>b.addEventListener('click',()=>{editId=b.dataset.id;$('fPhoto')?.click()}))}
  function renderPreview(){const d=state.design;if(!$('previewBody'))return;$('previewBody').innerHTML=state.categories.map(c=>{const ds=state.dishes.filter(x=>x.cat===c.id);if(!ds.length)return'';return`<div class="p-cat">${esc(c.name)}</div>`+ds.map(x=>`<div class="p-item"><div class="p-photo">${x.photo?`<img src="${x.photo}" alt="">`:'🍽'}</div><div><b>${esc(x.name)}</b>${d.showDescriptions&&x.desc?`<span>${esc(x.desc)}</span>`:''}</div>${d.showPrices?`<div class="p-price">${Number(x.price||0).toFixed(2)} ₼</div>`:''}</div>`}).join('')}).join('');$('previewName').textContent=d.name||'Мой ресторан';$('previewTagline').textContent=d.tagline||'QR Menu';$('phoneTop').style.background=d.theme==='dark'?'#111':d.accent;$('phoneScreen').style.fontFamily=d.font==='system'?'system-ui':d.font+',Georgia,serif';$('phoneScreen').style.borderRadius=d.radius;$('phoneHero').style.backgroundImage=d.hero?`url("${d.hero}")`:'';$('phoneHero').style.display=d.hero?'block':'none';$('phoneLogo').innerHTML=d.logo?`<img src="${d.logo}" alt="logo">`:esc((d.name||'M').slice(0,1));$('phoneLogo').style.borderColor=d.accent;$('phoneLogo').style.color=d.accent;$('phoneScreen').style.background=d.surface;$('phoneScreen').style.color=d.text;$('previewBody').style.background=d.bg;$('previewInfo').innerHTML=(d.showAbout&&d.about?`<b>О ресторане</b><br>${esc(d.about)}`:'')+(d.showContacts&&[d.phone,d.address,d.hours,d.social,d.wifi].some(Boolean)?`<div style="margin-top:8px"><b>Контакты</b><br>${[d.phone,d.address,d.hours,d.social,d.wifi].filter(Boolean).map(esc).join('<br>')}</div>`:'')}
  function render(){renderCats();renderItems();renderPreview()}
  function openEdit(id=null){editId=id;const d=id?state.dishes.find(x=>String(x.id)===String(id)):{cat:state.active,name:'',price:'',desc:'',source:'local'};if(!d)return;if(d.source==='iiko'){alert('Это блюдо является зеркалом iiko. Измените его в iiko и выполните синхронизацию.');return}$('modalTitle').textContent=id?'Изменить блюдо':'Добавить блюдо';$('fName').value=d.name||'';$('fPrice').value=d.price??'';$('fDesc').value=d.desc||'';$('fCat').value=d.cat||state.active;$('fPhoto').value='';$('modal').classList.add('show')}
  function deleteDish(id){const d=state.dishes.find(x=>String(x.id)===String(id));if(!d)return;if(d.source==='iiko'){alert('Это блюдо является зеркалом iiko. Измените его в iiko и выполните синхронизацию.');return}state.dishes=state.dishes.filter(x=>String(x.id)!==String(id));save();render()}
  function resizeImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=e=>{const im=new Image();im.onerror=reject;im.onload=()=>{const max=900,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};im.src=e.target.result};r.readAsDataURL(file)})}
  function fillDesignForm(){const d=state.design;$('dName').value=d.name;$('dTagline').value=d.tagline;$('dAbout').value=d.about;[['accent','dAccent','dAccentText'],['text','dText','dTextText'],['bg','dBg','dBgText'],['surface','dSurface','dSurfaceText']].forEach(([k,i,t])=>{$(i).value=d[k];$(t).value=d[k]});$('dTheme').value=d.theme;$('dFont').value=d.font;$('dRadius').value=d.radius;$('dPhone').value=d.phone;$('dAddress').value=d.address;$('dHours').value=d.hours;$('dSocial').value=d.social;$('dWifi').value=d.wifi;$('dShowPrices').checked=!!d.showPrices;$('dShowDescriptions').checked=!!d.showDescriptions;$('dShowComposition').checked=!!d.showComposition;$('dShowAbout').checked=!!d.showAbout;$('dShowContacts').checked=!!d.showContacts}
  function readDesignForm(){const d=state.design;d.name=$('dName').value.trim()||'Мой ресторан';d.tagline=$('dTagline').value.trim()||'QR Menu';d.about=$('dAbout').value.trim();d.theme=$('dTheme').value;d.font=$('dFont').value;d.radius=$('dRadius').value;d.phone=$('dPhone').value.trim();d.address=$('dAddress').value.trim();d.hours=$('dHours').value.trim();d.social=$('dSocial').value.trim();d.wifi=$('dWifi').value.trim();d.showPrices=$('dShowPrices').checked;d.showDescriptions=$('dShowDescriptions').checked;d.showComposition=$('dShowComposition').checked;d.showAbout=$('dShowAbout').checked;d.showContacts=$('dShowContacts').checked;save();renderPreview()}
  async function syncIiko(){const btn=$('syncBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='↻ Синхронизация...';try{const connection=JSON.parse(localStorage.getItem('iikoConnection')||'null')||JSON.parse(localStorage.getItem('iiko')||'null')||JSON.parse(localStorage.getItem('iikoSettings')||'null');if(!connection)throw new Error('Сначала подключитесь к локальному iiko Server в «Настройки».');const ip=connection.ip||connection.host||connection.serverIp,port=connection.port||connection.serverPort||'8080',login=connection.login||connection.username,password=connection.password||connection.pass;if(!ip||!login||!password)throw new Error('Не найдены IP, порт, логин или пароль локального iiko Server.');const r=await fetch('/api/iiko/qr-menu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip,port,login,password})}),data=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!data.success)throw new Error(data.message||`HTTP ${r.status}`);const cats=(data.categories||[]).map(c=>({id:'iiko_cat_'+c.iikoId,iikoId:c.iikoId,name:c.name,source:'iiko',sortOrder:c.sortOrder??0})),dishes=(data.products||[]).map(p=>({id:'iiko_'+p.id,iikoId:p.id,cat:'iiko_cat_'+p.categoryId,name:p.name,price:p.price??0,desc:p.description||'',source:'iiko',code:p.code||'',num:p.num||'',frontImageId:p.frontImageId||null,sortOrder:p.sortOrder??0}));const localCats=state.categories.filter(c=>c.source!=='iiko'),localDishes=state.dishes.filter(d=>d.source!=='iiko'),oldActive=state.active;state.categories=[...localCats,...cats];state.dishes=[...localDishes,...dishes];state.active=state.categories.some(c=>c.id===oldActive)?oldActive:(cats[0]?.id||localCats[0]?.id||'');save();render();alert(`Синхронизация успешна. iiko: ${dishes.length} блюд, ${cats.length} групп.`)}catch(e){alert(`Не удалось синхронизировать меню iiko:\n${e.message||e}`)}finally{btn.disabled=false;btn.textContent=old}}
  async function publishMenu(){const btn=$('publishBtn'),organizationId=localStorage.getItem('iikoOrganizationId')||localStorage.getItem('organizationId')||state.organizationId||'';if(!organizationId){alert('Не найден ID организации iiko. Сначала выполните подключение/синхронизацию iiko.');return}btn.disabled=true;btn.textContent='Публикация...';try{const r=await fetch('/api/qr-menu/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,restaurantName:state.design.name||'Мой ресторан',menu:{categories:state.categories,dishes:state.dishes,design:state.design}})}),d=await r.json().catch(()=>({success:false,message:'Некорректный ответ API'}));if(!r.ok||!d.success)throw new Error(d.message||`HTTP ${r.status}`);state.publicUrl=d.publicUrl;save();alert(`Меню опубликовано!\n${d.publicUrl||''}`)}catch(e){alert(`Ошибка публикации: ${e.message||e}`)}finally{btn.disabled=false;btn.textContent='Опубликовать меню'}}
  function bind(){
    $('addDishBtn')?.addEventListener('click',()=>openEdit());
    $('designBtn')?.addEventListener('click',()=>{fillDesignForm();$('settingsModal').classList.add('show')});
    $('closeSettings')?.addEventListener('click',()=>$('settingsModal').classList.remove('show'));
    $('settingsModal')?.addEventListener('click',e=>{if(e.target===$('settingsModal'))$('settingsModal').classList.remove('show')});
    $('syncBtn')?.addEventListener('click',syncIiko);$('publishBtn')?.addEventListener('click',publishMenu);
    $('addCatBtn')?.addEventListener('click',()=>{const name=prompt('Название новой категории:');if(!name?.trim())return;const id='local_cat_'+Date.now();state.categories.push({id,name:name.trim(),source:'local'});state.active=id;save();render()});
    $('sortBtn')?.addEventListener('click',()=>{sortAsc=!sortAsc;renderItems()});$('searchDish')?.addEventListener('input',renderItems);
    $('closeModal')?.addEventListener('click',()=>$('modal').classList.remove('show'));$('cancelModal')?.addEventListener('click',()=>$('modal').classList.remove('show'));
    $('saveDish')?.addEventListener('click',async()=>{const name=$('fName').value.trim();if(!name){alert('Введите название блюда.');return}let photo=null;if($('fPhoto').files[0])photo=await resizeImage($('fPhoto').files[0]);if(editId){const d=state.dishes.find(x=>String(x.id)===String(editId));if(!d||d.source==='iiko')return;Object.assign(d,{name,price:Number($('fPrice').value)||0,desc:$('fDesc').value.trim(),cat:$('fCat').value});if(photo)d.photo=photo}else state.dishes.push({id:'local_'+Date.now(),name,price:Number($('fPrice').value)||0,desc:$('fDesc').value.trim(),cat:$('fCat').value,photo,source:'local'});state.active=$('fCat').value;save();$('modal').classList.remove('show');render()});
    $('fPhoto')?.addEventListener('change',async()=>{if(!editId||!$('fPhoto').files[0])return;const d=state.dishes.find(x=>String(x.id)===String(editId));if(d&&d.source!=='iiko'){d.photo=await resizeImage($('fPhoto').files[0]);save();render()}});
    ['dName','dTagline','dAbout','dTheme','dFont','dRadius','dPhone','dAddress','dHours','dSocial','dWifi','dShowPrices','dShowDescriptions','dShowComposition','dShowAbout','dShowContacts'].forEach(id=>{$(id)?.addEventListener('input',readDesignForm);$(id)?.addEventListener('change',readDesignForm)});
    [['accent','dAccent','dAccentText'],['text','dText','dTextText'],['bg','dBg','dBgText'],['surface','dSurface','dSurfaceText']].forEach(([k,i,t])=>{$(i)?.addEventListener('input',()=>{state.design[k]=$(i).value;$(t).value=$(i).value;save();renderPreview()});$(t)?.addEventListener('change',()=>{const v=$(t).value.trim();if(/^#[0-9a-fA-F]{6}$/.test(v)){state.design[k]=v;$(i).value=v;save();renderPreview()}})});
    document.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.palette,pal={gold:{accent:'#D4AF37',text:'#17211c',bg:'#f4f1ea',surface:'#fffdf8',theme:'light'},green:{accent:'#42D392',text:'#17211c',bg:'#f1f5f3',surface:'#ffffff',theme:'light'},blue:{accent:'#4DA3FF',text:'#162333',bg:'#eef4fa',surface:'#ffffff',theme:'light'},rose:{accent:'#E98AA3',text:'#281a20',bg:'#f8f0f3',surface:'#fffafb',theme:'light'},cream:{accent:'#B87932',text:'#33251a',bg:'#fff9ef',surface:'#ffffff',theme:'warm'}};Object.assign(state.design,pal[p]||{});save();fillDesignForm();renderPreview()}));
    $('dHero')?.addEventListener('change',async e=>{if(e.target.files[0]){state.design.hero=await resizeImage(e.target.files[0]);save();renderPreview()}});$('dLogo')?.addEventListener('change',async e=>{if(e.target.files[0]){state.design.logo=await resizeImage(e.target.files[0]);save();renderPreview()}});
    $('resetDesign')?.addEventListener('click',()=>{if(confirm('Сбросить настройки дизайна?')){state.design={...DEFAULT_DESIGN};save();fillDesignForm();renderPreview()}});$('saveDesign')?.addEventListener('click',()=>{readDesignForm();$('settingsModal').classList.remove('show');alert('Дизайн сохранён. Нажмите «Опубликовать меню», чтобы применить его в публичном QR Menu.')});
  }
  function init(){if(!$('addDishBtn'))return;loadState();bind();render();console.info('QR Menu initialized')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
