import { clean, iikoText } from './_lib/iiko-client.js';

function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}})}
function xmlDecode(v){return String(v||"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").trim()}
function xmlChild(block,name){const m=block.match(new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)<\\/${name}>`,`i`));return m?xmlDecode(m[1].replace(/<[^>]+>/g,"")):""}
function parseCorporateXml(text){const out=[];const re=/<(?:corporateItemDto|corporateItem|item|entity)\b[^>]*>([\s\S]*?)<\/(?:corporateItemDto|corporateItem|item|entity)>/gi;let m;while((m=re.exec(text))){const b=m[1]||"",id=xmlChild(b,"id"),type=xmlChild(b,"type").toUpperCase();if(!id)continue;out.push({id,parentId:xmlChild(b,"parentId")||null,code:xmlChild(b,"code"),name:xmlChild(b,"name")||xmlChild(b,"code")||id,type:type||"UNKNOWN"})}return out}
function corporateObjects(payload){const out=[],seen=new Set();function walk(v){if(!v||typeof v!=="object")return;if(Array.isArray(v)){v.forEach(walk);return}const type=clean(v.type??v.Type??v.itemType??v.entityType).toUpperCase(),id=v.id??v.Id??v.ID??v.uuid??v.UUID,name=v.name??v.Name,known=["CORPORATION","JURPERSON","ORGDEVELOPMENT","DEPARTMENT"].includes(type);if(id!=null&&(known||name)&&!seen.has(String(id))){out.push({id:String(id),parentId:v.parentId??v.parentID??v.ParentId??null,code:clean(v.code??v.Code),name:clean(name||v.code||v.Code||id),type:type||"UNKNOWN"});seen.add(String(id))}Object.values(v).forEach(walk)}walk(payload);return out}
function groupObjects(payload){const groups=[],pos=[],sections=[],seenG=new Set(),seenP=new Set(),seenS=new Set();function walk(v,parent){if(!v||typeof v!=="object")return;if(Array.isArray(v)){v.forEach(x=>walk(x,parent));return}const type=clean(v.type??v.Type).toUpperCase(),id=v.id??v.Id??v.ID,name=v.name??v.Name,looksGroup=type==="GROUP"||type==="GROUPDTO"||Array.isArray(v.pointOfSaleDtoes)||Array.isArray(v.pointOfSaleDto)||v.pointOfSaleDtoes?.pointOfSaleDto;if(id!=null&&looksGroup&&!seenG.has(String(id))){groups.push({id:String(id),name:clean(name||id),departmentId:v.departmentId??v.DepartmentId??null});seenG.add(String(id))}const p=v.pointOfSaleDtoes?.pointOfSaleDto??v.pointOfSaleDtoes??v.pointOfSaleDto??null,parr=Array.isArray(p)?p:[p];for(const x of parr){if(!x||typeof x!=="object")continue;const pid=x.id??x.Id??x.ID;if(pid!=null&&!seenP.has(String(pid))){pos.push({id:String(pid),name:clean(x.name??x.Name??pid),main:x.main===true||x.Main===true,groupId:id!=null?String(id):null,cashRegisterInfo:x.cashRegisterInfo??x.CashRegisterInfo??null});seenP.add(String(pid))}walk(x.restaurantSectionIds??x.restaurantSectionInfos,{posId:pid,groupId:id})}const rsi=v.restaurantSectionInfos?.restaurantSectionInfo??v.restaurantSectionInfo??v.restaurantSectionIds??null,ra=Array.isArray(rsi)?rsi:[rsi];for(const s of ra){if(!s)continue;const sid=s.id??s.Id??s.ID??s.i;if(sid!=null&&!seenS.has(String(sid))){sections.push({id:String(sid),name:clean(s.name??s.Name??sid),groupId:parent?.groupId??(id!=null?String(id):null),pointOfSaleId:parent?.posId??null});seenS.add(String(sid))}}for(const[k,x]of Object.entries(v))if(!["pointOfSaleDtoes","pointOfSaleDto","restaurantSectionInfos","restaurantSectionInfo","restaurantSectionIds"].includes(k))walk(x,parent)}walk(payload,null);return{groups,pointsOfSale:pos,restaurantSections:sections}}
async function getJsonOrXml(connection,path){const r=await iikoText(connection,path,{headers:{Accept:"application/json, application/xml, text/xml"}});if(!r.ok)throw Error(`HTTP ${r.status}${r.text?` — ${r.text.slice(0,600)}`:""}`);if(!r.text)return{payload:{},rawFormat:"empty",rawPreview:"",authCacheHit:Boolean(r.auth?.cacheHit)};try{return{payload:JSON.parse(r.text),rawFormat:"json",rawPreview:r.text.slice(0,1200),authCacheHit:Boolean(r.auth?.cacheHit)}}catch{return{payload:null,rawFormat:"xml",rawPreview:r.text.slice(0,1200),xml:r.text,authCacheHit:Boolean(r.auth?.cacheHit)}}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()})}
export async function onRequestPost({request}){try{const b=await request.json(),connection={ip:clean(b.ip),port:clean(b.port),login:clean(b.login),password:String(b.password??"")};if(!connection.ip||!connection.port||!connection.login||!connection.password)return json({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const[dep,grp]=await Promise.all([getJsonOrXml(connection,"/resto/api/corporation/departments?revisionFrom=-1"),getJsonOrXml(connection,"/resto/api/corporation/groups?revisionFrom=-1")]);const hierarchy=dep.rawFormat==="xml"?parseCorporateXml(dep.xml):corporateObjects(dep.payload),depts=hierarchy.filter(x=>x.type==="DEPARTMENT"),corporation=hierarchy.find(x=>x.type==="CORPORATION")||null,groupData=grp.rawFormat==="xml"?{groups:[],pointsOfSale:[],restaurantSections:[]}:groupObjects(grp.payload),departments=depts.map(x=>({id:x.id,parentId:x.parentId,code:x.code,name:x.name,type:x.type})),restaurants=departments.map(x=>({id:x.id,name:x.name,code:x.code,parentId:x.parentId}),),detectedMode=departments.length>1?"CHAIN":"RMS";return json({success:true,mode:detectedMode,detectedMode,organization:corporation,departments,restaurants,hierarchy,groups:groupData.groups,pointsOfSale:groupData.pointsOfSale,restaurantSections:groupData.restaurantSections,source:"iiko-corporation-api",server:{ip:connection.ip,port:connection.port},loadedAt:new Date().toISOString(),meta:{departmentAuthCacheHit:dep.authCacheHit,groupAuthCacheHit:grp.authCacheHit}})}catch(error){return json({success:false,message:error?.message||"Не удалось определить тип SH Server"},502)}}
