function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders()}})}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function clean(v){return String(v??"").trim()}
function xmlDecode(v){return String(v||"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").trim()}
function xmlChild(block,name){const m=block.match(new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"));return m?xmlDecode(m[1].replace(/<[^>]+>/g,"")):""}
function parseCorporateXml(text){const out=[];const re=/<(?:corporateItemDto|corporateItem|item|entity)\\b[^>]*>([\\s\\S]*?)<\\/(?:corporateItemDto|corporateItem|item|entity)>/gi;let m;while((m=re.exec(text))){const b=m[1]||"";const id=xmlChild(b,"id");const type=xmlChild(b,"type").toUpperCase();if(!id)continue;out.push({id,parentId:xmlChild(b,"parentId")||null,code:xmlChild(b,"code"),name:xmlChild(b,"name")||xmlChild(b,"code")||id,type:type||"UNKNOWN"})}return out}
function corporateObjects(payload){const out=[];const seen=new Set();function walk(v){if(!v||typeof v!=="object")return;if(Array.isArray(v)){v.forEach(walk);return}const type=clean(v.type??v.Type??v.itemType??v.entityType).toUpperCase();const id=v.id??v.Id??v.ID??v.uuid??v.UUID;const name=v.name??v.Name;const known=["CORPORATION","JURPERSON","ORGDEVELOPMENT","DEPARTMENT"].includes(type);if(id!=null&&(known||name)&&!seen.has(String(id))){out.push({id:String(id),parentId:v.parentId??v.parentID??v.ParentId??null,code:clean(v.code??v.Code),name:clean(name||v.code||v.Code||id),type:type||"UNKNOWN"});seen.add(String(id))}Object.values(v).forEach(walk)}walk(payload);return out}
function groupObjects(payload){const groups=[];const pos=[];const sections=[];const seenG=new Set(),seenP=new Set(),seenS=new Set();function walk(v,parent){if(!v||typeof v!=="object")return;if(Array.isArray(v)){v.forEach(x=>walk(x,parent));return}const type=clean(v.type??v.Type).toUpperCase();const id=v.id??v.Id??v.ID;const name=v.name??v.Name;const looksGroup=type==="GROUP"||type==="GROUPDTO"||Array.isArray(v.pointOfSaleDtoes)||Array.isArray(v.pointOfSaleDto)||v.pointOfSaleDtoes?.pointOfSaleDto; if(id!=null&&looksGroup&&!seenG.has(String(id))){groups.push({id:String(id),name:clean(name||id),departmentId:v.departmentId??v.DepartmentId??null});seenG.add(String(id))}const p=v.pointOfSaleDtoes?.pointOfSaleDto??v.pointOfSaleDtoes??v.pointOfSaleDto??null;const parr=Array.isArray(p)?p:[p];for(const x of parr){if(!x||typeof x!=="object")continue;const pid=x.id??x.Id??x.ID;if(pid!=null&&!seenP.has(String(pid))){pos.push({id:String(pid),name:clean(x.name??x.Name??pid),main:x.main===true||x.Main===true,groupId:id!=null?String(id):null,cashRegisterInfo:x.cashRegisterInfo??x.CashRegisterInfo??null});seenP.add(String(pid))}const rs=x.restaurantSectionIds??x.restaurantSectionInfos;walk(rs,{posId:pid,groupId:id})}const rsi=v.restaurantSectionInfos?.restaurantSectionInfo??v.restaurantSectionInfo??v.restaurantSectionIds??null;const ra=Array.isArray(rsi)?rsi:[rsi];for(const s of ra){if(!s)continue;const sid=s.id??s.Id??s.ID??s.i;if(sid!=null&&!seenS.has(String(sid))){sections.push({id:String(sid),name:clean(s.name??s.Name??sid),groupId:parent?.groupId??(id!=null?String(id):null),pointOfSaleId:parent?.posId??null});seenS.add(String(sid))}}for(const [k,x] of Object.entries(v))if(k!=="pointOfSaleDtoes"&&k!=="pointOfSaleDto"&&k!=="restaurantSectionInfos"&&k!=="restaurantSectionInfo"&&k!=="restaurantSectionIds")walk(x,parent)}walk(payload,null);return{groups,pointsOfSale:pos,restaurantSections:sections}}
async function getToken(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const hash=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${hash}`);const token=(await r.text()).trim();if(!r.ok||!token)throw Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return{serverUrl,token}}
async function getJsonOrXml(url){const r=await fetch(url,{headers:{Accept:"application/json, application/xml, text/xml"}});const text=(await r.text()).trim();if(!r.ok)throw Error(`HTTP ${r.status}${text?` — ${text.slice(0,600)}`:""}`);if(!text)return{payload:{},rawFormat:"empty",rawPreview:""};try{return{payload:JSON.parse(text),rawFormat:"json",rawPreview:text.slice(0,1200)}}catch{return{payload:null,rawFormat:"xml",rawPreview:text.slice(0,1200),xml:text}}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()})}
export async function onRequestPost({request}){try{const b=await request.json();const ip=clean(b.ip),port=clean(b.port),login=clean(b.login),password=String(b.password??"");if(!ip||!port||!login||!password)return json({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const{serverUrl,token}=await getToken(ip,port,login,password);const dep=await getJsonOrXml(`${serverUrl}/resto/api/corporation/departments?key=${encodeURIComponent(token)}&revisionFrom=-1`);const grp=await getJsonOrXml(`${serverUrl}/resto/api/corporation/groups?key=${encodeURIComponent(token)}&revisionFrom=-1`);const hierarchy=dep.rawFormat==="xml"?parseCorporateXml(dep.xml):corporateObjects(dep.payload);const depts=hierarchy.filter(x=>x.type==="DEPARTMENT");const corporation=hierarchy.find(x=>x.type==="CORPORATION")||null;const groupData=grp.rawFormat==="xml"?{groups:[],pointsOfSale:[],restaurantSections:[]}:groupObjects(grp.payload);const departments=depts.map(x=>({id:x.id,parentId:x.parentId,code:x.code,name:x.name,type:x.type}));const restaurants=departments.map(x=>({id:x.id,name:x.name,code:x.code,parentId:x.parentId}));return json({success:true,mode:"CHAIN",organization:corporation,departments,restaurants,hierarchy,groups:groupData.groups,pointsOfSale:groupData.pointsOfSale,restaurantSections:groupData.restaurantSections,source:"iiko-chain-corporation-api",server:{ip,port},loadedAt:new Date().toISOString()})}catch(error){return json({success:false,message:error?.message||"Не удалось получить структуру iikoChain"},502)}}
