function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации iiko Server: HTTP ${r.status}`);return {serverUrl,token};}
function cleanId(v){return String(v??"").trim().replace(/^\{+|\}+$/g,"").toLowerCase();}
function cleanName(v){return String(v??"").replace(/<[^>]*>/g,"").trim();}
function xmlDecode(v){return String(v??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function localName(v){return String(v||"").split(":").pop().toLowerCase();}
function textTag(block,names){const wanted=new Set((Array.isArray(names)?names:[names]).map(localName));const re=/<([A-Za-z][\w:.-]*)\b[^>]*>([\s\S]*?)<\/\1>/gi;let m;while((m=re.exec(String(block||""))))if(wanted.has(localName(m[1])))return xmlDecode(m[2].trim());return "";}
function elementBlocks(source,names){const wanted=new Set((Array.isArray(names)?names:[names]).map(localName));const text=String(source||"");const out=[];const open=/<([A-Za-z][\w:.-]*)\b[^>]*>/gi;let m;while((m=open.exec(text))){const fullName=m[1];if(!wanted.has(localName(fullName)))continue;const esc=fullName.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const close=new RegExp(`</${esc}>`,'ig');const tail=text.slice(open.lastIndex);const cm=close.exec(tail);if(cm)out.push(text.slice(m.index,open.lastIndex+cm.index+cm[0].length));}return out;}
function openingAttrs(block){const m=String(block||"").match(/^<([A-Za-z][\w:.-]*)\b([^>]*)>/i);const a={};if(!m)return a;const re=/([A-Za-z][\w:.-]*)\s*=\s*(["'])(.*?)\2/g;let q;while((q=re.exec(m[2])))a[localName(q[1])]=xmlDecode(q[3]);return a;}
function parseJson(value,out){if(Array.isArray(value)){value.forEach(x=>parseJson(x,out));return;}if(!value||typeof value!=="object")return;const id=value.id??value.uuid??value.entityId??value.contractorId??value.contractorUuid??value.supplierId;const name=value.name??value.title??value.description??value.fullName; if(id&&name)out.push({id,name}); for(const x of Object.values(value))if(x&&typeof x==="object")parseJson(x,out);}
function parse(value){const source=String(value||"").trim();const out=[];const seen=new Set();const add=(id,name)=>{const i=cleanId(id),n=cleanName(name);if(i&&n&&!seen.has(i)){seen.add(i);out.push({id:i,name:n});}};if(!source)return out;
if(source[0]==="{"||source[0]==="["){try{const raw=[];parseJson(JSON.parse(source),raw);raw.forEach(x=>add(x.id,x.name));if(out.length)return out;}catch{}}
for(const block of elementBlocks(source,["contractor","contractorDto","contractorDTO","supplier","supplierDto","supplierDTO","entity","entityDto"])){const a=openingAttrs(block);const id=textTag(block,["id","uuid","entityId","contractorId","contractorUuid","supplierId","supplierUuid"])||a.id||a.uuid||a.entityid||a.contractorid||a.contractoruuid||a.supplierid||a.supplieruuid;const name=textTag(block,["name","title","description","fullName"])||a.name||a.title||a.description||a.fullname;if(id&&name)add(id,name);}
return out;}
async function request(serverUrl,path,token){const sep=path.includes("?")?"&":"?";const r=await fetch(`${serverUrl}${path}${sep}key=${encodeURIComponent(token)}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, */*"}});return {status:r.status,ok:r.ok,text:await r.text(),contentType:r.headers.get("content-type")||""};}
async function ensure(db){if(!db)throw new Error("D1 binding DB не настроен");await db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_suppliers (scope_id TEXT NOT NULL,supplier_id TEXT NOT NULL,supplier_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,supplier_id))`).run();}
async function load(serverUrl,token,path){const r=await request(serverUrl,path,token);const rows=r.ok?parse(r.text):[];return {r,rows};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request,env}){try{const b=await request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return json({success:false,message:"Заполните IP, порт, логин и пароль iiko Server"},400);await ensure(env.DB);const {serverUrl,token}=await auth(ip,port,login,password);const diagnostics=[];const all=[];const paths=["/resto/api/v2/entities/contractors","/resto/api/suppliers"];
for(const path of paths){const {r,rows}=await load(serverUrl,token,path);diagnostics.push({path,status:r.status,ok:r.ok,contentType:r.contentType,rawLength:r.text.length,parsedCount:rows.length});if(rows.length)all.push(...rows);}
const unique=[];const seen=new Set();for(const x of all){const id=cleanId(x.id);if(id&&!seen.has(id)){seen.add(id);unique.push({id,name:x.name});}}
const requestedIds=Array.isArray(b.supplierIds)?[...new Set(b.supplierIds.map(cleanId).filter(Boolean))]:[];const unresolved=requestedIds.filter(id=>!unique.some(x=>x.id===id));
for(const id of unresolved){for(const path of [`/resto/api/v2/entities/contractors/${encodeURIComponent(id)}`,`/resto/api/v2/entities/contractors?id=${encodeURIComponent(id)}`]){const {r,rows}=await load(serverUrl,token,path);diagnostics.push({path,status:r.status,ok:r.ok,contentType:r.contentType,rawLength:r.text.length,parsedCount:rows.length,requestedId:id});const exact=rows.find(x=>cleanId(x.id)===id);if(exact){unique.push(exact);seen.add(id);break;}}}
const scope=await sha1(serverUrl.toLowerCase());const now=new Date().toISOString();if(unique.length){await env.DB.batch(unique.map(x=>env.DB.prepare(`INSERT INTO sh_iiko_suppliers(scope_id,supplier_id,supplier_name,updated_at) VALUES(?1,?2,?3,?4) ON CONFLICT(scope_id,supplier_id) DO UPDATE SET supplier_name=excluded.supplier_name,updated_at=excluded.updated_at`).bind(scope,x.id,x.name,now)));}
const r=await env.DB.prepare(`SELECT supplier_id id,supplier_name name FROM sh_iiko_suppliers WHERE scope_id=?1`).bind(scope).all();const suppliers=Object.fromEntries((r.results||[]).map(x=>[cleanId(x.id),cleanName(x.name)]));const unresolvedAfter=requestedIds.filter(id=>!Object.prototype.hasOwnProperty.call(suppliers,id));return json({success:true,count:Object.keys(suppliers).length,suppliers,unresolvedSupplierIds:unresolvedAfter,diagnostics});}catch(e){return json({success:false,message:e?.message||"Ошибка загрузки поставщиков"},502);}}