function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации iiko Server: HTTP ${r.status}`);return {serverUrl,token};}
function cleanId(v){return String(v??"").trim().replace(/^\{+|\}+$/g,"").toLowerCase();}
function cleanName(v){return String(v??"").replace(/<[^>]*>/g,"").trim();}
function xmlDecode(v){return String(v??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function parse(value){const source=String(value||"").trim();const out=[];const seen=new Set();const add=(id,name)=>{const i=cleanId(id),n=cleanName(name);if(i&&n&&!seen.has(i)){seen.add(i);out.push({id:i,name:n});}};if(!source)return out;if(source[0]==="{"||source[0]==="["){try{const walk=v=>{if(Array.isArray(v)){v.forEach(walk);return;}if(!v||typeof v!=="object")return;const id=v.id??v.uuid??v.entityId??v.contractorId??v.supplierId;const name=v.name??v.title??v.description??v.fullName;if(id&&name)add(id,name);Object.values(v).forEach(x=>{if(x&&typeof x==="object")walk(x);});};walk(JSON.parse(source));if(out.length)return out;}catch{}}
const re=/<([A-Za-z][\\w:.-]*)\b[^>]*>([\\s\\S]*?)<\/\1>/gi;let m;while((m=re.exec(source))){const block=m[0];const id=(block.match(/<(?:id|uuid|entityId|contractorId|supplierId)[^>]*>([\\s\\S]*?)<\//i)||[])[1];const name=(block.match(/<(?:name|title|description|fullName)[^>]*>([\\s\\S]*?)<\//i)||[])[1];if(id&&name)add(xmlDecode(id),xmlDecode(name));}return out;}
async function request(serverUrl,path,token){const sep=path.includes("?")?"&":"?";const r=await fetch(`${serverUrl}${path}${sep}key=${encodeURIComponent(token)}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, */*"}});return {status:r.status,ok:r.ok,text:await r.text(),contentType:r.headers.get("content-type")||""};}
async function ensure(db){await db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_suppliers (scope_id TEXT NOT NULL,supplier_id TEXT NOT NULL,supplier_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,supplier_id))`).run();}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request,env}){try{const b=await request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return json({success:false,message:"Заполните IP, порт, логин и пароль iiko Server"},400);await ensure(env.DB);const {serverUrl,token}=await auth(ip,port,login,password);const paths=["/resto/api/v2/entities/contractors","/resto/api/suppliers"];const diagnostics=[];let rows=[];for(const path of paths){const r=await request(serverUrl,path,token);const parsed=r.ok?parse(r.text):[];diagnostics.push({path,status:r.status,ok:r.ok,contentType:r.contentType,rawLength:r.text.length,parsedCount:parsed.length});if(parsed.length)rows.push(...parsed);}const seen=new Set();rows=rows.filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true;});const scope=await sha1(serverUrl.toLowerCase());const now=new Date().toISOString();if(rows.length){await env.DB.batch(rows.map(x=>env.DB.prepare(`INSERT INTO sh_iiko_suppliers(scope_id,supplier_id,supplier_name,updated_at) VALUES(?1,?2,?3,?4) ON CONFLICT(scope_id,supplier_id) DO UPDATE SET supplier_name=excluded.supplier_name,updated_at=excluded.updated_at`).bind(scope,x.id,x.name,now)));}const r=await env.DB.prepare(`SELECT supplier_id id,supplier_name name FROM sh_iiko_suppliers WHERE scope_id=?1`).bind(scope).all();const suppliers=Object.fromEntries((r.results||[]).map(x=>[cleanId(x.id),cleanName(x.name)]));return json({success:true,count:Object.keys(suppliers).length,suppliers,diagnostics});}catch(e){return json({success:false,message:e?.message||"Ошибка загрузки поставщиков"},502);}}