function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации iiko Server: HTTP ${r.status}`);return {serverUrl,token};}
function cleanId(v){return String(v??"").trim().replace(/^\{+|\}+$/g,"").toLowerCase();}
function cleanName(v){return String(v??"").replace(/<[^>]*>/g,"").trim();}
function decode(v){return String(v??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&").trim();}
function add(out,seen,id,name){const i=cleanId(id),n=cleanName(name);if(i&&n&&!seen.has(i)){seen.add(i);out.push({id:i,name:n});}}
function parseJson(value,out,seen){if(Array.isArray(value)){for(const x of value)parseJson(x,out,seen);return;}if(!value||typeof value!=="object")return;const name=value.name??value.title??value.fullName??value.fullname??value.description;const id=value.id??value.uuid??value.entityId??value.contractorId??value.contractorUuid??value.supplierId??value.supplier_id;if(id&&name)add(out,seen,id,name);const supplier=value.supplier;if(typeof supplier==="string"&&name)add(out,seen,supplier,name);if(supplier&&typeof supplier==="object"){const sid=supplier.id??supplier.uuid??supplier.entityId??supplier.supplierId;const sn=supplier.name??supplier.title??supplier.fullName??supplier.description??name;if(sid&&sn)add(out,seen,sid,sn);}for(const x of Object.values(value))if(x&&typeof x==="object")parseJson(x,out,seen);}
function xmlBlocks(source,tag){const out=[];const re=new RegExp(`<${tag}(?:\\s[^>]*)?>[\\s\\S]*?<\\/${tag}>`,'gi');let m;while((m=re.exec(String(source||""))))out.push(m[0]);return out;}
function xmlValue(block,names){for(const name of names){const re=new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i');const m=String(block||"").match(re);if(m)return decode(m[1]);}return "";}
function xmlAttrs(block){const m=String(block||"").match(/^<[^>]+>/);const out={};if(!m)return out;const re=/([A-Za-z_:][\\w:.-]*)\\s*=\\s*(["'])(.*?)\\2/g;let x;while((x=re.exec(m[0])))out[x[1].split(':').pop().toLowerCase()]=decode(x[3]);return out;}
function parseXml(source,out,seen){const text=String(source||"");for(const tag of ["supplier","supplierDto","supplierDTO","contractor","contractorDto","contractorDTO","employee","employeeDto","employeeDTO"]){for(const block of xmlBlocks(text,tag)){const a=xmlAttrs(block);const id=xmlValue(block,["id","uuid","entityId","supplierId","supplier_id","contractorId","contractor_id"])||a.id||a.uuid||a.entityid||a.supplierid||a.supplier_id||a.contractorid||a.contractor_id;const name=xmlValue(block,["name","title","fullName","fullname","description"])||a.name||a.title||a.fullname||a.description;if(id&&name)add(out,seen,id,name);}}
// Fallback for SH Server XML where the record wrapper has another tag name.
const generic=/<([A-Za-z][\\w:.-]*)\\b[^>]*>([\\s\\S]*?)<\\/\\1>/gi;let m;while((m=generic.exec(text))){const block=m[0];const id=xmlValue(block,["id","uuid","entityId","supplierId","supplier_id"]);const name=xmlValue(block,["name","title","fullName","fullname"]);if(id&&name)add(out,seen,id,name);}}
function parse(value){const source=String(value||"").trim();const out=[],seen=new Set();if(!source)return out;if(source[0]==="{"||source[0]==="["){try{parseJson(JSON.parse(source),out,seen);if(out.length)return out;}catch{}}parseXml(source,out,seen);return out;}
async function request(serverUrl,path,token){const sep=path.includes("?")?"&":"?";const r=await fetch(`${serverUrl}${path}${sep}key=${encodeURIComponent(token)}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, */*"}});const text=await r.text();return {status:r.status,ok:r.ok,text,contentType:r.headers.get("content-type")||""};}
async function ensure(db){if(!db)throw new Error("D1 binding DB не настроен");await db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_suppliers (scope_id TEXT NOT NULL,supplier_id TEXT NOT NULL,supplier_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,supplier_id))`).run();}
async function load(serverUrl,token,path){const r=await request(serverUrl,path,token);const rows=r.ok?parse(r.text):[];return {r,rows};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request,env}){try{const b=await request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return json({success:false,message:"Заполните IP, порт, логин и пароль iiko Server"},400);await ensure(env.DB);const {serverUrl,token}=await auth(ip,port,login,password);const diagnostics=[];const all=[];const paths=["/resto/api/v2/entities/contractors","/resto/api/suppliers","/resto/api/corporation/suppliers"];
for(const path of paths){const {r,rows}=await load(serverUrl,token,path);diagnostics.push({path,status:r.status,ok:r.ok,contentType:r.contentType,rawLength:r.text.length,parsedCount:rows.length});if(rows.length)all.push(...rows);}
const unique=[];const seen=new Set();for(const x of all){const id=cleanId(x.id);if(id&&!seen.has(id)){seen.add(id);unique.push({id,name:x.name});}}
const requestedIds=Array.isArray(b.supplierIds)?[...new Set(b.supplierIds.map(cleanId).filter(Boolean))]:[];const unresolved=requestedIds.filter(id=>!unique.some(x=>x.id===id));
for(const id of unresolved){for(const path of [`/resto/api/v2/entities/contractors/${encodeURIComponent(id)}`,`/resto/api/v2/entities/contractors?id=${encodeURIComponent(id)}`]){const {r,rows}=await load(serverUrl,token,path);diagnostics.push({path,status:r.status,ok:r.ok,contentType:r.contentType,rawLength:r.text.length,parsedCount:rows.length,requestedId:id});const exact=rows.find(x=>cleanId(x.id)===id);if(exact){unique.push(exact);seen.add(id);break;}}}
const scope=await sha1(serverUrl.toLowerCase());const now=new Date().toISOString();if(unique.length)await env.DB.batch(unique.map(x=>env.DB.prepare(`INSERT INTO sh_iiko_suppliers(scope_id,supplier_id,supplier_name,updated_at) VALUES(?1,?2,?3,?4) ON CONFLICT(scope_id,supplier_id) DO UPDATE SET supplier_name=excluded.supplier_name,updated_at=excluded.updated_at`).bind(scope,x.id,x.name,now)));
const r=await env.DB.prepare(`SELECT supplier_id id,supplier_name name FROM sh_iiko_suppliers WHERE scope_id=?1`).bind(scope).all();const suppliers=Object.fromEntries((r.results||[]).map(x=>[cleanId(x.id),cleanName(x.name)]));const unresolvedAfter=requestedIds.filter(id=>!Object.prototype.hasOwnProperty.call(suppliers,id));return json({success:true,count:Object.keys(suppliers).length,suppliers,unresolvedSupplierIds:unresolvedAfter,diagnostics});}catch(e){return json({success:false,message:e?.message||"Ошибка загрузки поставщиков"},502);}}