function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
const clean=v=>String(v??"").trim();
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации iiko Server: HTTP ${r.status}`);return{serverUrl,token};}
async function getJson(url,options={}){const r=await fetch(url,{...options,headers:{Accept:"application/json",...(options.headers||{})},cache:"no-store"});const text=(await r.text()).trim();let payload=null;try{payload=JSON.parse(text||"{}")}catch{}return{ok:r.ok,status:r.status,text,payload};}
function extractFields(raw){const out=[];const add=(name,meta={})=>{name=clean(name);if(!name||out.some(x=>x.name.toLowerCase()===name.toLowerCase()))return;out.push({name,title:clean(meta.title||meta.caption||meta.label||meta.displayName||meta.name||name),type:clean(meta.type||meta.dataType||meta.kind||"unknown")});};if(Array.isArray(raw))for(const x of raw){if(typeof x==="string")add(x);else if(x&&typeof x==="object")add(x.technicalName||x.field||x.key||x.code||x.id||x.name,x)}else if(raw&&typeof raw==="object"){for(const key of ["fields","columns","dimensions","measures"])if(Array.isArray(raw[key]))for(const x of raw[key]){if(typeof x==="string")add(x);else if(x)add(x.technicalName||x.field||x.key||x.code||x.id||x.name,x)}}return out;}
function fieldName(fields,candidates){const norm=s=>clean(s).toLowerCase().replace(/[\s._()-]+/g,"");for(const c of candidates){const x=fields.find(f=>norm(f.name)===norm(c)||norm(f.title)===norm(c));if(x)return x.name}for(const c of candidates){const q=norm(c),x=fields.find(f=>norm(f.name).includes(q)||norm(f.title).includes(q));if(x)return x.name}return null;}
async function query(serverUrl,token,{dateField,revenueField,orderField,profitField,from,to,departmentIds}){const filters={};filters["OpenDate.Typed"]={filterType:"DateRange",periodType:"CUSTOM",from,to,includeLow:true,includeHigh:true};if(departmentIds.length)filters["Department.Id"]={filterType:"IncludeValues",values:[...new Set(departmentIds)]};filters.DeletedWithWriteoff={filterType:"IncludeValues",values:["NOT_DELETED"]};filters.OrderDeleted={filterType:"IncludeValues",values:["NOT_DELETED"]};const aggregateFields=[revenueField,...(orderField?[orderField]:[]),...(profitField?[profitField]:[])];const req={reportType:"SALES",buildSummary:true,groupByRowFields:[dateField],groupByColFields:[],aggregateFields,filters};const r=await getJson(`${serverUrl}/resto/api/v2/reports/olap?key=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(req)});if(!r.ok)return{success:false,error:`iiko OLAP HTTP ${r.status}: ${(r.payload?.message||r.payload?.error||r.text).slice(0,2000)}`,request:req,report:r.payload};return{success:true,request:req,report:r.payload};}
export function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost(context){try{const b=await context.request.json();const ip=clean(b.ip),port=clean(b.port),login=clean(b.login),password=String(b.password??"");if(!ip||!port||!login||!password)return jsonResponse({success:false,message:"Заполните IP, порт, логин и пароль iiko"},400);const from=clean(b.from).slice(0,10),to=clean(b.to||b.from).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))return jsonResponse({success:false,message:"Укажите корректный период"},400);const {serverUrl,token}=await auth(ip,port,login,password);const fr=await getJson(`${serverUrl}/resto/api/v2/reports/olap/columns?key=${encodeURIComponent(token)}&reportType=SALES`);if(!fr.ok||!fr.payload)throw new Error(`iiko OLAP columns HTTP ${fr.status}`);const fields=extractFields(fr.payload);const dateField=fieldName(fields,["OpenDate.Typed","OpenDate"]),revenueField=fieldName(fields,["DishDiscountSumInt","DishSumInt","Sales"]),orderField=fieldName(fields,["UniqOrderId","UniqOrderId.Id"]),profitField=fieldName(fields,["ProductCostBase.Profit","Profit"]);if(!dateField||!revenueField)throw new Error("Не найдены необходимые OLAP-поля");const departmentIds=Array.isArray(b.departmentIds)?b.departmentIds.map(String).filter(Boolean):[];const daily=await query(serverUrl,token,{dateField,revenueField,orderField,profitField,from,to,departmentIds});return jsonResponse({success:true,from,to,departmentIds,fields,revenueField,orderField,profitField,reports:{daily}});}catch(e){return jsonResponse({success:false,message:e?.message||"Ошибка Dashboard Summary"},502);}}
