function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return {serverUrl,token};}
function date(v){const s=String(v??"").trim();if(/^\d{2}\.\d{2}\.\d{4}$/.test(s)){const [d,m,y]=s.split('.');return `${y}-${m}-${d}`;}return s;}
async function request(serverUrl,path,token){const sep=path.includes('?')?'&':'?';const r=await fetch(`${serverUrl}${path}${sep}key=${encodeURIComponent(token)}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, text/plain, */*"}});const text=await r.text();let body=null;try{body=JSON.parse(text);}catch{}return {ok:r.ok,status:r.status,text,body};}
function list(body){if(Array.isArray(body))return body;if(Array.isArray(body?.response))return body.response;if(Array.isArray(body?.data))return body.data;if(Array.isArray(body?.documents))return body.documents;return [];}
function normalize(value){return String(value??"").trim();}
function decorate(docs,storeMap,productMap){return docs.map(d=>({...d,storeFromName:storeMap.get(normalize(d.storeFromId))||normalize(d.storeFromId)||'—',storeToName:storeMap.get(normalize(d.storeToId))||normalize(d.storeToId)||'—',storeName:storeMap.get(normalize(d.storeId))||normalize(d.storeId)||'—',items:Array.isArray(d.items)?d.items.map(i=>({...i,productName:productMap.get(normalize(i.productId))||normalize(i.productId)||'—'})):[]}));}
async function referenceMap(serverUrl,token,paths){const map=new Map();for(const path of paths){const r=await request(serverUrl,path,token);if(!r.ok)continue;for(const x of list(r.body)){const id=normalize(x.id??x.uuid??x.entityId),name=normalize(x.name??x.title??x.description);if(id&&name)map.set(id,name);}if(map.size)break;}return map;}
async function storeNames(serverUrl,token){return referenceMap(serverUrl,token,['/resto/api/corporation/stores','/resto/api/v2/entities/stores']);}
async function productNames(serverUrl,token){return referenceMap(serverUrl,token,['/resto/api/v2/entities/products/list?includeDeleted=true','/resto/api/products']);}
async function load(serverUrl,token,type,from,to){const endpoint=type==='internalTransfer'?'/resto/api/v2/documents/internalTransfer':'/resto/api/v2/documents/writeoff';const qs=new URLSearchParams({dateFrom:date(from),dateTo:date(to)});const r=await request(serverUrl,`${endpoint}?${qs}`,token);if(!r.ok)throw new Error(`${endpoint}: HTTP ${r.status}`);return {documents:list(r.body),revision:r.body?.revision??null};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request}){try{const b=await request.json();const type=String(b.type||'').trim();if(!['internalTransfer','writeoff'].includes(type))return json({success:false,message:'Неподдерживаемый тип документа'},400);const ip=String(b.ip||'').trim(),port=String(b.port||'').trim(),login=String(b.login||'').trim(),password=String(b.password||'');if(!ip||!port||!login||!password)return json({success:false,message:'Нет данных подключения к SH Server'},400);const from=String(b.from||'').trim(),to=String(b.to||'').trim();if(!from||!to)return json({success:false,message:'Укажите период'},400);if(date(to)<date(from))return json({success:false,message:'Дата «По» раньше даты «С»'},400);const {serverUrl,token}=await auth(ip,port,login,password);const result=await load(serverUrl,token,type,from,to);const stores=await storeNames(serverUrl,token);const products=await productNames(serverUrl,token);const documents=decorate(result.documents,stores,products);return json({success:true,type,from,to,count:documents.length,revision:result.revision,documents,referenceCounts:{stores:stores.size,products:products.size}});}catch(e){return json({success:false,message:e?.message||'Ошибка получения документов'},502);}}