function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return {serverUrl,token};}
function key(v){return String(v??"").trim().replace(/^\{+|\}+$/g,"").toLowerCase();}
function date(v){const s=String(v??"").trim();if(/^\d{2}\.\d{2}\.\d{4}$/.test(s)){const [d,m,y]=s.split('.');return `${y}-${m}-${d}`;}return s;}
function decode(v){return String(v??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&").trim();}
function xmlRecords(text){const out=[];const re=/<([A-Za-z][\\w:.-]*)\\b[^>]*>([\\s\\S]*?)<\\/\\1>/gi;let m;while((m=re.exec(String(text||"")))){const b=m[0];const id=(b.match(/<(?:id|uuid|entityId|storeId|productId)>([\\s\\S]*?)<\/(?:id|uuid|entityId|storeId|productId)>/i)||[])[1];const name=(b.match(/<(?:name|title|description)>([\\s\\S]*?)<\/(?:name|title|description)>/i)||[])[1];if(id&&name)out.push({id:key(decode(id)),name:decode(name)});}return out;}
async function request(serverUrl,path,token){const sep=path.includes('?')?'&':'?';const r=await fetch(`${serverUrl}${path}${sep}key=${encodeURIComponent(token)}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, text/plain, */*"}});const text=await r.text();let body=null;try{body=JSON.parse(text);}catch{}return {ok:r.ok,status:r.status,text,body};}
function list(body,text){if(Array.isArray(body))return body;if(Array.isArray(body?.response))return body.response;if(Array.isArray(body?.data))return body.data;return xmlRecords(text);}
async function referenceMap(serverUrl,token,paths){const map=new Map();for(const path of paths){const r=await request(serverUrl,path,token);for(const x of list(r.body,r.text)){const id=key(x.id??x.uuid??x.entityId),name=String(x.name??x.title??x.description??'').trim();if(id&&name)map.set(id,name);}if(map.size)break;}return map;}
async function names(serverUrl,token){return referenceMap(serverUrl,token,['/resto/api/corporation/stores','/resto/api/v2/entities/stores']);}
async function productNames(serverUrl,token){return referenceMap(serverUrl,token,['/resto/api/v2/entities/products/list?includeDeleted=true','/resto/api/products']);}
function decorate(docs,storeMap,productMap,type){return docs.map(d=>({...d,storeFromName:storeMap.get(key(d.storeFromId))||d.storeFromId||'—',storeToName:storeMap.get(key(d.storeToId))||d.storeToId||'—',storeName:storeMap.get(key(d.storeId))||d.storeId||'—',items:Array.isArray(d.items)?d.items.map(i=>({...i,productName:productMap.get(key(i.productId))||i.productId||'—'})):[]}));}
async function load(serverUrl,token,type,from,to){const endpoint=type==='internalTransfer'?'/resto/api/v2/documents/internalTransfer':'/resto/api/v2/documents/writeoff';const qs=new URLSearchParams({dateFrom:date(from),dateTo:date(to)});const r=await request(serverUrl,`${endpoint}?${qs}`,token);if(!r.ok)throw new Error(`${endpoint}: HTTP ${r.status}`);const docs=list(r.body,r.text);return {documents:docs,revision:r.body?.revision??null};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request}){try{const b=await request.json();const type=String(b.type||'').trim();if(!['internalTransfer','writeoff'].includes(type))return json({success:false,message:'Неподдерживаемый тип документа'},400);const ip=String(b.ip||'').trim(),port=String(b.port||'').trim(),login=String(b.login||'').trim(),password=String(b.password||'');if(!ip||!port||!login||!password)return json({success:false,message:'Нет данных подключения к SH Server'},400);const from=String(b.from||'').trim(),to=String(b.to||'').trim();if(!from||!to)return json({success:false,message:'Укажите период'},400);if(date(to)<date(from))return json({success:false,message:'Дата «По» раньше даты «С»'},400);const {serverUrl,token}=await auth(ip,port,login,password);const result=await load(serverUrl,token,type,from,to);const storeMap=await names(serverUrl,token);const productMap=await productNames(serverUrl,token);const documents=decorate(result.documents,storeMap,productMap,type);return json({success:true,type,from,to,count:documents.length,revision:result.revision,documents,referenceCounts:{stores:storeMap.size,products:productMap.size}});}catch(e){return json({success:false,message:e?.message||'Ошибка получения документов'},502);}}