function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return{serverUrl,token};}
function validDateTime(value,name){const s=String(value||"").trim();if(!s)return null;const d=new Date(s);if(Number.isNaN(d.getTime()))throw new Error(`Некорректная дата ${name}`);return s;}
function xmlDecode(value){return String(value??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function tag(block,name){const m=String(block||"").match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`,`i`));return m?xmlDecode(m[1].trim()):"";}
function parseAttributes(block){const out={};const re=/<attribute[^>]*>[\s\S]*?<name[^>]*>([\s\S]*?)<\/name>[\s\S]*?<value[^>]*>([\s\S]*?)<\/value>[\s\S]*?(?:<type[^>]*>([\s\S]*?)<\/type>)?[\s\S]*?<\/attribute>/gi;let m;while((m=re.exec(block))){const name=xmlDecode(m[1].trim());if(name)out[name]=xmlDecode(m[2].trim());}return out;}
function parseEvents(xml){const source=String(xml||"");const events=[];const re=/<event[^>]*>[\s\S]*?<\/event>/gi;let m;while((m=re.exec(source))){const block=m[0];events.push({id:tag(block,"id")||null,date:tag(block,"date")||null,type:tag(block,"type")||null,departmentId:tag(block,"departmentId")||null,attributes:parseAttributes(block)});}const revision=tag(source,"revision");return{events,revision:revision?Number(revision):null};}
function parseMetadata(xml){const source=String(xml||"");const result={};const blocks=[];let re=/<(?:eventType|event|item|node)[^>]*>[\s\S]*?<\/(?:eventType|event|item|node)>/gi,m;while((m=re.exec(source)))blocks.push(m[0]);const candidates=blocks.length?blocks:[source];for(const block of candidates){const id=tag(block,"id")||tag(block,"type")||tag(block,"code")||tag(block,"eventType");const name=tag(block,"name")||tag(block,"title")||tag(block,"caption")||tag(block,"description");if(id&&name&&!result[id])result[id]=name;}return result;}
async function request(serverUrl,token,path){const r=await fetch(`${serverUrl}${path}`,{cache:"no-store",headers:{Accept:"application/xml,text/xml,*/*"}});const text=await r.text();return{ok:r.ok,status:r.status,text};}
function eventContains(event,needle){if(!needle)return true;const q=String(needle).trim().toLowerCase();if(!q)return true;const values=[event.type,event.id,event.departmentId,...Object.entries(event.attributes||{}).flatMap(([k,v])=>[k,v])];return values.some(v=>String(v??"").toLowerCase().includes(q));}
function normalizeOrderNumber(value){return String(value??"").trim().replace(/\.0+$/,"" );}
function eventMatchesOrder(event,needle){const q=normalizeOrderNumber(needle);if(!q)return true;const attrs=event.attributes||{};const candidates=[];for(const [key,value] of Object.entries(attrs)){if(/order(num|number|id)?|receipt|document/i.test(key))candidates.push(normalizeOrderNumber(value));}return candidates.some(v=>v===q||v.includes(q));}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost(context){try{const b=await context.request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return jsonResponse({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const from=validDateTime(b.from,"начала периода"),to=validDateTime(b.to,"окончания периода");if(!from||!to)return jsonResponse({success:false,message:"Укажите период событий"},400);if(new Date(to)<=new Date(from))return jsonResponse({success:false,message:"Окончание периода должно быть позже начала"},400);const {serverUrl,token}=await auth(ip,port,login,password);const params=new URLSearchParams({key:token});if(b.fromRev!==undefined&&b.fromRev!==null&&String(b.fromRev).trim()!==""){const rev=Number(b.fromRev);if(!Number.isInteger(rev)||rev<0)return jsonResponse({success:false,message:"Некорректная ревизия событий"},400);params.set("from_rev",String(rev));}else{params.set("from_time",from);params.set("to_time",to);}const result=await request(serverUrl,token,`/resto/api/events?${params.toString()}`);if(!result.ok)return jsonResponse({success:false,message:`iiko Server вернул HTTP ${result.status}`,iikoHttpStatus:result.status,rawResponse:result.text.slice(0,4000)},502);const parsed=parseEvents(result.text);let metadata={};if(b.includeMetadata===true){try{const meta=await request(serverUrl,token,`/resto/api/events/metadata?key=${encodeURIComponent(token)}`);if(meta.ok)metadata=parseMetadata(meta.text);}catch{metadata={};}}
const typeFilter=String(b.type||"").trim().toLowerCase();const userFilter=String(b.user||"").trim().toLowerCase();const orderFilter=String(b.order||"").trim();const search=String(b.search||"").trim();const filtered=parsed.events.filter(event=>{if(typeFilter&&!String(event.type||"").toLowerCase().includes(typeFilter))return false;if(userFilter&&!Object.entries(event.attributes||{}).some(([k,v])=>/user(name)?/i.test(k)&&String(v).toLowerCase().includes(userFilter)))return false;if(orderFilter&&!eventMatchesOrder(event,orderFilter))return false;if(search&&!eventContains(event,search))return false;return true;});return jsonResponse({success:true,count:filtered.length,total:parsed.events.length,revision:parsed.revision,from,to,events:filtered,metadata});}catch(e){return jsonResponse({success:false,message:e?.message||"Ошибка получения журнала событий"},502);}}
