function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return{serverUrl,token};}
function validDateTime(value,name){const s=String(value||"").trim();if(!s)return null;const d=new Date(s);if(Number.isNaN(d.getTime()))throw new Error(`Некорректная дата ${name}`);return s;}
function xmlDecode(value){return String(value??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function xmlEscape(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");}
function tag(block,name){const m=String(block||"").match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`,`i`));return m?xmlDecode(m[1].trim()):"";}
function parseAttributes(block){const out={};const list=[];const re=/<attribute[^>]*>[\s\S]*?<name[^>]*>([\s\S]*?)<\/name>[\s\S]*?<value[^>]*>([\s\S]*?)<\/value>[\s\S]*?(?:<type[^>]*>([\s\S]*?)<\/type>)?[\s\S]*?<\/attribute>/gi;let m;while((m=re.exec(block))){const name=xmlDecode(m[1].trim());const value=xmlDecode(m[2].trim());const type=xmlDecode((m[3]||"").trim());if(name){out[name]=value;list.push({name,value,type});}}return{values:out,list};}
function parseEvents(xml){const source=String(xml||"");const events=[];const re=/<event[^>]*>[\s\S]*?<\/event>/gi;let m;while((m=re.exec(source))){const block=m[0],parsed=parseAttributes(block);events.push({id:tag(block,"id")||null,date:tag(block,"date")||null,type:tag(block,"type")||null,departmentId:tag(block,"departmentId")||null,attributes:parsed.values,attributeList:parsed.list});}const revision=tag(source,"revision");return{events,revision:revision?Number(revision):null};}
function parseMetadata(xml){const source=String(xml||"");const result={};const re=/<type[^>]*>[\s\S]*?<\/type>/gi;let m;while((m=re.exec(source))){const block=m[0],id=tag(block,"id"),name=tag(block,"name"),severity=tag(block,"severity");if(id)result[id]={name:name||id,severity:severity===""?null:Number(severity),attributes:parseMetadataAttributes(block)};}return result;}
function parseMetadataAttributes(block){const out=[];const re=/<attribute[^>]*>[\s\S]*?<\/attribute>/gi;let m;while((m=re.exec(block))){const a=m[0],id=tag(a,"id"),name=tag(a,"name"),type=tag(a,"type");if(id||name)out.push({id:id||null,name:name||id||"",type:type||""});}return out;}
async function request(serverUrl,path,options={}){const r=await fetch(`${serverUrl}${path}`,{cache:"no-store",...options,headers:{Accept:"application/xml,text/xml,*/*",...(options.headers||{})}});const text=await r.text();return{ok:r.ok,status:r.status,text};}
function normalize(value){return String(value??"").trim().toLowerCase();}
function attr(event,patterns){for(const[k,v]of Object.entries(event?.attributes||{})){if(patterns.some(p=>p.test(k))&&String(v??"").trim()!=='')return String(v).trim();}return"";}
function eventMatches(event,patterns,needle){if(!needle)return true;const q=normalize(needle);return normalize(attr(event,patterns)).includes(q);}
function eventMatchesOrder(event,needle){if(!needle)return true;const q=normalize(needle).replace(/\.0+$/,""),a=event.attributes||{};for(const[k,v]of Object.entries(a)){if(/order|receipt/i.test(k)){const value=normalize(v).replace(/\.0+$/,"");if(value===q||value.includes(q))return true;}}return false;}
function metadataIds(metadata){return Object.keys(metadata||{});}
function orderRequestXml(order,metadata){const ids=metadataIds(metadata);const events=ids.map(id=>`<event>${xmlEscape(id)}</event>`).join("");return `<eventsRequestData><events>${events}</events><orderNums><orderNum>${xmlEscape(order)}</orderNum></orderNums></eventsRequestData>`;}
function attachMetadata(events,metadata){return events.map(e=>({...e,metadata:metadata[e.type]||null}));}
function applyFilters(events,b){const type=normalize(b.type),user=normalize(b.user),terminal=normalize(b.terminal),order=String(b.order||"").trim(),document=String(b.document||"").trim(),shift=String(b.shift||"").trim(),severity=String(b.severity??"").trim();return events.filter(e=>{if(type&&!normalize(e.type).includes(type))return false;if(user&&!eventMatches(e,[/userName/i,/username/i,/employeeName/i,/waiterName/i,/login/i],user))return false;if(terminal&&!eventMatches(e,[/terminal(name|address|ip|host)?/i,/computer(name|address)?/i,/machine(name|address)?/i,/host(name|address)?/i],terminal))return false;if(order&&!eventMatchesOrder(e,order))return false;if(document&&!eventMatches(e,[/document|invoice|наклад/i],document))return false;if(shift&&!eventMatches(e,[/shift|session/i],shift))return false;if(severity&&String(e.metadata?.severity??"")!==severity)return false;return true;});}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost(context){try{const b=await context.request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return jsonResponse({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const from=validDateTime(b.from,"начала периода"),to=validDateTime(b.to,"окончания периода");if(!from||!to)return jsonResponse({success:false,message:"Укажите период событий"},400);if(new Date(to)<=new Date(from))return jsonResponse({success:false,message:"Окончание периода должно быть позже начала"},400);const {serverUrl,token}=await auth(ip,port,login,password);
let metadata={};const needMetadata=b.includeMetadata===true||String(b.order||"").trim()!=="";if(needMetadata){try{const meta=await request(serverUrl,`/resto/api/events/metadata?key=${encodeURIComponent(token)}`);if(meta.ok)metadata=parseMetadata(meta.text);}catch{metadata={};}}
let result;const order=String(b.order||"").trim();if(order){const body=orderRequestXml(order,metadata);result=await request(serverUrl,`/resto/api/events?key=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/xml"},body});}else{const params=new URLSearchParams({key:token,from_time:from,to_time:to});result=await request(serverUrl,`/resto/api/events?${params.toString()}`);}
if(!result.ok)return jsonResponse({success:false,message:`iiko Server вернул HTTP ${result.status}`,iikoHttpStatus:result.status,rawResponse:result.text.slice(0,4000)},502);const parsed=parseEvents(result.text);let events=attachMetadata(parsed.events,metadata);events=applyFilters(events,b);return jsonResponse({success:true,count:events.length,total:parsed.events.length,revision:parsed.revision,from,to,events,metadata});
}catch(e){return jsonResponse({success:false,message:e?.message||"Ошибка получения журнала событий"},502);}}
