function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return{serverUrl,token};}
async function getJson(url){const r=await fetch(url,{headers:{Accept:"application/json"},cache:"no-store"});const text=(await r.text()).trim();let payload=null;try{payload=JSON.parse(text||"[]")}catch{}return{ok:r.ok,status:r.status,text,payload};}
function parseDate(v){const m=String(v||"").trim().match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return null;const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));return d.getUTCFullYear()===+m[1]&&d.getUTCMonth()===+m[2]-1&&d.getUTCDate()===+m[3]?d:null;}
function iso(d){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;}
function extractList(p){if(Array.isArray(p))return p;for(const k of ["items","sessions","cashShifts","cashSessions","data","rows"])if(Array.isArray(p?.[k]))return p[k];return[];}
function sid(x){return String(x?.id??x?.sessionId??x?.sessionID??x?.uuid??x?.UUID??"").trim();}
function shiftDate(x,f){for(const k of ["businessDate","operatingDay","operationalDay","date","openDate","openedAt","openTime","startDate","startTime"]){const v=x?.[k];const m=String(v??"").match(/(\d{4})[-.](\d{2})[-.](\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;}return f;}
function normalizeShift(x,date,status){return x&&typeof x==="object"?{...x,_sessionId:sid(x),_dateKey:shiftDate(x,date),_requestedStatus:status}:null;}
async function shiftsFor(serverUrl,token,date,status){const key=encodeURIComponent(token),d=encodeURIComponent(date),s=encodeURIComponent(status);const a=await getJson(`${serverUrl}/resto/api/v2/cashshifts/list?key=${key}&date=${d}&status=${s}`);if(a.ok)return{ok:true,shifts:extractList(a.payload).map(x=>normalizeShift(x,date,status)).filter(Boolean)};const b=await getJson(`${serverUrl}/resto/api/v2/cashshifts/list?key=${key}&openDateFrom=${d}&openDateTo=${d}&status=${s}`);if(b.ok)return{ok:true,shifts:extractList(b.payload).map(x=>normalizeShift(x,date,status)).filter(Boolean)};return{ok:false,error:{date,status,httpStatus:a.status,fallbackStatus:b.status,message:(a.text||"").slice(0,500)}};}
function recordsFrom(p){if(!p||typeof p!=="object")return[];const groups=[["CARD",p.cashlessRecords],["PAYIN",p.payInRecords],["PAYOUT",p.payOutRecords||p.payOuts]];const out=[];for(const [fallback,list] of groups)if(Array.isArray(list))for(const r of list){const i=r?.info||{};out.push({id:i.id??r.id??null,group:i.group??r.group??fallback,sum:i.sum??r.sum??r.actualSum??r.originalSum??null,actualSum:r.actualSum??null,originalSum:r.originalSum??i.sum??null,accountId:i.accountId??r.accountId??r.editedPayAccountId??r.originalPayAccountId??null,counteragentId:i.counteragentId??r.counteragentId??null,paymentTypeId:i.paymentTypeId??r.paymentTypeId??null,type:i.type??r.type??null,cashierId:i.cashierId??r.cashierId??null,date:i.date??r.date??null,creationDate:i.creationDate??r.creationDate??null,comment:i.comment??r.comment??r.editableComment??"",status:r.status??i.status??null});}return out;}
async function detail(serverUrl,token,id){const key=encodeURIComponent(token),sidv=encodeURIComponent(id);const a=await getJson(`${serverUrl}/resto/api/v2/cashshifts/byId/${sidv}?key=${key}`);if(!a.ok||!a.payload||typeof a.payload!=="object")return{success:false,sessionId:id,message:`Не удалось получить смену: HTTP ${a.status}`};const b=await getJson(`${serverUrl}/resto/api/v2/cashshifts/payments/list/${sidv}?key=${key}&hideAccepted=false`);const p=b.payload&&typeof b.payload==="object"?b.payload:{};return{success:true,sessionId:id,shift:a.payload,payments:recordsFrom(p),paymentsLoaded:b.ok,paymentsStatus:b.status,operationDay:p.operationDay||null};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost(context){try{const b=await context.request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return jsonResponse({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const {serverUrl,token}=await auth(ip,port,login,password);const mode=String(b.mode||"list").toLowerCase();if(mode==="details"){const ids=Array.isArray(b.sessionIds)?b.sessionIds.map(x=>String(x||"").trim()).filter(Boolean):[];if(!ids.length)return jsonResponse({success:false,message:"Не указаны ID кассовых смен"},400);if(ids.length>15)return jsonResponse({success:false,message:"За один запрос можно получить детали максимум для 15 смен"},400);const results=await Promise.all(ids.map(id=>detail(serverUrl,token,id)));return jsonResponse({success:true,mode,details:results});}const from=parseDate(b.from),to=parseDate(b.to);if(!from||!to)return jsonResponse({success:false,message:"Укажите корректный период дат"},400);if(to<from)return jsonResponse({success:false,message:"Дата окончания не может быть раньше даты начала"},400);const days=Math.round((to-from)/86400000)+1;if(days>5)return jsonResponse({success:false,message:"Оптимизированный запрос кассовых смен ограничен 5 днями"},400);const all=[],errors=[];for(let i=0;i<days;i++){const date=iso(new Date(from.getTime()+i*86400000));for(const status of ["OPEN","CLOSED"]){const r=await shiftsFor(serverUrl,token,date,status);if(r.ok)all.push(...r.shifts);else errors.push(r.error);}}const seen=new Set();const shifts=all.filter(x=>{const id=x._sessionId||JSON.stringify(x);if(seen.has(id))return false;seen.add(id);return true;});return jsonResponse({success:true,mode:"list",from:b.from,to:b.to,count:shifts.length,shifts,errors,endpoint:"/resto/api/v2/cashshifts/list"});}catch(e){return jsonResponse({success:false,message:e?.message||"Ошибка получения финансовых данных"},502);}}
