import { clean, iikoJson } from './_lib/iiko-client.js';

function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}});}
function parseDate(v){const m=String(v||"").trim().match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return null;const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));return d.getUTCFullYear()===+m[1]&&d.getUTCMonth()===+m[2]-1&&d.getUTCDate()===+m[3]?d:null;}
function iso(d){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;}
function extractList(p){if(Array.isArray(p))return p;for(const k of ["items","sessions","cashShifts","cashSessions","data","rows"])if(Array.isArray(p?.[k]))return p[k];return[];}
function sid(x){return String(x?.id??x?.sessionId??x?.sessionID??x?.uuid??x?.UUID??"").trim();}
function shiftDate(x,f){for(const k of ["businessDate","operatingDay","operationalDay","date","openDate","openedAt","openTime","startDate","startTime"]){const v=x?.[k];const m=String(v??"").match(/(\d{4})[-.](\d{2})[-.](\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;}return f;}
function normalizeShift(x,date,status){return x&&typeof x==="object"?{...x,_sessionId:sid(x),_dateKey:shiftDate(x,date),_requestedStatus:status}:null;}
function shiftDepartmentId(x){for(const v of[x?.departmentId,x?.departmentID,x?.department?.id,x?.department?.uuid,x?.department?.guid,x?.departmentGuid]){const s=String(v??"").trim();if(s)return s}return"";}
function recordsFrom(p){if(!p||typeof p!=="object")return[];const groups=[["CARD",p.cashlessRecords],["PAYIN",p.payInRecords],["PAYOUT",p.payOutRecords||p.payOuts]];const out=[];for(const [fallback,list] of groups)if(Array.isArray(list))for(const r of list){const i=r?.info||{};out.push({id:i.id??r.id??null,group:i.group??r.group??fallback,sum:i.sum??r.sum??r.actualSum??r.originalSum??null,actualSum:r.actualSum??null,originalSum:r.originalSum??i.sum??null,accountId:i.accountId??r.accountId??r.editedPayAccountId??r.originalPayAccountId??null,counteragentId:i.counteragentId??r.counteragentId??null,paymentTypeId:i.paymentTypeId??r.paymentTypeId??null,type:i.type??r.type??null,cashierId:i.cashierId??r.cashierId??null,date:i.date??r.date??null,creationDate:i.creationDate??r.creationDate??null,comment:i.comment??r.comment??r.editableComment??"",status:r.status??i.status??null});}return out;}
async function mapLimit(items,limit,worker){const result=new Array(items.length);let cursor=0;async function run(){while(true){const i=cursor++;if(i>=items.length)return;result[i]=await worker(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return result;}
async function shiftsFor(connection,date,status){const d=encodeURIComponent(date),s=encodeURIComponent(status);const a=await iikoJson(connection,`/resto/api/v2/cashshifts/list?date=${d}&status=${s}`);if(a.ok)return{ok:true,shifts:extractList(a.payload).map(x=>normalizeShift(x,date,status)).filter(Boolean),authCacheHit:Boolean(a.auth?.cacheHit)};const b=await iikoJson(connection,`/resto/api/v2/cashshifts/list?openDateFrom=${d}&openDateTo=${d}&status=${s}`);if(b.ok)return{ok:true,shifts:extractList(b.payload).map(x=>normalizeShift(x,date,status)).filter(Boolean),authCacheHit:Boolean(b.auth?.cacheHit),fallback:true};return{ok:false,error:{date,status,httpStatus:a.status,fallbackStatus:b.status,message:(a.text||"").slice(0,500)}};}
async function detail(connection,id){const sidv=encodeURIComponent(id);const [a,b]=await Promise.all([iikoJson(connection,`/resto/api/v2/cashshifts/byId/${sidv}`),iikoJson(connection,`/resto/api/v2/cashshifts/payments/list/${sidv}?hideAccepted=false`)]);if(!a.ok||!a.payload||typeof a.payload!=="object")return{success:false,sessionId:id,message:`Не удалось получить смену: HTTP ${a.status}`};const p=b.payload&&typeof b.payload==="object"?b.payload:{};return{success:true,sessionId:id,shift:a.payload,payments:recordsFrom(p),paymentsLoaded:b.ok,paymentsStatus:b.status,operationDay:p.operationDay||null};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost(context){try{const b=await context.request.json();const connection={ip:clean(b.ip),port:clean(b.port),login:clean(b.login),password:String(b.password||"")};if(!connection.ip||!connection.port||!connection.login||!connection.password)return jsonResponse({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const departmentIds=Array.isArray(b.departmentIds)?[...new Set(b.departmentIds.map(String).filter(Boolean))]:[];const mode=String(b.mode||"list").toLowerCase();if(mode==="details"){const ids=Array.isArray(b.sessionIds)?[...new Set(b.sessionIds.map(x=>String(x||"").trim()).filter(Boolean))]:[];if(!ids.length)return jsonResponse({success:false,message:"Не указаны ID кассовых смен"},400);if(ids.length>60)return jsonResponse({success:false,message:"За один запрос можно получить детали максимум для 60 смен"},400);const results=await mapLimit(ids,6,id=>detail(connection,id));return jsonResponse({success:true,mode,details:results,meta:{requested:ids.length,concurrency:6,departmentIds}});}const from=parseDate(b.from),to=parseDate(b.to);if(!from||!to)return jsonResponse({success:false,message:"Укажите корректный период дат"},400);if(to<from)return jsonResponse({success:false,message:"Дата окончания не может быть раньше даты начала"},400);const days=Math.round((to-from)/86400000)+1;if(days>62)return jsonResponse({success:false,message:"Период кассовых смен ограничен 62 днями за один запрос"},400);const tasks=[];for(let i=0;i<days;i++){const date=iso(new Date(from.getTime()+i*86400000));for(const status of["OPEN","CLOSED"])tasks.push({date,status});}const results=await mapLimit(tasks,6,x=>shiftsFor(connection,x.date,x.status));const all=[],errors=[];for(const r of results){if(r.ok)all.push(...r.shifts);else errors.push(r.error)}const seen=new Set();let shifts=all.filter(x=>{const id=x._sessionId||JSON.stringify(x);if(seen.has(id))return false;seen.add(id);return true;});const detectedDepartmentIds=[...new Set(shifts.map(shiftDepartmentId).filter(Boolean))];let departmentScopeApplied=false;if(departmentIds.length&&detectedDepartmentIds.length){const wanted=new Set(departmentIds);shifts=shifts.filter(x=>wanted.has(shiftDepartmentId(x)));departmentScopeApplied=true;}return jsonResponse({success:true,mode:"list",from:b.from,to:b.to,count:shifts.length,shifts,errors,endpoint:"/resto/api/v2/cashshifts/list",meta:{days,requestPairs:tasks.length,concurrency:6,departmentIds,detectedDepartmentIds,departmentScopeApplied}});}catch(e){return jsonResponse({success:false,message:e?.message||"Ошибка получения финансовых данных"},502);}}
