function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};}
function jsonResponse(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...corsHeaders()}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function clean(v){return String(v??"").trim();}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации iiko Server: HTTP ${r.status}`);return{serverUrl,token};}
async function getJson(url,options={}){const r=await fetch(url,{...options,cache:"no-store",headers:{Accept:"application/json",...(options.headers||{})}});const text=(await r.text()).trim();let payload=null;try{payload=JSON.parse(text||"{}");}catch{}return{ok:r.ok,status:r.status,text,payload};}
function extractFields(raw){const out=[];const add=(name,meta={})=>{name=clean(name);if(!name)return;const key=name.toLowerCase();if(out.some(x=>x.name.toLowerCase()===key))return;out.push({name,title:clean(meta.title||meta.caption||meta.label||meta.displayName||meta.name||name),type:clean(meta.type||meta.dataType||meta.kind||"unknown")});};if(Array.isArray(raw))for(const x of raw){if(typeof x==="string")add(x);else if(x&&typeof x==="object")add(x.technicalName||x.field||x.key||x.code||x.id||x.name,x);}else if(raw&&typeof raw==="object"){for(const key of ["fields","columns","dimensions","measures"]){if(Array.isArray(raw[key]))for(const x of raw[key]){if(typeof x==="string")add(x);else if(x)add(x.technicalName||x.field||x.key||x.code||x.id||x.name,x);}}}return out;}
function fieldName(fields,candidates){const norm=s=>clean(s).toLowerCase().replace(/[\s._()-]+/g,"");for(const c of candidates){const x=fields.find(f=>norm(f.name)===norm(c)||norm(f.title)===norm(c));if(x)return x.name;}for(const c of candidates){const q=norm(c);const x=fields.find(f=>norm(f.name).includes(q)||norm(f.title).includes(q));if(x)return x.name;}return null;}
function buildRequest({rows,measure,from,to}){return{reportType:"SALES",buildSummary:true,groupByRowFields:rows,groupByColFields:[],aggregateFields:[measure],filters:{"OpenDate.Typed":{filterType:"DateRange",periodType:"CUSTOM",from,to,includeLow:true,includeHigh:true},DeletedWithWriteoff:{filterType:"IncludeValues",values:["NOT_DELETED"]},OrderDeleted:{filterType:"IncludeValues",values:["NOT_DELETED"]}}};}
function number(v){if(typeof v==="number")return v;return Number.parseFloat(String(v??"").replace(",","."))||0;}
async function query(serverUrl,token,request){const r=await getJson(`${serverUrl}/resto/api/v2/reports/olap?key=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)});if(!r.ok)return{success:false,error:`iiko OLAP HTTP ${r.status}: ${(r.payload?.message||r.payload?.error||r.text).slice(0,2000)}`};return{success:true,report:r.payload};}
function rowsFromReport(report){return report&&Array.isArray(report.data)?report.data:[];}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost(context){try{const b=await context.request.json();const ip=clean(b.ip),port=clean(b.port),login=clean(b.login),password=String(b.password??"");if(!ip||!port||!login||!password)return jsonResponse({success:false,message:"Заполните IP, порт, логин и пароль iiko"},400);const from=clean(b.from).slice(0,10),to=clean(b.to||b.from).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))return jsonResponse({success:false,message:"Укажите корректный период"},400);const {serverUrl,token}=await auth(ip,port,login,password);const columns=await getJson(`${serverUrl}/resto/api/v2/reports/olap/columns?key=${encodeURIComponent(token)}&reportType=SALES`);if(!columns.ok||!columns.payload)return jsonResponse({success:false,message:`iiko OLAP columns HTTP ${columns.status}`},502);const fields=extractFields(columns.payload);const dateField=fieldName(fields,["OpenDate.Typed","OpenDate"]);const orderField=fieldName(fields,["OrderNum","OrderNumber","Order.Number","OrderNum.Id","OrderId","Order.Id"]);const tableField=fieldName(fields,["TableName","Table.Name","Table"]);const waiterField=fieldName(fields,["WaiterName","Waiter.Name","EmployeeName","Waiter"]);const statusField=fieldName(fields,["OrderStatus","Order.Status","Status"]);const revenueField=fieldName(fields,["DishDiscountSumInt","DishSumInt","Sales"]);if(!dateField||!revenueField)return jsonResponse({success:false,message:"Не найдены необходимые OLAP-поля заказа",fields},502);if(!orderField){return jsonResponse({success:true,available:false,from,to,orders:[],summary:{orders:0,revenue:0},message:"В iiko не найдено поле номера заказа для списка заказов",fields});}const rows=[orderField,dateField];if(tableField)rows.push(tableField);if(waiterField)rows.push(waiterField);if(statusField)rows.push(statusField);const result=await query(serverUrl,token,buildRequest({rows,measure:revenueField,from,to}));if(!result.success)return jsonResponse({success:false,message:result.error,fields},502);const orders=rowsFromReport(result.report).map((raw,index)=>{const orderNumber=clean(raw[orderField]??raw.OrderNum??raw.OrderNumber)||`#${index+1}`;return{number:orderNumber,date:clean(raw[dateField]??raw.OpenDate),table:tableField?clean(raw[tableField]):"",waiter:waiterField?clean(raw[waiterField]):"",status:statusField?clean(raw[statusField]):"",amount:number(raw[revenueField]??raw.DishSumInt??raw.DishDiscountSumInt)};}).filter(x=>x.number);const revenue=orders.reduce((sum,x)=>sum+x.amount,0);return jsonResponse({success:true,available:true,from,to,orders,summary:{orders:orders.length,revenue},fields:{orderField,dateField,tableField,waiterField,statusField,revenueField}});}catch(e){return jsonResponse({success:false,message:e?.message||"Ошибка получения заказов"},502);}}
