const HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const SUPABASE_URL="https://izytdfkdpbhmyuizuuut.supabase.co";
const SUPABASE_KEY="sb_publishable_OODMzFTaHq6DIoorXb85nQ_2FfwBXAS";
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:HEADERS})}
async function user(request,env){const a=request.headers.get("Authorization")||"";if(!a.startsWith("Bearer "))return null;const token=a.slice(7).trim();if(!token)return null;const r=await fetch(`${env.SUPABASE_URL||SUPABASE_URL}/auth/v1/user`,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY||SUPABASE_KEY,Authorization:`Bearer ${token}`,Accept:"application/json"}});if(!r.ok)return null;const u=await r.json();return u?.id?u:null}
async function table(db){await db.prepare(`CREATE TABLE IF NOT EXISTS sh_pnl_account_mapping (scope_id TEXT NOT NULL, account_id TEXT NOT NULL, account_name TEXT NOT NULL DEFAULT '', account_type TEXT NOT NULL DEFAULT '', pnl_category TEXT NOT NULL DEFAULT 'UNCLASSIFIED', updated_at TEXT NOT NULL, PRIMARY KEY(scope_id,account_id))`).run()}
function clean(v){return String(v??'').trim()}
const allowed=new Set(['REVENUE','COGS','OPEX','OTHER_INCOME','OTHER_EXPENSE','EXCLUDED','UNCLASSIFIED']);
export async function onRequestOptions(){return new Response(null,{status:204,headers:HEADERS})}
export async function onRequestGet({request,env}){try{if(!env.DB)return json({success:false,message:'D1 binding DB не настроен.'},503);const u=await user(request,env);if(!u)return json({success:false,message:'Необходима авторизация.'},401);await table(env.DB);const scope=clean(new URL(request.url).searchParams.get('scope'));if(!scope)return json({success:false,message:'Не указан scope.'},400);const r=await env.DB.prepare(`SELECT account_id,account_name,account_type,pnl_category,updated_at FROM sh_pnl_account_mapping WHERE scope_id=?1 ORDER BY account_name`).bind(scope).all();return json({success:true,mappings:r.results||[]})}catch(e){return json({success:false,message:e?.message||'Ошибка загрузки классификации.'},500)}}
export async function onRequestPost({request,env}){try{if(!env.DB)return json({success:false,message:'D1 binding DB не настроен.'},503);const u=await user(request,env);if(!u)return json({success:false,message:'Необходима авторизация.'},401);const b=await request.json();const scope=clean(b.scope),items=Array.isArray(b.mappings)?b.mappings:[];if(!scope)return json({success:false,message:'Не указан scope.'},400);if(items.length>1000)return json({success:false,message:'Слишком много счетов.'},413);await table(env.DB);const now=new Date().toISOString();const statements=[];for(const x of items){const id=clean(x.account_id);if(!id)continue;const category=allowed.has(clean(x.pnl_category).toUpperCase())?clean(x.pnl_category).toUpperCase():'UNCLASSIFIED';statements.push(env.DB.prepare(`INSERT INTO sh_pnl_account_mapping(scope_id,account_id,account_name,account_type,pnl_category,updated_at) VALUES(?1,?2,?3,?4,?5,?6) ON CONFLICT(scope_id,account_id) DO UPDATE SET account_name=excluded.account_name,account_type=excluded.account_type,pnl_category=excluded.pnl_category,updated_at=excluded.updated_at`).bind(scope,id,clean(x.account_name),clean(x.account_type),category,now))}for(let i=0;i<statements.length;i+=80)await env.DB.batch(statements.slice(i,i+80));return json({success:true,saved:statements.length,updatedAt:now})}catch(e){return json({success:false,message:e?.message||'Ошибка сохранения классификации.'},500)}}