function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return {serverUrl,token};}
function xmlDecode(v){return String(v??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function localName(name){return String(name||"").split(":").pop().toLowerCase();}
function cleanId(v){return String(v??"").trim().replace(/^\{+|\}+$/g,"").toLowerCase();}
function cleanName(v){return String(v??"").replace(/<[^>]*>/g,"").trim();}
function textTag(block,names){const wanted=new Set((Array.isArray(names)?names:[names]).map(localName));const re=/<([A-Za-z][\w:.-]*)\b[^>]*>([\s\S]*?)<\/\1>/gi;let m;while((m=re.exec(String(block||""))))if(wanted.has(localName(m[1])))return xmlDecode(m[2].trim());return "";}
function elementBlocks(source,names){const wanted=new Set((Array.isArray(names)?names:[names]).map(localName));const text=String(source||"");const out=[];const open=/<([A-Za-z][\w:.-]*)\b[^>]*>/gi;let m;while((m=open.exec(text))){const fullName=m[1];if(!wanted.has(localName(fullName)))continue;const esc=fullName.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const close=new RegExp(`</${esc}>`,'ig');const tail=text.slice(open.lastIndex);const cm=close.exec(tail);if(cm)out.push(text.slice(m.index,open.lastIndex+cm.index+cm[0].length));}return out;}
function openingAttrs(block){const m=String(block||"").match(/^<([A-Za-z][\w:.-]*)\b([^>]*)>/i);const a={};if(!m)return a;const re=/([A-Za-z][\w:.-]*)\s*=\s*(["'])(.*?)\2/g;let q;while((q=re.exec(m[2])))a[localName(q[1])]=xmlDecode(q[3]);return a;}
function innerText(block){return xmlDecode(String(block||"").replace(/^<[A-Za-z][\w:.-]*\b[^>]*>/i,"").replace(/<\/[A-Za-z][\w:.-]*>\s*$/i,"").trim());}
function parseJsonSupplierRefs(value,out){if(Array.isArray(value)){for(const x of value)parseJsonSupplierRefs(x,out);return;}if(!value||typeof value!=="object")return;const name=value.name??value.title??value.description??value.fullName;const supplier=value.supplier;if(supplier&&typeof supplier==="object"){const sid=supplier.id??supplier.uuid??supplier.entityId??supplier.supplierId;const sn=supplier.name??supplier.title??supplier.description??supplier.fullName;if(sid&&(sn||name))out.push({id:sid,name:sn||name});}else if(typeof supplier==="string"&&name){out.push({id:supplier,name});}const id=value.supplierId??value.supplier_id??value.id??value.uuid??value.entityId;if(id&&name)out.push({id,name});for(const v of Object.values(value))if(v&&typeof v==="object")parseJsonSupplierRefs(v,out);}
function parseSupplierList(value){const source=String(value||"").trim();const result=[];const seen=new Set();const add=(id,name)=>{const sid=cleanId(id),sname=cleanName(name);if(sid&&sname&&!seen.has(sid)){seen.add(sid);result.push({id:sid,name:sname});}};if(!source)return result;
if(source[0]==="{"||source[0]==="["){try{const raw=[];parseJsonSupplierRefs(JSON.parse(source),raw);for(const x of raw)add(x.id,x.name);if(result.length)return result;}catch{}}
const attrs=/<([A-Za-z][\w:.-]*)\b([^>]*)>/gi;let m;while((m=attrs.exec(source))){const n=localName(m[1]);if(!["supplier","supplierdto","employee","employeedto"].includes(n))continue;const a={};const ar=/([A-Za-z][\w:.-]*)\s*=\s*(["'])(.*?)\2/g;let q;while((q=ar.exec(m[2])))a[localName(q[1])]=xmlDecode(q[3]);if(n.startsWith("supplier"))add(a.supplierid||a.id||a.uuid||a.entityid,a.name||a.title||a.description);else if(n.startsWith("employee")){const employeeId=a.id||a.uuid||a.entityid;const employeeName=a.name||a.title||a.description||a.fullname;const supplierId=a.supplierid||a.supplier_id||a.supplieruuid||a.supplier;add(supplierId,employeeName);if(employeeId)add(employeeId,employeeName);}}
for(const b of elementBlocks(source,["supplier","supplierDto"])){const a=openingAttrs(b);const id=textTag(b,["id","uuid","entityId","supplierId","supplier_id"])||a.supplierid||a.id;const name=textTag(b,["name","title","description","fullName"])||a.name||a.title;if(id&&name)add(id,name);}
for(const b of elementBlocks(source,["employee","employeeDto","employeeDTO"])){const a=openingAttrs(b);const employeeName=textTag(b,["name","title","description","fullName"])||a.name||a.title||a.description||a.fullname;const employeeId=textTag(b,["id","uuid","entityId"])||a.id||a.uuid||a.entityid;const supplierValue=textTag(b,["supplierId","supplier_id"])||a.supplierid||a.supplier_id||a.supplieruuid;const supplierText=elementBlocks(b,["supplier","supplierDto"]);const supplierIds=[];if(a.supplier)supplierIds.push(a.supplier);for(const sb of supplierText){const sa=openingAttrs(sb);const sid=textTag(sb,["id","uuid","entityId","supplierId","supplier_id"])||sa.id||sa.uuid||sa.entityid||sa.supplierid||innerText(sb);const sn=textTag(sb,["name","title","description","fullName"])||sa.name||sa.title||employeeName;if(sid){supplierIds.push(sid);if(sn)add(sid,sn);}}if(supplierValue)supplierIds.push(supplierValue);if(employeeName){if(employeeId)add(employeeId,employeeName);for(const sid of supplierIds)add(sid,employeeName);}}
return result;}
function parseReferenceList(value){const source=String(value||"").trim();const result=[];const seen=new Set();const add=(id,name)=>{const sid=cleanId(id),sname=cleanName(name);if(sid&&sname&&!seen.has(sid)){seen.add(sid);result.push({id:sid,name:sname});}};if(!source)return result;if(source[0]==="{"||source[0]==="["){try{const walk=v=>{if(Array.isArray(v)){v.forEach(walk);return;}if(!v||typeof v!=="object")return;const id=v.id??v.uuid??v.entityId??v.storeId??v.warehouseId??v.productId;const name=v.name??v.title??v.description;if(id&&name)add(id,name);Object.values(v).forEach(x=>{if(x&&typeof x==="object")walk(x);});};walk(JSON.parse(source));if(result.length)return result;}catch{}}
const re=/<([A-Za-z][\w:.-]*)\b([^>]*)>/gi;let m;while((m=re.exec(source))){const n=localName(m[1]);if(!["store","storedto","warehouse","department","product","productdto","entity","entitydto","corporateitemdto","item"].includes(n))continue;const a={};const ar=/([A-Za-z][\w:.-]*)\s*=\s*(["'])(.*?)\2/g;let q;while((q=ar.exec(m[2])))a[localName(q[1])]=xmlDecode(q[3]);add(a.id||a.uuid||a.entityid||a.storeid||a.warehouseid||a.productid,a.name||a.title||a.description);}
for(const b of elementBlocks(source,["store","storeDto","warehouse","department","product","productDto","entity","entityDto","corporateItemDto","item"])){const a=openingAttrs(b);add(textTag(b,["id","uuid","entityId","storeId","warehouseId","productId"])||a.id||a.uuid||a.entityid||a.storeid||a.warehouseid||a.productid,textTag(b,["name","title","description"])||a.name||a.title||a.description);}return result;}
async function request(serverUrl,path,token){const r=await fetch(`${serverUrl}${path}${path.includes("?")?"&":"?"}key=${encodeURIComponent(token)}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, */*"}});return {ok:r.ok,status:r.status,text:await r.text(),contentType:r.headers.get("content-type")||""};}
async function ensure(db){if(!db)throw new Error("D1 binding DB не настроен");await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_suppliers (scope_id TEXT NOT NULL,supplier_id TEXT NOT NULL,supplier_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,supplier_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_warehouses (scope_id TEXT NOT NULL,warehouse_id TEXT NOT NULL,warehouse_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,warehouse_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_products (scope_id TEXT NOT NULL,product_id TEXT NOT NULL,product_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,product_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_product_groups (scope_id TEXT NOT NULL,group_id TEXT NOT NULL,group_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,group_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_product_categories (scope_id TEXT NOT NULL,category_id TEXT NOT NULL,category_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,category_id))`)]);}
async function readMap(db,table,idCol,nameCol,scope){const r=await db.prepare(`SELECT ${idCol} id,${nameCol} name FROM ${table} WHERE scope_id=?1`).bind(scope).all();return new Map((r.results||[]).filter(x=>x?.id&&x?.name).map(x=>[cleanId(x.id),cleanName(x.name)]));}
async function save(db,table,idCol,nameCol,scope,rows){if(!rows.length)return;const now=new Date().toISOString();for(let i=0;i<rows.length;i+=50)await db.batch(rows.slice(i,i+50).map(x=>db.prepare(`INSERT INTO ${table}(scope_id,${idCol},${nameCol},updated_at) VALUES(?1,?2,?3,?4) ON CONFLICT(scope_id,${idCol}) DO UPDATE SET ${nameCol}=excluded.${nameCol},updated_at=excluded.updated_at`).bind(scope,cleanId(x.id),cleanName(x.name),now)));}
async function loadRef(serverUrl,token,paths,parser){const all=[];const diagnostics=[];for(const path of paths){try{const r=await request(serverUrl,path,token);const rows=r.ok?parser(r.text):[];diagnostics.push({path,status:r.status,ok:r.ok,contentType:r.contentType,rawLength:r.text.length,parsedCount:rows.length});if(r.ok&&rows.length)all.push(...rows);}catch(e){diagnostics.push({path,status:0,ok:false,contentType:"",rawLength:0,parsedCount:0,error:String(e?.message||e)});}}const seen=new Set();const rows=all.filter(x=>{const id=cleanId(x.id);if(!id||seen.has(id))return false;seen.add(id);return true;});const last=diagnostics[diagnostics.length-1]||{};return {rows,status:diagnostics.find(x=>x.parsedCount>0)?.status||last.status||0,contentType:last.contentType||"",rawLength:diagnostics.reduce((s,x)=>s+Number(x.rawLength||0),0),path:paths.join(" + "),error:rows.length?null:diagnostics.map(x=>`${x.path}: HTTP ${x.status}`).join("; "),attempts:diagnostics};}
async function syncReferences(env,serverUrl,token){await ensure(env.DB);const scope=await sha1(serverUrl.toLowerCase());const refs={};refs.suppliers=await loadRef(serverUrl,token,["/resto/api/v2/entities/contractors","/resto/api/suppliers","/resto/api/corporation/suppliers"],parseSupplierList);refs.warehouses=await loadRef(serverUrl,token,["/resto/api/corporation/stores"],parseReferenceList);refs.products=await loadRef(serverUrl,token,["/resto/api/v2/entities/products/list?includeDeleted=true","/resto/api/products"],parseReferenceList);refs.groups=await loadRef(serverUrl,token,["/resto/api/v2/entities/products/group/list?includeDeleted=true"],parseReferenceList);refs.categories=await loadRef(serverUrl,token,["/resto/api/v2/entities/products/category/list?includeDeleted=true"],parseReferenceList);await Promise.all([save(env.DB,"sh_iiko_suppliers","supplier_id","supplier_name",scope,refs.suppliers.rows),save(env.DB,"sh_iiko_warehouses","warehouse_id","warehouse_name",scope,refs.warehouses.rows),save(env.DB,"sh_iiko_products","product_id","product_name",scope,refs.products.rows),save(env.DB,"sh_iiko_product_groups","group_id","group_name",scope,refs.groups.rows),save(env.DB,"sh_iiko_product_categories","category_id","category_name",scope,refs.categories.rows)]);const maps={suppliers:await readMap(env.DB,"sh_iiko_suppliers","supplier_id","supplier_name",scope),warehouses:await readMap(env.DB,"sh_iiko_warehouses","warehouse_id","warehouse_name",scope),products:await readMap(env.DB,"sh_iiko_products","product_id","product_name",scope),groups:await readMap(env.DB,"sh_iiko_product_groups","group_id","group_name",scope),categories:await readMap(env.DB,"sh_iiko_product_categories","category_id","category_name",scope)};return {maps,diagnostics:Object.fromEntries(Object.entries(refs).map(([k,v])=>[k,{httpStatus:v.status,contentType:v.contentType,rawLength:v.rawLength,parsedCount:v.rows.length,path:v.path,error:v.error||null,attempts:v.attempts||[]}]))};}
export {syncReferences};
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request,env}){try{const b=await request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return json({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const {serverUrl,token}=await auth(ip,port,login,password);const refs=await syncReferences(env,serverUrl,token);return json({success:true,source:"iiko-sync+d1",supplierCount:refs.maps.suppliers.size,warehouseCount:refs.maps.warehouses.size,productCount:refs.maps.products.size,diagnostics:refs.diagnostics});}catch(e){return json({success:false,message:e?.message||"Ошибка загрузки справочников iiko"},502);}}