function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Content-Type":"application/json; charset=utf-8"};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(),"Cache-Control":"no-store"}});}
async function sha1(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-1",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function auth(ip,port,login,password){const serverUrl=`http://${ip}:${port}`;const pass=await sha1(password);const r=await fetch(`${serverUrl}/resto/api/auth?login=${encodeURIComponent(login)}&pass=${pass}`,{cache:"no-store"});const token=(await r.text()).trim();if(!r.ok||!token)throw new Error(`Ошибка авторизации SH Server: HTTP ${r.status}`);return {serverUrl,token};}
function xmlDecode(v){return String(v??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");}
function localName(name){return String(name||"").split(":").pop().toLowerCase();}
function cleanId(v){return String(v??"").trim().replace(/^\{+|\}+$/g,"").toLowerCase();}
function cleanName(v){return String(v??"").trim();}
function tag(block,name){const wanted=localName(name);const re=/<([A-Za-z][\w:.-]*)\b[^>]*>([\s\S]*?)<\/\1>/gi;let m;while((m=re.exec(String(block||""))))if(localName(m[1])===wanted)return xmlDecode(m[2].trim());return "";}
function blocks(source,names){const wanted=new Set((Array.isArray(names)?names:[names]).map(localName));const text=String(source||"");const out=[];const open=/<([A-Za-z][\w:.-]*)\b[^>]*>/gi;let m;while((m=open.exec(text))){const fullName=m[1],local=localName(fullName);if(!wanted.has(local))continue;const close=new RegExp(`</${fullName.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}>`,'i');const tail=text.slice(open.lastIndex);const cm=close.exec(tail);if(cm)out.push(text.slice(m.index,open.lastIndex+cm.index+cm[0].length));}return out;}
function parseJsonRefs(value,out){if(Array.isArray(value)){for(const x of value)parseJsonRefs(x,out);return;}if(!value||typeof value!=="object")return;const id=value.id??value.uuid??value.entityId??value.storeId??value.supplierId;const name=value.name??value.title??value.description;if(id&&name){const sid=cleanId(id),sname=cleanName(name);if(sid&&sname)out.push({id:sid,name:sname});}for(const v of Object.values(value))if(v&&typeof v==="object")parseJsonRefs(v,out);}
function parseXmlAttributeRefs(source,out,seen){const names=new Set(["supplier","supplierdto","store","storedto","corporateitemdto","item","entity","entitydto","department","warehouse","product","productdto","employee","employeedto"]);const re=/<([A-Za-z][\w:.-]*)\b([^>]*)>/gi;let m;while((m=re.exec(String(source||"")))){if(!names.has(localName(m[1])))continue;const attrs={};const ar=/([A-Za-z][\w:.-]*)\s*=\s*(["'])(.*?)\2/g;let a;while((a=ar.exec(m[2])))attrs[localName(a[1])]=xmlDecode(a[3]);const id=attrs.id||attrs.uuid||attrs.entityid||attrs.storeid||attrs.supplierid;const name=attrs.name||attrs.title||attrs.description;if(id&&name){const sid=cleanId(id),sname=cleanName(name);if(sid&&sname&&!seen.has(sid)){seen.add(sid);out.push({id:sid,name:sname});}}}}
function parseReferenceList(value){const source=String(value||"").trim();const result=[];const seen=new Set();if(!source)return result;if(source[0]==="{"||source[0]==="["){try{const raw=[];parseJsonRefs(JSON.parse(source),raw);for(const x of raw){const id=cleanId(x.id),name=cleanName(x.name);if(id&&name&&!seen.has(id)){seen.add(id);result.push({id,name});}}if(result.length)return result;}catch{}}
parseXmlAttributeRefs(source,result,seen);const names=["supplier","supplierDto","store","storeDto","corporateItemDto","item","entity","entityDto","department","warehouse","product","productDto","employee","employeeDto"];for(const b of blocks(source,names)){const id=tag(b,"id")||tag(b,"uuid")||tag(b,"entityId");const name=tag(b,"name")||tag(b,"title")||tag(b,"description");if(id&&name){const sid=cleanId(id),sname=cleanName(name);if(sid&&sname&&!seen.has(sid)){seen.add(sid);result.push({id:sid,name:sname});}}}return result;}
function parseSupplierList(value){const source=String(value||"").trim();const result=[];const seen=new Set();const add=(id,name)=>{const sid=cleanId(id),sname=cleanName(name);if(sid&&sname&&!seen.has(sid)){seen.add(sid);result.push({id:sid,name:sname});}};if(!source)return result;if(source[0]==="{"||source[0]==="["){try{const walk=v=>{if(Array.isArray(v)){for(const x of v)walk(x);return;}if(!v||typeof v!=="object")return;const name=v.name??v.title??v.description;const supplierId=typeof v.supplier==="string"?v.supplier:null;const id=v.supplierId??supplierId??v.id??v.uuid??v.entityId;if(id&&name)add(id,name);for(const x of Object.values(v))if(x&&typeof x==="object")walk(x);};walk(JSON.parse(source));if(result.length)return result;}catch{}}
parseXmlAttributeRefs(source,result,seen);for(const b of blocks(source,["employee","employeeDto"])){const name=tag(b,"name")||tag(b,"title");const supplierId=tag(b,"supplier")||tag(b,"supplierId");const employeeId=tag(b,"id")||tag(b,"uuid")||tag(b,"entityId");if(name){if(supplierId)add(supplierId,name);if(employeeId)add(employeeId,name);}}return result;}
async function request(serverUrl,path){const r=await fetch(`${serverUrl}${path}`,{cache:"no-store",headers:{Accept:"application/json, application/xml, text/xml, */*"}});return {ok:r.ok,status:r.status,text:await r.text(),contentType:r.headers.get("content-type")||""};}
async function ensure(db){if(!db)throw new Error("D1 binding DB не настроен");await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_suppliers (scope_id TEXT NOT NULL,supplier_id TEXT NOT NULL,supplier_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,supplier_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_warehouses (scope_id TEXT NOT NULL,warehouse_id TEXT NOT NULL,warehouse_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,warehouse_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_products (scope_id TEXT NOT NULL,product_id TEXT NOT NULL,product_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,product_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_product_groups (scope_id TEXT NOT NULL,group_id TEXT NOT NULL,group_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,group_id))`),db.prepare(`CREATE TABLE IF NOT EXISTS sh_iiko_product_categories (scope_id TEXT NOT NULL,category_id TEXT NOT NULL,category_name TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(scope_id,category_id))`)]);}
async function readMap(db,table,idCol,nameCol,scope){const r=await db.prepare(`SELECT ${idCol} id,${nameCol} name FROM ${table} WHERE scope_id=?1`).bind(scope).all();return new Map((r.results||[]).filter(x=>x?.id&&x?.name).map(x=>[cleanId(x.id),cleanName(x.name)]));}
async function save(db,table,idCol,nameCol,scope,rows){if(!rows.length)return;const now=new Date().toISOString();for(let i=0;i<rows.length;i+=50){const batch=rows.slice(i,i+50).map(x=>db.prepare(`INSERT INTO ${table}(scope_id,${idCol},${nameCol},updated_at) VALUES(?1,?2,?3,?4) ON CONFLICT(scope_id,${idCol}) DO UPDATE SET ${nameCol}=excluded.${nameCol},updated_at=excluded.updated_at`).bind(scope,cleanId(x.id),cleanName(x.name),now));await db.batch(batch);}}
async function loadRef(serverUrl,token,paths,parser=parseReferenceList){const list=Array.isArray(paths)?paths:[paths];let last=null;for(const path of list){try{const r=await request(serverUrl,`${path}${path.includes("?")?"&":"?"}key=${encodeURIComponent(token)}`);last=r;if(r.ok){const rows=parser(r.text);if(rows.length)return {rows,status:r.status,contentType:r.contentType,rawLength:r.text.length,path};}}catch(e){last={ok:false,status:0,text:String(e?.message||e)}}}if(last&&!last.ok)throw new Error(`iiko reference HTTP ${last.status}`);return {rows:[],status:last?.status||0,contentType:last?.contentType||"",rawLength:last?.text?.length||0,path:list[list.length-1]};}
async function loadAll(serverUrl,token){const defs={suppliers:["/resto/api/suppliers","/resto/api/corporation/suppliers"],warehouses:["/resto/api/corporation/stores"],products:["/resto/api/v2/entities/products/list?includeDeleted=true","/resto/api/products"],groups:["/resto/api/v2/entities/products/group/list?includeDeleted=true"],categories:["/resto/api/v2/entities/products/category/list?includeDeleted=true"]};const out={};for(const [key,paths] of Object.entries(defs)){try{out[key]=await loadRef(serverUrl,token,paths,key==="suppliers"?parseSupplierList:parseReferenceList);}catch(e){out[key]={rows:[],status:0,contentType:"",rawLength:0,path:paths[0],error:String(e?.message||e)}}}return out;}
export async function syncReferences(env,serverUrl,token){await ensure(env.DB);const scope=await sha1(serverUrl.toLowerCase());const refs=await loadAll(serverUrl,token);await Promise.all([save(env.DB,"sh_iiko_suppliers","supplier_id","supplier_name",scope,refs.suppliers.rows),save(env.DB,"sh_iiko_warehouses","warehouse_id","warehouse_name",scope,refs.warehouses.rows),save(env.DB,"sh_iiko_products","product_id","product_name",scope,refs.products.rows),save(env.DB,"sh_iiko_product_groups","group_id","group_name",scope,refs.groups.rows),save(env.DB,"sh_iiko_product_categories","category_id","category_name",scope,refs.categories.rows)]);const suppliers=await readMap(env.DB,"sh_iiko_suppliers","supplier_id","supplier_name",scope),warehouses=await readMap(env.DB,"sh_iiko_warehouses","warehouse_id","warehouse_name",scope),products=await readMap(env.DB,"sh_iiko_products","product_id","product_name",scope),groups=await readMap(env.DB,"sh_iiko_product_groups","group_id","group_name",scope),categories=await readMap(env.DB,"sh_iiko_product_categories","category_id","category_name",scope);return {suppliers,warehouses,products,groups,categories,diagnostics:{suppliers:{httpStatus:refs.suppliers.status,contentType:refs.suppliers.contentType,rawLength:refs.suppliers.rawLength,parsedCount:refs.suppliers.rows.length,path:refs.suppliers.path,error:refs.suppliers.error||null},warehouses:{httpStatus:refs.warehouses.status,contentType:refs.warehouses.contentType,rawLength:refs.warehouses.rawLength,parsedCount:refs.warehouses.rows.length,path:refs.warehouses.path,error:refs.warehouses.error||null},products:{httpStatus:refs.products.status,contentType:refs.products.contentType,rawLength:refs.products.rawLength,parsedCount:refs.products.rows.length,path:refs.products.path,error:refs.products.error||null}}};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:corsHeaders()});}
export async function onRequestPost({request,env}){try{const b=await request.json();const ip=String(b.ip||"").trim(),port=String(b.port||"").trim(),login=String(b.login||"").trim(),password=String(b.password||"");if(!ip||!port||!login||!password)return json({success:false,message:"Заполните IP, порт, логин и пароль SH Server"},400);const {serverUrl,token}=await auth(ip,port,login,password);const refs=await syncReferences(env,serverUrl,token);return json({success:true,source:"iiko-sync+d1",supplierCount:refs.suppliers.size,warehouseCount:refs.warehouses.size,productCount:refs.products.size,groupCount:refs.groups.size,categoryCount:refs.categories.size,diagnostics:refs.diagnostics,suppliers:Object.fromEntries(refs.suppliers),warehouses:Object.fromEntries(refs.warehouses),products:Object.fromEntries(refs.products),groups:Object.fromEntries(refs.groups),categories:Object.fromEntries(refs.categories)});}catch(e){return json({success:false,message:e?.message||"Ошибка загрузки справочников iiko"},502);}}