name: anarsystem_mobile
description: AnarSystem mobile application for restaurant analytics and management.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2

flutter:
  uses-material-design: true
