import { getUser } from './iiko/_lib/user-state.js';

function cors(){return{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization'}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...cors()}})}
function clean(v){return String(v??'').trim()}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function dateOnly(v){const s=clean(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:''}
function nowIso(){return new Date().toISOString()}
function dayDiff(date){if(!date)return null;const a=new Date(`${date}T00:00:00Z`),b=new Date();const today=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate());return Math.ceil((a.getTime()-today)/86400000)}
function monthIndex(date){const s=dateOnly(date);if(!s)return null;const [y,m]=s.slice(0,7).split('-').map(Number);return y*12+(m-1)}
function assetMath(asset){const cost=Math.max(0,num(asset.purchase_cost)),salvage=Math.max(0,Math.min(cost,num(asset.salvage_value))),life=Math.max(1,Math.trunc(num(asset.useful_life_months)||1));const start=monthIndex(asset.in_service_date),now=monthIndex(new Date().toISOString().slice(0,10));let months=0;if(start!==null&&now!==null&&now>=start)months=Math.max(0,Math.min(life,now-start+1));const monthly=(cost-salvage)/life,acc=Math.min(cost-salvage,monthly*months);return{monthlyDepreciation:monthly,bookValue:Math.max(salvage,cost-acc),depreciatedMonths:months,lifeRatio:Math.min(1,months/life)}}
async function ensure(db){if(!db)throw new Error('D1 binding DB не настроен.');await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS fixed_asset_meta (
    asset_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    warranty_until TEXT NOT NULL DEFAULT '',
    next_service_date TEXT NOT NULL DEFAULT '',
    replacement_cost REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_fixed_asset_meta_user ON fixed_asset_meta(user_id, asset_id)`)
]);}
async function auth(request,env){const a=await getUser(request,env);if(!a)return null;await ensure(env.DB);return a}
function recommendation(asset,meta,totalRepair,repair12m){const m=assetMath(asset),replacement=Math.max(0,num(meta?.replacement_cost));let code='KEEP',label='Эксплуатировать дальше',reason='Существенных признаков для замены пока нет.';const serviceDays=dayDiff(meta?.next_service_date),warrantyDays=dayDiff(meta?.warranty_until);if(asset.status==='DISPOSED'||asset.status==='SOLD'){code='ARCHIVED';label='Объект выбыл';reason='Объект больше не участвует в эксплуатации.'}else if(replacement>0&&repair12m>=replacement*.4){code='REVIEW_REPLACE';label='Проверить замену';reason='Расходы на ремонт за 12 месяцев достигли 40% или больше стоимости нового аналога.'}else if(replacement>0&&m.lifeRatio>=.8&&repair12m>=replacement*.2){code='REVIEW_REPLACE';label='Проверить замену';reason='Объект использовал не менее 80% срока службы, а ремонты за год уже значительны.'}else if(replacement<=0&&m.lifeRatio>=.9&&repair12m>=Math.max(1,m.bookValue)*.3){code='REVIEW_REPLACE';label='Проверить замену';reason='Срок службы почти исчерпан, а затраты на ремонт заметны относительно остаточной стоимости.'}else if(serviceDays!==null&&serviceDays<0){code='SERVICE_DUE';label='Требуется ТО';reason='Дата планового обслуживания уже прошла.'}else if(warrantyDays!==null&&warrantyDays>=0){code='WARRANTY';label='На гарантии';reason='Гарантийный срок ещё действует.'}
return{code,label,reason,lifeRatio:m.lifeRatio,bookValue:m.bookValue,replacementCost:replacement,totalRepairCost:totalRepair,repairCost12m:repair12m,warrantyDaysRemaining:warrantyDays,nextServiceDays:serviceDays,warrantyActive:warrantyDays!==null&&warrantyDays>=0,serviceOverdue:serviceDays!==null&&serviceDays<0}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:cors()})}
export async function onRequestGet({request,env}){try{const a=await auth(request,env);if(!a)return json({success:false,message:'Требуется авторизация'},401);let assets=[];try{const r=await env.DB.prepare(`SELECT * FROM fixed_assets WHERE user_id=?1 ORDER BY name COLLATE NOCASE`).bind(a.user.id).all();assets=r.results||[]}catch{return json({success:true,items:[]})}const metas=await env.DB.prepare(`SELECT * FROM fixed_asset_meta WHERE user_id=?1`).bind(a.user.id).all();const metaMap=new Map((metas.results||[]).map(x=>[x.asset_id,x]));let events=[];try{const r=await env.DB.prepare(`SELECT asset_id,event_type,event_date,cost FROM fixed_asset_events WHERE user_id=?1`).bind(a.user.id).all();events=r.results||[]}catch{}const cutoff=new Date();cutoff.setUTCFullYear(cutoff.getUTCFullYear()-1);const cutoffDate=cutoff.toISOString().slice(0,10);const byAsset=new Map();for(const e of events){if(!['BREAKDOWN','REPAIR','MAINTENANCE','PART'].includes(String(e.event_type||'').toUpperCase()))continue;const s=byAsset.get(e.asset_id)||{total:0,last12:0};const cost=Math.max(0,num(e.cost));s.total+=cost;if(String(e.event_date||'')>=cutoffDate)s.last12+=cost;byAsset.set(e.asset_id,s)}const items=assets.map(asset=>{const meta=metaMap.get(asset.id)||{asset_id:asset.id,warranty_until:'',next_service_date:'',replacement_cost:0};const costs=byAsset.get(asset.id)||{total:0,last12:0};return{assetId:asset.id,name:asset.name,status:asset.status,restaurantId:asset.restaurant_id||'',category:asset.category||'',location:asset.location||'',inventoryNumber:asset.inventory_number||'',warrantyUntil:meta.warranty_until||'',nextServiceDate:meta.next_service_date||'',replacementCost:num(meta.replacement_cost),...recommendation(asset,meta,costs.total,costs.last12)}});return json({success:true,items})}catch(e){return json({success:false,message:e.message||String(e)},500)}}
export async function onRequestPost({request,env}){try{const a=await auth(request,env);if(!a)return json({success:false,message:'Требуется авторизация'},401);const b=await request.json().catch(()=>({}));const assetId=clean(b.assetId);if(!assetId)return json({success:false,message:'Не указан объект'},400);const asset=await env.DB.prepare(`SELECT id FROM fixed_assets WHERE id=?1 AND user_id=?2`).bind(assetId,a.user.id).first();if(!asset)return json({success:false,message:'Объект не найден'},404);const warranty=dateOnly(b.warrantyUntil),service=dateOnly(b.nextServiceDate),replacement=Math.max(0,num(b.replacementCost)),now=nowIso();await env.DB.prepare(`INSERT INTO fixed_asset_meta(asset_id,user_id,warranty_until,next_service_date,replacement_cost,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?6) ON CONFLICT(asset_id) DO UPDATE SET warranty_until=excluded.warranty_until,next_service_date=excluded.next_service_date,replacement_cost=excluded.replacement_cost,updated_at=excluded.updated_at WHERE user_id=excluded.user_id`).bind(assetId,a.user.id,warranty,service,replacement,now).run();return json({success:true})}catch(e){return json({success:false,message:e.message||String(e)},500)}}