-- ANAR SYSTEM: plugin event storage
-- Run this migration in Supabase SQL Editor.

create table if not exists public.plugin_events (
  id bigint generated by default as identity primary key,
  event_id text,
  event_type text not null,
  event_timestamp timestamptz,
  received_at timestamptz not null default now(),
  department_id uuid not null,
  department_name text,
  plugin_id text,
  plugin_version text,
  server_url text,
  currency_code text,
  group_id text,
  group_name text,
  payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null
);

create unique index if not exists plugin_events_event_id_uq
  on public.plugin_events(event_id)
  where event_id is not null;

create index if not exists plugin_events_department_time_idx
  on public.plugin_events(department_id, event_timestamp desc);

create index if not exists plugin_events_type_time_idx
  on public.plugin_events(event_type, event_timestamp desc);

alter table public.plugin_events enable row level security;

-- Browser users can read events only after authentication.
create policy if not exists "authenticated users can read plugin events"
  on public.plugin_events for select
  to authenticated
  using (true);

-- Inserts are performed by the Cloudflare Function with the service role key,
-- so the browser does not receive direct insert permission.
